### ISSUE TITLE
Failed to connect to Common Data Service

### ISSUE THREAD

**Issue by AndrewTheWild** [microsoft/PowerPlatform-DataverseServiceClient#100]
I am trying to connect CDS.I got message.I am using .Net Core
![image](https://user-images.githubusercontent.com/57155452/108727021-c2ae1280-7530-11eb-8cb6-2fb045a05280.png) 
I test my credentials on .Net and everything works.
Can you help me with this ploblem?

**Comment by MattB-msft** [comment]
which authentication type are you trying to use? 
Can you provide the connection string w/out the URL or Secrets?

**Comment by AndrewTheWild** [comment]
Client Secret
https://xrmdynamicscrm.wordpress.com/2020/07/19/connect-to-dynamics-crm-online-using-net-core-sdk/ -I used this example

**Comment by MattB-msft** [comment]
If you are using it directly, it will not work.  You would need to create and setup your own application id locally to your tenant.  did you do that? 

also there should have been more to the exception indicating that/.   Can you paste the full exception?

**Comment by AndrewTheWild** [comment]
Yes I do.
It is full exception

**Comment by BetimBeja** [comment]
@AndrewTheWild you can read [this](https://www.linkedin.com/pulse/microsoftpowerplatformcdsclient-betim-beja/) article I wrote on LinkedIn with all the steps needed to configure client secret authentication.

Also, you can find a basic implementation [here](https://github.com/albanian-xrm/CdsClient-Demo)

**Comment by MattB-msft** [comment]
@AndrewTheWild  did @BetimBeja  direction help you ?  are you still stuck?

**Comment by MattB-msft** [comment]
No response from @AndrewTheWild ,  Going to close this for now, 
if your still stuck Andrew, Please reopen.
