### ISSUE TITLE
Expose Activity ID on CdsClientOperationException

### ISSUE THREAD

**Issue by onsvejda** [microsoft/PowerPlatform-DataverseServiceClient#101]
Platform uses ActivityId (kusto: WebRequestStatistics.ActivityId) as a way to correlate incoming calls. This is also exposed in http headers - however in case of failure this is not exposed in the `CdsClientOperationException` exception.

For WCF it is `FaultException<OrganizationServiceFault>.Detail.ActivityId` / for ODATA it is `HttpOperationException.Headers["REQ_ID"]`

But ideally underlying client should be transparent and activity id should be accessible on "logical" exception level.

**Comment by MattB-msft** [comment]
The request ID is attached to the organization requests as "requestid",  you can set that before you send the request, or you can enabled verbose logging to see the request ID's the system auto assigns. 

You can also set "sessionId" to group requests together 

Low level server activity id's are returned in the Exception.details object.

**Comment by MattB-msft** [comment]
@onsvejda Just confirming... when you get such an exception, you should find the HttpOperationException on the inner exception? 
 that also has the properties your looking for.   Can you confirm?

**Comment by onsvejda** [comment]
@MattB-msft - yes I can - I was just wondering since we shouldn't know about the internal implementation if this shouldn't be propagated to higher logical level :)

**Comment by MattB-msft** [comment]
@onsvejda , 
The field your asking about is only relevant to first party internal implementations who have visibility to our internal telemetry systems :) 

For external use the RequestID and Session ID are what are provided to support, which then is used with CAP Telem to xref back to the internal telemetry .

Either way we will see if we can get this put in the top level exception for you.
