### ISSUE TITLE
Unable to connect using ServiceClient

### ISSUE THREAD

**Issue by andrew-sumner** [microsoft/PowerPlatform-DataverseServiceClient#112]
I'm struggling to connect my AzureFunctions to our dynamics 365 instances using ServiceClient when running within Visual Studio (haven't tested when deployed to Azure). Is there anything obvious that I'm doing wrong?

**Dependencies:**
```
<PackageReference Include="Azure.Identity" Version="1.3.0" />
<PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" Version="0.4.6" />
```

## Managed Identity Example
```
var client = new ServiceClient(new Uri(d365url), GetTokenAsync, false, logger);

private static async Task<string> GetTokenAsync(string instanceUri)
{
    var credential = new DefaultAzureCredential(false);

    var properScope = new Uri(instanceUri).GetComponents(UriComponents.SchemeAndServer, UriFormat.UriEscaped);
    var acessToken = await credential.GetTokenAsync(new TokenRequestContext(new[] { properScope }));

    return acessToken.Token;
}
```

**Fails With:**
MsalServiceException: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://devsupporttt.crm6.dynamics.com offline_access openid profile is not valid. The scope format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>.

## ConnectionString Example
```
var connectionString = "AuthType=OAuth;Username=***;Url=https://***.crm6.dynamics.com;AppId=51f81489-12ee-4a9e-aaae-a2591f45987d;RedirectUri=app://58145B91-0C36-4500-8554-080854F2AC97;LoginPrompt=Always";

var client = new ServiceClient(connectionString, logger);
```
**Fails With:**
MsalClientException: Only loopback redirect uri is supported, but app://58145b91-0c36-4500-8554-080854f2ac97/ was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details

**Comment by mathiasbl** [comment]
Regarding managed identities you have to specify a valid scope. This can be either default or user_impersonation.
Example https://xx.crm4.dynamics.com/.default or https://xx.crm4.dynamics.com/.user_impersonation

The user_impersonation scope is only used for client applications. For non_interactive apps the .default scope suits better.

Here's the snippet of code I use in my azure function.

```
    private static CdsServiceClient GetClient()
        {
            var cdsServiceUri = Environment.GetEnvironmentVariable("CdsServiceUri");
            var credentials = new EnvironmentCredential();

            var client = new CdsServiceClient(new Uri(cdsServiceUri), async (resourceUri) =>
            {
                var context = new TokenRequestContext(scopes: new[] { $"{cdsServiceUri}/.default" });
                var token = await credentials.GetTokenAsync(context).ConfigureAwait(false);

                return token.Token;
            });

            return client.IsReady ? client : throw client.LastCdsException;
        }
```

**Comment by MattB-msft** [comment]
Also Regarding the use of the OAuth flow,  for RedirectUri,  Please try to use RedirectUri=http://localhost .   that should cause a window to pop and aquire your UID\PW
