### ISSUE TITLE
The ServiceClient doesn't work in Blazor (Server)

### ISSUE THREAD

**Issue by kowgli** [microsoft/PowerPlatform-DataverseServiceClient#113]
Hello,

I am trying to use the service client in Blazor Server (.NET 5 running on Windows) and it doesn't seem to work when I try to create a new instance from inside a Blazor component (directly or indirectly).

When I try something like:
`ServiceClient serviceClient = new ServiceClient(myConnectionString);`
it just hangs indefinitely. 

When I do the same in Startup.cs it works, but that's not really a solution. I need a separate instance per circuit, since the client doesn't seem to be thread safe and an error would affect all users.

Sample project to replicate (stock Blazor Server template with a few lines changed inside Index.razor).
https://github.com/kowgli/Dataverse-ServiceClient-BlazorServer-Issue/blob/master/BlazorCrm/Pages/Index.razor

**Comment by kowgli** [comment]
Solved it :) Looked into the code and figured out it's some async issue. Maybe a missing ConfigureAwait(false)?

This works:
```
protected override async Task OnInitializedAsync()
{
	string connectionStr = "authtype=ClientSecret;url=https://****;clientid=****;clientsecret=****";

	ServiceClient serviceClient = await Task<ServiceClient>.Run(() =>
	{
		ServiceClient serviceClient = new ServiceClient(connectionStr);
		return serviceClient;
	});      
}
```

**Comment by MattB-msft** [comment]
hrm.  We do not yet have a Blazor test case working yet @kowgli ,  thanks for finding this. 
So by new-ing up the ServiceClient directly, w/out the Task .Run it hung up on you?

I have personally seen this in functions, however I thought we had resolved it.. 
We will go back and see if there is a non await happening in the pipeline. 

We will check into this..
thanks for raising it.

**Comment by kowgli** [comment]
@MattB-msft 
Yes exactly. If just new-ed up inside a component it hangs.

**Comment by MattB-msft** [comment]
@kowgli 
Following up on this... we finally had some time to run this done and we have fixed it in an upcoming drop. 
You were correct in that we were missing a few ConfigureAwaits . 
thanks
