### ISSUE TITLE
[Question] Any ETA?

### ISSUE THREAD

**Issue by andrew-sumner** [microsoft/PowerPlatform-DataverseServiceClient#114]
Response to issue #65 stated that only waiting on MSAL support before going to beta / 1.0. 

I believe this has been completed, so any idea when this might be released?

**Comment by MattB-msft** [comment]
In discussion with our partner teams, we reset that timeline to require a much higher level of WebAPI support then the current support in DataverseClient ( that being Create / Update / Delete only ) 

Say tuned...

**Comment by peterbjorkmarker** [comment]
I have been trying it out fairly extensively with .Net Core and Azure Functions v3. Good work, feels solid for my use cases!  

Can't use an alpha version in prod though... :) Should I hope for a beta in a few months or revert to something less exciting? Anything I can do to help shorting the timeline?

**Comment by jordimontana82** [comment]
Hi Matt,

There was a  package pushed a couple of days ago stating it's in public preview in its description (v0.4.12). 

All the v0.4.x releases have removed the -Alpha tag compared to the v0.3.x ones. However the README on this repo still says it's in alpha release, which is a bit confusing...  Are these new packages in beta, or still in alpha?

What does public preview mean, if the source code was already public I mean?

Thanks!

**Comment by filcole** [comment]
See some info here: https://github.com/microsoft/PowerPlatform-DataverseServiceClient/issues/133#issuecomment-851704674

**Comment by MattB-msft** [comment]
going to close this thread and keep #133 going
