### ISSUE TITLE
Error: Does not support untyped value in non-open type

### ISSUE THREAD

**Issue by mathiasbl** [microsoft/PowerPlatform-DataverseServiceClient#115]
When updating an entity where a lookup is set to null you get the error 'Error: Does not support untyped value in non-open type'

Example:
```
var entity = new Entity("opportunity", myid);
entity["contactid"] = null;

client.Update(entity);
```

This is being translated to:
PATCH https://xxxx.api.crm4.dynamics.com/api/data/v9.2/opportunities(xxxx)

{
      "contactid": null
}

Which results in this error:
```
An error occurred while validating input parameters: Microsoft.OData.ODataException: Does not support untyped value in non-open type.\r\n   at System.Web.OData.Formatter.Deserialization.DeserializationHelpers.ApplyProperty(ODataProperty property, IEdmStructuredTypeReference resourceType, Object resource, ODataDeserializerProvider deserializerProvider, ODataDeserializerContext readContext)\r\n   at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyStructuralProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)\r\n   at Microsoft.Crm.Extensibility.CrmODataEntityDeserializer.ApplyStructuralProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)\r\n   at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadResource(ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)\r\n   at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
```

**Comment by mathiasbl** [comment]
Looking at the code (see link below) the foreach over the attributes should use the attributemetadata to determine the type of the value not the otherway around.

If the attribute is a lookup and is set to null this should translate to:

```
{
"contactid@odata.bind": null
}
```

https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/9f25d39708e7ab32318f61e9c8cfbfaeec6c1f05/src/GeneralTools/DataverseClient/Client/Utils/Utils.cs#L342

**Comment by MattB-msft** [comment]
Yes. this was the result of a number of tradeoffs for perf and trying to reduce calls for metadata. 
Let me see if we can work though way to accommodate this for lookups.

**Comment by lnetrebskii** [comment]
Hi! Is there a workaround for this bug?

**Comment by MattB-msft** [comment]
Still working on a fix for this folks, it just didn't make it to the official stream due to failing tests

**Comment by MattB-msft** [comment]
Following up again... As we are digging more into this, the behavior seems to be inconsistent depending on the related entity..  We are looking more into it.

**Comment by MattB-msft** [comment]
Fix in route now.

**Comment by lnetrebskii** [comment]
It works partially. We use "key"
`
key = $"{key}@odata.bind";
`
This does not work for all properties. We should use navigationPropertyName instead:
```
var navigationPropertyName = metadata.ManyToOneRelationships.FirstOrDefault(w =>
        w.ReferencingAttribute.Equals(attribute.Key) &&
        w.ReferencedEntity.Equals(attribData.Targets.First()))
    ?.ReferencingEntityNavigationPropertyName;

key = $"{navigationPropertyName}@odata.bind";
