### ISSUE TITLE
MetadataUtility class doesn't check the LastException property

### ISSUE THREAD

**Issue by mathiasbl** [microsoft/PowerPlatform-DataverseServiceClient#116]
The MetadataUtility does calls to retrieve metadata. However, for example, when the client is being throttled and the retry limit is reached the response you receive is null. The MetadataUtility doesn't check this and just returns null causing some null reference errors in your codebase or errors like 'entity or attribute' does not exist.

When the response is null it should check whether it has a LastException before assuming the entity doesn't exist.

Example line here:
https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/9f25d39708e7ab32318f61e9c8cfbfaeec6c1f05/src/GeneralTools/DataverseClient/Client/MetadataUtility.cs#L85

**Comment by MattB-msft** [comment]
@mathiasbl your reporting this as consequence of throttling, The cmd Execute should have gone into retry mode.. thus I am assuming that it is the result of giving up, and the request ultimately fails. 

is your concern that the error message is misleading? 

thanks

**Comment by mathiasbl** [comment]
Yeah, the message is misleading.

Don't forget that developers can manipulate the maxretrycount. So in theory they could disable the built in retry.
