### ISSUE TITLE
Query to filter by Boolean doesn't work

### ISSUE THREAD

**Issue by rmencia-isv** [microsoft/PowerPlatform-DataverseServiceClient#118]
I have some code to filter by a boolean property that used to work well when I run the code in .net framework but it doesn't work with this Client version.
If I run the query using a Text field, the filter works well. 
I'm not sure still the pattern, because I have tried some boolean fields that were working in the same entity.
The result is that it doesn't bring any value at all.

DOES NOT WORK
var accounts1 = context.AccountSet
                  .Where(account => account.isv_Member == true)
                  .ToList();

var accounts1 = context.AccountSet
                  .Where(account => account.isv_Member)
                  .ToList();

WORKS
var accounts2 = context.AccountSet
                  .Where(account => account.Name == "Account Name")
                  .ToList();

It seems that some of the properties work well but not others. Also I haven't found a pattern for when the properties are Custom or Managed or Unmanaged.
The only thing is that the filters used to work with .net 4.6 using Microsoft.Crm.Sdk vs 9.0.2.5 of the nuget package.

**Comment by MattB-msft** [comment]
@rmencia-isv there are a few different things going on here. 
can you check the current value of account.isv_member to determine if there a value there for the compare to work? 

I ask, because the code between full framework and .net core client code is not different for Linq execution.  Also this code is the same code currently in use in CrmServiceClient.

**Comment by rmencia-isv** [comment]
This is supposed to create a query that is executed in Dynamics to retrieve the values from the server.

Taking the following code, if I run in debug mode with breakpoints, I can see how I get 1 result with the first statement, I go to Dynamics, I change the value to "No" and I move the cursor to run it again and it doesn't return any value. 
The second Statement is executed afterwards and I get no results, but there should be a number of results coming back. 
I can move the cursor back and forth while changing the values in the server and the first query always returns the right values but not the second one. This very same code works when executed in the application running with the .net 4.6 and the previous packages.

            accounts1 = context.AccountSet
                  .Where(account => account.CreditOnHold == true)
                  .ToList();

            accounts1 = context.AccountSet
                  .Where(account => account.isv_Member == true)
                  .ToList();

Is there a way to get access to the Query before being sent to Dynamics? (a JSON or XML or similar?) That would help to compare both.

Note: They are generated using the XrmToolBox tools and they both look the same. They are both Nullable<bool>. 

		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("creditonhold")]
		public System.Nullable<bool> CreditOnHold
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("creditonhold");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreditOnHold");
				this.SetAttributeValue("creditonhold", value);
				this.OnPropertyChanged("CreditOnHold");
			}
		}

		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isv_member")]
		public System.Nullable<bool> isv_Member
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isv_member");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("isv_Member");
				this.SetAttributeValue("isv_member", value);
				this.OnPropertyChanged("isv_Member");
			}
		}

**Comment by rmencia-isv** [comment]
This is the result with .net 4.6 old nuget packages

![image](https://user-images.githubusercontent.com/82075665/113957277-42363d80-9862-11eb-866c-a288337382be.png)

This is the same with the new one with .net 5 and new nuget packages:

![image](https://user-images.githubusercontent.com/82075665/113957522-ba046800-9862-11eb-8fde-dc7cf76af55e.png)

As you can see the results are different with the same query, one returns 598 and the other 0

**Comment by rmencia-isv** [comment]
I have done additional research and I managed to make it work. 
It seems that the issue was due to permissions. 
The user I was using for 4.6 had assigned different roles in Dynamics and the user for the new version didn't have the same roles.

Somehow, that was making that the queries were returning no results with some properties in the filter, but it was working with some other properties (maybe the permissions to access the data in those properties). 
I made my API user sysadmin and it started returning results after I updated the permissions.

That was very confusing and it should have probably returned exceptions from Dynamics instead of no results.

**Comment by BetimBeja** [comment]
> Is there a way to get access to the Query before being sent to Dynamics? (a JSON or XML or similar?) That would help to compare both.

You can use a plugin registered with the `RetrieveMultiple` message of the interested table (`account` in your case)

**Comment by MattB-msft** [comment]
@rmencia-isv thanks for the feedback, Glad you got it sorted out. 

A comment on your suggestion.. 
Security preventing visibility of data in a general query is not an error situation,  That is part of the design of the security system of Dataverse.   

Had you asked for a specific record, by ID, using a RetrieveRequest,  and you did not have permissions, you would have received an exception from the server indicating that you do not have permissions to access the record. 

Linq commands execute the RetrieveMultiple command on the server. This is an equivalent of "Select <fieldlist> from <entity> where <conditions>".  in such a query in dataverse, if you do not have permissions for rows in the target entity,  the query will not return data.
