### ISSUE TITLE
When updating a DateTime attribute, time is truncated

### ISSUE THREAD

**Issue by lnetrebskii** [microsoft/PowerPlatform-DataverseServiceClient#123]
When updating a DateTime attribute with format Xrm.Sdk.Metadata.DateTimeFormat.DateOnly, time is truncated. Meanwhile, the format specifies how data should [be displayed](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.metadata.datetimeformat?view=dynamics-general-ce-9). It is not related to how to store dates.

Updates from forms to such fields and via OData API allows storing time fraction.

Data truncating happens [here](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/9f25d39708e7ab32318f61e9c8cfbfaeec6c1f05/src/GeneralTools/DataverseClient/Client/Utils/Utils.cs#L434).

I suppose, instead of truncating data for fields with DateOnly format, it should have happened to fields with DateTimeBehavior == DateTimeBehavior.DateOnly.

**Comment by MattB-msft** [comment]
Thanks, Fix in route now.
