### ISSUE TITLE
Cannot connect to the dataverse after multiple successful connection.

### ISSUE THREAD

**Issue by abisheksharma** [microsoft/PowerPlatform-DataverseServiceClient#134]
` var connectionString = $@"
                AuthType=OAuth;
                Username={username};
                Password={password};
                Url={url};
                AppId={appId};
                RedirectUri={redirectUrl};
                TokenCacheStorePath=d:\MyTokenCache;
                LoginPrompt=Auto
            ";
            try
            {
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
                organizationService = new ServiceClient(connectionString);
}`

I am using above method to connect to the dynamics 365 and it works until it doesn't and I get error saying 

> Cannot connect to the dataverse

 and it redirects me to the login page but I don't want this to happen. If I don't do anything it fixes the issue in a minute or so. So, I was wondering is this some type of **DDOS** protection scenario or something? As this only happens when I do 10 or more calls to the **Dataverse** in a short period of time. I was using the 0.4.6 and then upgraded to the latest 0.4.12 but the issue still persists. Any help is appreciated.

**Comment by MattB-msft** [comment]
I suspect your correct, in that you are seeing AAD block your login. 
If you enabled Logging on the client you should see AAD's actual error code. 

That said, 
TokenCacheStorePath is not used in this client currently, Thus each process stop then start causes AAD to be pinged for authentication.  Each time you "new" a new ServiceClient, it will ping AAD for auth, as it does not share token cache between instances of the ServiceClient unless the client is Cloned from an established connection. 

Could you tell me a bit more about the pattern your using that it triggering this to happen?

**Comment by abisheksharma** [comment]
Hey Matt,
Thanks for your quick response. I noticed that the service was pinging AAD each time for auth. Do you guys have any plans on using the TokenCacheStorePath in the future?
The situation I am facing currently is that I have a customer service portal where all the CRUD functions make the call to Dynamics 365 and the call works until it doesn't and it redirects the user to log in again. I haven't researched the error code that happens after the user enters the login cred and fails. But I don't want to go that route if I don't have to. Have you guys noticed any such issues in development. The issue happens when series of calls happen in quick succession. And the issue persists for a minute or so and fixes itself. 
Let me know if you need any more information from my side. 
Regards,
Abishek

**Comment by MattB-msft** [comment]
The current plan is to provide a means for you to provide your own token caching logic,  MSAL's implementation of token management is substantially different from ADAL.net's.   MSAL's version makes it pretty much impossible to provide a shipped implementation, as we did in CrmServiceClient, aside from the in-memory feature set it has as the caching scenario's MSAL supports rely on knowledge of the hosting infrastructure and runtime. 

That said,  the in-memory system works quite well.  
Given your scenario and making some assumptions ( single portal account talking to Dataverse) , I would suggest you have a singleton instance of the dataverse serviceclient and for each thread / page operation clone a connection from the singleton to use for the life of the page operation and then dispose it.   That will continue to reuse the in-memory instance of the client.  

In our applications and services that are actively using the Dataverse and CrmServiceClients for, we use a Singleton/Clone flow to create as many connections as required. 

Alternative if your using a constructor and not a connection string,  create the client and set "useUniqueInstance" = false, which will cause it reuse the in-memory cached copy of the connection.  That will cause requests or executes to pipeline if there calls from different threads. 

and as another alterative, you can create your own token handler and pass that to the Dataverse Client and apply the caching strategy you wish from the MSAL feature set.

**Comment by abisheksharma** [comment]
Hey Matt, 
Thanks for very valuable information. Is there any way you could point me to an working example of Singleton/clone flow. I feel like that's the path I want to take. We are using .net 5 so the dependency is easy to inject and set life cycle as well. 

Regards,
Abishek

**Comment by abisheksharma** [comment]
Hey Matt,
Thanks for the suggestion. I tried using a constructor and set 'useUniqueInstance' as false and it's working without any issues.

**Comment by thenerdynerd** [comment]
Hi do you have a basic example of this?

I am currently facing an issue with regards to AADSTS50196: The server terminated an operation because it encountered a client request loop. Application error - the app is requesting too many tokens

But have not found any examples on how to mitigate this issue?

**Comment by MattB-msft** [comment]
@thenerdynerd  are you using your own token handler or using the onboard system to do it? 
and are you using ClientID/Secret|Cert or UserID PW
and are hosting a service or running a client?
