### ISSUE TITLE
An error occurred while validating input parameters: Microsoft.OData.ODataException: Does not support untyped value in non-open type. If add activity party to email.

### ISSUE THREAD

**Issue by bogusve** [microsoft/PowerPlatform-DataverseServiceClient#136]
Hi, i try email with fields from and to and i get error. Problem for activity party.
I see https://github.com/microsoft/PowerPlatform-DataverseServiceClient/issues/70
But it not working for me.
My version: 0.4.12"
```
var from = new Entity("activityparty")
  {
      ["partyid"] = new EntityReference("systemuser", userId)
  };
  var email = new Entity("email")
  {
      ["subject"] = "Test",
      ["from"] = new Entity [] { from }
  };
```

**Comment by MattB-msft** [comment]
I assume your calling Create? 
svc.create(email) ? 

Can you verify or provide the rest of the call so we can have a look, The code snippet or example will help us understand how your getting to this error as we have tests and a few other ways of checking this pattern and believe we had solved it completely.

**Comment by bogusve** [comment]
`var emailId =  await _crmRepository.CreateAsync(email);`
in my class CrmRepository:
 ```
public Task<Guid> CreateAsync(Entity entity)
        {
            return _service.CreateAsync(entity);
        }
```
Sync method _service.Create(entity); the same doesn't work.
If I do not specify the FROM fields or TO everything works, the problem is only with activity party.

**Comment by 100silver100** [comment]
Hello,

Try to add participationtypemask (from) into activityparty.

**Comment by bogusve** [comment]
https://www.youtube.com/watch?v=Pg1jYOhVAp8

`Try to add participationtypemask (from) into activityparty.` its not work :(
```
 var from = new Entity("activityparty")
            {
                ["partyid"] = new EntityReference("systemuser", fromUser.Id),
                ["participationtypemask"] = 1
            };
```

**Comment by MattB-msft** [comment]
Ok thanks folks... we are looking into it.

**Comment by MattB-msft** [comment]
This has been fixed in the next drop. 
you can bypass this right now in 2 ways.. 
1) use an entitycollection vs an entity list when creating your activity parties 
2) do not include participationtypemask in your activity party,  just set the collection of activityparties to the from/to property of the activity. 

Upcoming fix will properly tolerate the different ways that an activity party can be reflected

**Comment by bogusve** [comment]
thx very very !!!
