### ISSUE TITLE
Error updating lookup field to null if the field schema name has uppercase letters

### ISSUE THREAD

**Issue by bogusve** [microsoft/PowerPlatform-DataverseServiceClient#140]
Hello,
I have lookup field logicalName: **new_fahrerid** ShemaName: **new_FahrerId**
If i update this field end set new entityReferance it's ok.
`updatingEntity["new_fahrerid"] = new EntityReferance("contact", new Guid(XXXXXXXXXXXXX))`
But if i update this field and set null value i have error:
`updatingEntity["new_fahrerid"] = null`
An error occurred while validating input parameters: Microsoft.OData.ODataException: Does not support untyped value in non-open type.

I checked, this error occurs only in the fields where the schema name differs from the logical name and if set null value.

Please fix it in new updates. Thx.

I`m using 0.4.12 version.

**Comment by MattB-msft** [comment]
Thanks for reporting this @bogusve ,
yes.. we are still chasing a number of these 'isms' in the WebAPI.  We are talking a look.

**Comment by theepan18** [comment]
Hi, Any idea when this bug will be fixed?

**Comment by bogusve** [comment]
> Hi, Any idea when this bug will be fixed?

At the moment I just update these fields via api.

**Comment by MattB-msft** [comment]
Right now I would say call the ExecuteOrganizationRequest with the parameter UseWebAPI=false at the moment till we lock this down.
