### ISSUE TITLE
Support for Global Discovery service (now Regional ones switched off?)

### ISSUE THREAD

**Issue by Liquidream** [microsoft/PowerPlatform-DataverseServiceClient#141]
Hi,

We have production code that is still using the **Microsoft.Xrm** namespace (e.g. `Microsoft.Xrm.Tooling.Connector.CrmServiceClient.DiscoverOrganizations()`) to make connections to D365 organizations (as, for the longest time, this "newer" library has still been in "Alpha" status?).

Well, Microsoft appear to have followed through on their commitment to turn off the Regional Discovery services - so now many of our clients are reporting `FCB 'EnableRegionalDisco' is disabled` errors.

It seems this Dataverse library has built-in support for the global discovery service(?), but (as far as I can tell), I'm struggling to find a supported (read: GA, not "Alpha"/Beta) library that we can now use in order to continue making D365 connections from our .NET Framework-based application.

Or is it simply that we should not be passing region-specific Discovery Service URL's to CrmServiceClient.DiscoverOrganizations(); method, and pass something like `https://globaldisco.crm.dynamics.com/api/discovery/v2.0/Instances` instead (per [this](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/discovery-orgsdk-to-webapi) article?)

Many thanks in advance for any assistance provided.

Kind regards,

**Comment by Liquidream** [comment]
**Update:**
I just tried the ["Work with Discovery Service" sample ](https://github.com/microsoft/PowerApps-Samples/tree/master/cds/orgsvc/C%23/DiscoveryService) (which is assumed uses your DataService SDK, as it's under a CDS subfolder), but it seems that also still uses Microsoft.Xrm.Tooling libraries as it also fails with the `FCB 'EnableRegionalDisco' is disabled` error.

**Comment by MattB-msft** [comment]
@Liquidream , 
-grunt- alpha.. yes.. though we have removed the flags from the nuget drops :) 

With regard to the CrmServiceClient, if you switch your auth to OAuth you will find that things will work properly as the client will prefer Global Discovery.
The Dataverse Service Client does not have this challenge as the only auth flow it currently supports is OAuth. 

To access global discovery with the CrmServiceClient, you can use this code: 

```C#
var creds = new System.ServiceModel.Description.ClientCredentials();
creds.UserName.UserName = "<userID>";
creds.UserName.Password = "<PW>";
string appId = "51f81489-12ee-4a9e-aaae-a2591f45987d";
Uri appReplyUri = new Uri("app://58145B91-0C36-4500-8554-080854F2AC97");
Uri discoUrl = new Uri("https://globaldisco.crm.dynamics.com/api/discovery/v2.0/Instances");

var orgs = CrmServiceClient.DiscoverGlobalOrganizations(
        discoUrl, creds, null, appId, appReplyUri, "", false, string.Empty, Microsoft.IdentityModel.Clients.ActiveDirectory.PromptBehavior.Auto);
var orgCt = orgs.Count;
```

In the dataverse client,  this was simplified to this 

```C#
string uid = "<userID>";
string pw = "<PW>";
string appId = "51f81489-12ee-4a9e-aaae-a2591f45987d";
Uri appReplyUri = new Uri("app://58145B91-0C36-4500-8554-080854F2AC97");

var orgData = ServiceClient.DiscoverOnlineOrganizationsAsync(uid,pw,appId,appReplyUri,false,null).Result;
var orgCt = orgData.Count; 
```
Where commercial Global discovery is inferred, and additional helpers were added to get the global discovery services for sovereign regions. 

Insofar as the sample, we will get that fixed,, thanks for letting us know it was still out there. 

if this works for you, please go ahead and close the thread

**Comment by github-lee** [comment]
Hi,

We have a web application which connects to D365 in below method. The "DiscoveryUri" was "https://disco.crm5.dynamics.com/XRMServices/2011/Discovery.svc", and we changed it to "https://globaldisco.crm.dynamics.com/api/discovery/v2.0/" according to Microsoft document, but are hitting error saying metadata cannot be resolved. Below is a snippet of the code:

`Trace.Indent();
            LogManager.WriteLog(LogType.Info, "CrmServiceHelper_ServerConnection", "GetDiscoveryServiceProxy", "");
            Trace.Unindent();
            // Set service management for either organization service Uri or discovery service Uri.
            //DiscoveryUri = new Uri("https://globaldisco.crm.dynamics.com/XRMServices/2011/Discovery.svc");//hardcoded to test new API - not working
            DiscoveryUri = new Uri("https://globaldisco.crm.dynamics.com/api/discovery/v2.0/");//hardcoded to test new API - not working
            IServiceManagement<IDiscoveryService> serviceManagement = ServiceConfigurationFactory.CreateManagement<IDiscoveryService>(DiscoveryUri);
            _userCredentials = GetUserLogonCredentials();`

The error will say "{"Metadata contains a reference that cannot be resolved: 'https://globaldisco.crm.dynamics.com/api/discovery/v2.0/?wsdl&sdkversion=8.1'."}"

Is this totally not supported anymore or it is only due to wrong URL?
And is the code posted by MattB the only way now? If yes, it seems not easy to transform the web application from its exisiting code in CrmServiceHelper to just a few lines of code by MattB.

Many thanks in advance for any assistance provided.

**Comment by github-lee** [comment]
hi Matt,

Thanks for your reply, we are trying to follow that path, then stumbled upon "appId" and "appReplyUri" in your code above. After some research, it seems to be a guid obtained from https://portal.azure.com, but are unsure where in Azure. Is it correct that an application need to be created at Home>Azure Active Directory>App Registrations>New Registration? We tried with Tenant ID and the instance ID in D365 CE Settings>Customizations>Developer Resources, but to no avail.

**Comment by github-lee** [comment]
hi Matt,

Thanks for your reply, we are trying to follow that path, then stumbled upon "appId" and "appReplyUri" in your code above. At first, we also tried putting Tenant ID and the instance ID in D365 CE Settings>Customizations>Developer Resources, but to no avail.

After some research, it seems to be two guids obtained from https://portal.azure.com, but are unsure where in Azure. Is it correct that an application need to be created first at Home>Azure Active Directory>App Registrations>New Registration? If yes, we registered a new app and use its application id and redirect url, but the code returned error "The request body must contain the following parameter: 'client_assertion' or 'client_secret'". We then created a client secret, the code returned same error.

**Comment by MattB-msft** [comment]
We have advised strongly against using IOrganizationService  iorgService = crmSvc.OrganizationWebProxyClient since about 2017. 
We have removed access to that property in the dataverse client going forward. 

To check if you connection is good,  you use
crmSvc.isReady == true
And to get the IOrganizationService you use 

IOrganizationService iorgService = (IOrganizationService)crmSvc;

Let me know if that sorts it out for you

**Comment by MattB-msft** [comment]
Closing due to no response.
