### ISSUE TITLE
AddListMembersListRequest class is missing

### ISSUE THREAD

**Issue by davidop** [microsoft/PowerPlatform-DataverseServiceClient#142]
I'm migrating a project to make it use your new DLL, but I've found a problem

Cannot find a class named **AddListMembersListRequest**, VS is triying to install the old DLL, as you can see in the screenshot:

![image](https://user-images.githubusercontent.com/7433346/121374284-1279e380-c940-11eb-8ca1-df95ac0d1ad4.png)

What can I do? Has it been renamed? Is there another way to use this class?

Thanks for your help, have a good day!

**Comment by BetimBeja** [comment]
Do you have `Microsoft.Dynamics.Sdk.Messages` package installed?
![image](https://user-images.githubusercontent.com/11160171/121382396-da29d380-c946-11eb-9d5a-81bc53a7aff4.png)
The `AddListMembersListRequest` class should be shipped with that NuGet.

**Comment by davidop** [comment]
Thank you very much for the clarification. Problem solved. Great job
