### ISSUE TITLE
Memory leak with previous .net exceptions on the stack 

### ISSUE THREAD

**Issue by enriconatella** [microsoft/PowerPlatform-DataverseServiceClient#144]
Hello,
we're facing a memory leak issue using the latest version of the library (0.4.12).
Analyzing the memory dump, we found out that the threads have evidence of all previous .net exceptions on the stack.
In particular, the exception that is causing the issue is the following:

`(False) MSAL 4.28.1.0 MSAL.NetCore Microsoft Windows 10.0.14393 [07/06/2021 16:30:14 - ] The default token cache provided by MSAL is not designed to be performant when used in confidential client applications. Please use token cache serialization. See https://aka.ms/msal-net-cca-token-cache-serialization.`

In the dump there are thousands of this exception (220.000+).

Are you already aware of this issue? If you need more details, don't hesitate to ask.

**Comment by MattB-msft** [comment]
Yep,  We are tracking that for clean up... thanks for raising it 
will see if we can get this prioritized with some of the work around subjectname based auth.
