### ISSUE TITLE
Forcing async request execution over thread pool

### ISSUE THREAD

**Issue by svejdo1** [microsoft/PowerPlatform-DataverseServiceClient#146]
In `ServiceClient.cs` there is this line:

    internal async Task<OrganizationResponse> Command_ExecuteAsync(OrganizationRequest req, string errorStringCheck, System.Threading.CancellationToken cancellationToken, bool bypassPluginExecution = false)
    {
        return await Task.Run(() => Command_Execute(req, errorStringCheck, bypassPluginExecution), cancellationToken);
    }

This is forcing execution of the job over thread pool - that is very expensive - if the goal was not to cause a deadlock over UI applications there are cheaper ways how to avoid it - ref: https://stackoverflow.com/a/28307965/2440262

For our scenarios (backend/server application) execution over thread pool is increasing CPU utilization a lot.

**Comment by MattB-msft** [comment]
Hi @svejdo1 Sorry about that, 
This is a temp situation until we can ship the proper implementation . 
We are working on shipping a full Async Client for the Older API leg.  its held up behind some changes we are making on the dataverse server right now. 

If it gets held up too much longer we will look at optimizing this for better behavior.

**Comment by MattB-msft** [comment]
@svejdo1 we have been perf testing our updated version and will be shipping soon.  it will be stamped release number 0.5.x as it includes a 'minor' breaking change, in addition to a large number of updated and new features.
