### ISSUE TITLE
Two different UserAgents are logged

### ISSUE THREAD

**Issue by pareszka** [microsoft/PowerPlatform-DataverseServiceClient#147]
I can see in logs, that DataverseServiceClient is using two "identities" in UserAgent logs: DataverseSvcClient and CdsSvcClient.
DataverseSvcClient  is coming from ConnectionService, while CdsSvcClient is coming from DataverseTelemetryBehaviors, line 50.
I guess this one place was missed during the rename. Can this be aligned?

**Comment by MattB-msft** [comment]
very astute :) 
That intentional, as its allowing us to segregate traffic from one of our API endpoints vs the other until we get a bit more telemetry on our side.

That is in place and rolling out now.
