### ISSUE TITLE
ServiceClient update does an upsert?

### ISSUE THREAD

**Issue by benoitwouter** [microsoft/PowerPlatform-DataverseServiceClient#149]
When using the ServiceClient update method using a record ID that does not exist in the system, a new record is being created.
Before, this would throw an error.

Executing the following lines of codes results in a new account record.

`ServiceClient service = new ServiceClient(connectionString);
Entity updater = new Entity("account", Guid.NewGuid());
updater["name"] = "Updated name";
service.Update(updater);`

Is this expected behavior now? Or will this be treated as a bug and fix can be expected in a future release?

**Comment by MattB-msft** [comment]
Yes, that is expected based on the current design of the WebAPI,

**Comment by benoitwouter** [comment]
If I execute an update using the WebAPI I get this error, which I was expecting

![image](https://user-images.githubusercontent.com/87990787/127211575-9281421e-d7d6-4c1f-8de6-66d2d4f4d4e3.png)

I can also find the following information
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/perform-conditional-operations-using-web-api#prevent-create-in-upsert

So, is there any way to overwrite this behavior when using the ServiceClient?

**Comment by MattB-msft** [comment]
Yes, this is a byproduct of the way the OrganizationService to WebAPI back to Organziation Service translation is happening. 
The decision of the API team was to allow it to work this way,  I will discuss it with them in the next meeting as it is a deviation in behavior of the OrganizationService API.

**Comment by MattB-msft** [comment]
We decided to put the Organization Service Behavior back in place. 
should be fixed shortly.
