### ISSUE TITLE
tokenProviderFunction called 4 times during ServiceClient initialization

### ISSUE THREAD

**Issue by ryanspain** [microsoft/PowerPlatform-DataverseServiceClient#161]
I am using the `Microsoft.Identity.Client` NuGet package to create a token provider function to initialize a new `ServiceClient` via the below constuctor.

```csharp
ServiceClient.ServiceClient(Uri instanceUrl, Func<string, Task<string>> tokenProviderFunction, ...)
```

On initialization of the `ServiceClient`, before a request is even made, the `tokenProviderFunction` is invoked a total of 4 times.

**Here is the `ServiceClient` initialization code:**

```csharp
static void ExecuteWhoAmIRequest(){

    var environmentUri = new Uri("https://XXX.crmX.dynamics.com");
    var tokenProvider = (Func<string,Task<string>>)GetBearerAccessToken;

    var serviceClient = new ServiceClient(
        instanceUrl: environmentUri,
        tokenProviderFunction: tokenProvider
    );

    var whoAmIResponse = serviceClient.Execute(new WhoAmIRequest());
}
```

> Note: The `tokenProviderFunction` is invoked 4 times before the `WhoAmIRequest` is even hit.

**And here is the `tokenProviderFunction` implementation:**

```csharp
static async Task<string> GetBearerAccessToken(string instanceUri){
    return "eyJ0eXAiOiJK..."
}
```
> Note: I've omitted the actual use of the MSAL.NET package as upon removing it, the same issue persisted whereby `GetBearerAccessToken` was called 4 times despite a valid bearer token being returned each time.

**Additional information:**

- This is a console application created via `dotnet new console`
- The application has a `TargetFramework` of `net5.0`
- The following NuGet packages are being used:
  - `<PackageReference Include="Microsoft.Identity.Client" Version="4.36.0" />`
  - `<PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" Version="0.4.21" />`

**Comment by MattB-msft** [comment]
Yes,  this is by design, 
Each time the client needs to use the token for something, or its accessed in a way that could contact Dataverse,  it requests it of the token provider.   
During initialization, several calls are made to support authentication, version detection and endpoints,  Client identification, and accessing user identification.   Collectively these calls setup any version specific handling of subsequent calls, and populate properties for the client.

When you take on control of providing the access token, its the functions responsibility to manage caching,  either via relying on MSAL's built in caching or extensions too it, or crafting your own caching mechanic.

**Comment by ryanspain** [comment]
Thanks for that confirmation Matt. It makes perfect sense.

I'd suggest that the description of the `tokenProviderFunction` parameter of this constructor be updated to make this a little clearer. Maybe even just to include reference to the usage of token caching strategies.

**For anybody that was curious or stumbles across this in the future...**
My problem was that the implementation for my `tokenProviderFunction` didn't allow for cached token to be read because I was initializing a new `IPublicClientApplication` for each invocation of `GetBearerAccessTokenAsync` (my `tokenProviderFunction`). See below.

```csharp
public async Task<string> GetBearerAccessTokenAsync(string instanceUri)
{
    IPublicClientApplication app = PublicClientApplicationBuilder.Create("06985e8a-XXXX-XXXX-XXXX-0077aaecc765")
        .WithTenantId("1fc4959a-XXXX-XXXX-XXXX-152765d1d5c9")
        .Build();
    
    ...
    
    try
    {
        result = await app
            .AcquireTokenSilent(scopes, accounts.FirstOrDefault())
            .ExecuteAsync();
    }
    catch (MsalUiRequiredException)
    {
        result = await app
            .AcquireTokenInteractive(scopes)
            .ExecuteAsync();
    }

    return result.AccessToken;
}
```

It was becuause of this oversight that I got 4 annoying interactive login popups instead of the expected 1. After hoisting the `IPublicClientApplication` instance out of `GetBearerAccessTokenAsync`, everything worked as expected with only a single interactive login popup, followed by 3 invocations that read from the token cache.
