### ISSUE TITLE
Updating SalesOrderDetail Null Reference Exception

### ISSUE THREAD

**Issue by Rtalos** [microsoft/PowerPlatform-DataverseServiceClient#163]
Hello,

We create an SalesOrder, save it and then try to update the PricePerUnit on the SalesOrderDetail before fulfilling the SalesOrder. The SalesOrderDetail is auto created in Dynamics because of some business logic. I can see it is the correct SalesOrderDetail entity that is being returned. This is the first time we develop this code and I have no idea if it was working in earlier versions.

Normally I would take this up with our Dynamics team to investigate errors but since it seems that the errors are thrown within the ServiceClient package, specifically Key Null Exception from GetEntityMetadata, it leads me to believe that perhaps there is some bug? I might be wrong, not entirely sure since I had issues while trying to debug with Just My Code off. Perhaps we are doing something wrong?

This is the code being run:

![image](https://user-images.githubusercontent.com/19684631/133458352-4067504b-92fd-4c5f-b2cc-d0fb1d74d137.png)

This is the error and internal error I get:

![image](https://user-images.githubusercontent.com/19684631/133459271-18be297b-e671-454a-b417-d35f5176252f.png)
![image](https://user-images.githubusercontent.com/19684631/133459285-5a94affb-b15b-49fe-ac7a-b337cf8d09cb.png)

Version:
![image](https://user-images.githubusercontent.com/19684631/133461336-c179bee0-4c92-47b8-8534-a389b5c6d8ab.png)

**Comment by MattB-msft** [comment]
@Rtalos 
On first glance, I think your correct here, this looks like an bug in our client, 
What is the error message it throws, in addition to the stack trace?

We will have a look at it tomorrow and get back to you

**Comment by MattB-msft** [comment]
Confirmed bug.  We are looking into this now.

**Comment by Rtalos** [comment]
> Confirmed bug. We are looking into this now.

Thank you!

I also want to take this opportunity to thank you and your team for the work you put into this. This package is such a great addition and it opens up new amazing opportunities. So, thank you! 🥇

**Comment by MattB-msft** [comment]
@Rtalos we have identified the issue and fixed it in the next build.  
The issue is rooted out of the specific behavior of that entity in our API ( deviation between underlying API endpoints ).  that entity is a "child entity type" which inherits much of its behavior from the parent.
