### ISSUE TITLE
Issue with Microsoft.cds.coreassemblies.internal

### ISSUE THREAD

**Issue by bluebookfairy** [microsoft/PowerPlatform-DataverseServiceClient#164]
Hello, solution can't be built. VS raises errors and it could not find "Microsoft.cds.coreassemblies.internal", please see the screen print.  I've already installed these three nuget packages:

Microsoft.PowerPlatform.Dataverse.Client
Microsoft.PowerPlatform.Dataverse.Client.Dynamics
Microsoft.Dynamics.Sdk.Messages

![error](https://user-images.githubusercontent.com/89654132/133908377-b51861cf-1016-41f2-a347-643328d811b1.png)

**Comment by BetimBeja** [comment]
It is written in the readme:

> The Dataverse ServiceClient cannot be built outside of Microsoft This is due to a set of dependencies on nuget packages that are internally available only. At some point in the future, we will expose the supporting nuget packages when we have updated our server infrastructure to support plugin development on .net core.

**Comment by MattB-msft** [comment]
@bluebookfairy,  as @BetimBeja points out... we do state that this is the case in the readme upfront.   We hope to be able to do this in the future.
