### ISSUE TITLE
ServiceClient connexion dosen't work in webapi .net framework 4.6.2

### ISSUE THREAD

**Issue by fatimabenradi** [microsoft/PowerPlatform-DataverseServiceClient#178]
I m working on a  project that implemante dataverse.client in webapi .net framework 4.6.2.
I used 2 types of connexion and both dosen't respond and i didn't have a time-out, but if I use a .netcore or windowsapplication(consol or library .net framework) it works fine.
Is Dataverse.Client not compatible with  web .net framework  and i must use just  Microsoft.Xrm.Tooling in this case?

new ServiceClient("AuthType=ClientSecret;Url=https://urlclient.crm3.dynamics.com;ClientId=guid;ClientSecret=secretcode")

new ServiceClient(certificate: certificat, certificateStoreName: StoreName.Root, certificateThumbPrint: CertificateThumbPrint, instanceUrl: new Uri(Url), useUniqueInstance: false, orgDetail: null, clientId: ClientId, redirectUri: new Uri(RedirectUri));

**Comment by MattB-msft** [comment]
This should work fine,  could you describe your situation a bit? 
what are you trying to host this in?

**Comment by fatimabenradi** [comment]
i create a simple web application to make a webapi who call a dataverse.client for searching entites, in below two methode of connexion that not responding  
just in this type of project doesn't work, in .net core and library works fine.

![image](https://user-images.githubusercontent.com/92134104/137412612-a261de97-4cd2-45c1-8153-fd7fd476e7ee.png)

![image](https://user-images.githubusercontent.com/92134104/137412289-2e29ea0f-274e-46cf-aa3b-e869a0a32ec4.png)

**Comment by fatimabenradi** [comment]
i pulled down the 0.5.7 but service client still doesn't respond

**Comment by MattB-msft** [comment]
Ok @fatimabenradi  the issue your running into is described here: https://docs.microsoft.com/en-us/aspnet/mvc/overview/performance/using-asynchronous-methods-in-aspnet-mvc-4

Creating a Dataverse ServiceClient is an async operation,  Asp.net in full framework has some challenges there b/c its setup to run operations with the asumption that all things are sync. 

thus the default code : 

```
        public ActionResult Index()
        {
                string cliId = "<appid>";
                string sKey = "<secret>";
                string cdsHost = "<url>";
                ServiceClient cli = new ServiceClient(new Uri(cdsHost), cliId, sKey, true);
                if (cli.IsReady)
                {
                }
            return View();
        }
```

will appear to hang. 

you can get around this by using this process instead : 

```
        public async Task<ActionResult> Index()
        {
            await System.Threading.Tasks.Task.Run(() =>
            {
                string cliId = "<appId>";
                string sKey = "<Secret>";
                string cdsHost = "<URL>";

                ServiceClient cli = new ServiceClient(new Uri(cdsHost), cliId, sKey, true);
                if (cli.IsReady)
                {

                }
            });
            return View();
        }

```
the better option here is to use DI and create an instance of the connection at startup to use and keep that setup as a singleton, or a session property 

There are a few examples of how this is done on the web ( https://colinvermander.wordpress.com/2020/03/26/cdsserviceclient-with-asp-net-core/) is from one of our MVP's as a sample,  just exchange CdsServiceClient for ServiceClient ( we changed the name a few months back). 

We are looking into providing an official sample of DI based usage and perhaps prebuilt module for Adding a ServiceClient to an ASP.net site in the future.. its stacked up behind a number of other priority items for us at the moment

**Comment by fatimabenradi** [comment]
thanks, it works
