### ISSUE TITLE
ServiceClient is not working in ASP.NET Framework MVC project 

### ISSUE THREAD

**Issue by Cobra86** [microsoft/PowerPlatform-DataverseServiceClient#181]
Hi,

I'm trying to connect to dynamic 365 from asp.net mvc project but its just keep loading/connecting and it didn't crash or throw exception.
I wrapped my code with try and catch and nothing happen just loading/connecting.
It's showing me error message when I tried to use invalid url and credentials
Also, I created new project and it's still the same issue.

To reproduce the issue:
ASP.NET Framework MVC project.
.NET framework 4.7.2
Visual Studio 2019.10.4
Microsoft.PowerPlatform.Dataverse.Client Version 0.5.5
Windows 10

This is the sample code. 
```
String url = "";
String clientId = "";
String clientSecret = "";

String connectionString = $@"RequireNewInstance=true; Url ={url}; AuthType=ClientSecret; ClientId={clientId}; ClientSecret={clientSecret}";
var serviceClient = new Microsoft.PowerPlatform.Dataverse.Client.ServiceClient(connectionString);
```
same code is working fine in ASP.NET Core MVC .NET 5 and .NET Framework 4.7.2 console app.

**Comment by Cobra86** [comment]
Thank you @MattB-msft 
It's working in the controller class but it didn't work in the referenced c# class library, it's keep hanging. 
I had to change everything to sync and use the code below. 
is this a good approach?
```
var _serviceClient = null;
Task t =  System.Threading.Tasks.Task.Run(() =>
            {
                string cliId = "<appId>";
                string sKey = "<Secret>";
                string cdsHost = "<URL>";

                var serviceClient = new ServiceClient(new Uri(cdsHost), cliId, sKey, true);
                if (serviceClient.IsReady)
                {
                  _serviceClient = serviceClient;
                }
            });
   t.Wait();

return _serviceClient;
```

**Comment by dblohowiak** [comment]
FYI - the same thing happens to me in a Blazor application with .NET 5.0. The workaround in that comment also fixes it.
