### ISSUE TITLE
System.Text.Json 5.0.2 assembly in project dependencies in version 0.5.10 - Impacting Azure Functions v3 + Microsoft.Net.Sdk.Functions .12,.13 Nuget packages.

### ISSUE THREAD

**Issue by drivardxrm** [microsoft/PowerPlatform-DataverseServiceClient#192]
Hi,

it seems that there is a dependency on a .NET 5 package in the latest version (0.5.10)

In an Azure Function project (.NET Core 3.1) I receive this error at runtime whenever I make a call using the new package. 

One or more errors occurred. (Could not load file or assembly 'System.Text.Encodings.Web, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.)

I have no such issues with earlier version (0.5.7)

Might be because of the System.Text.Json that seems to have changed from 4.72 to 5.0.2
![image](https://user-images.githubusercontent.com/38399134/138632606-f96a3e1b-671d-41f2-a58b-b206b82c2810.png)

**Comment by s-bauer** [comment]
Any update on this topic?

**Comment by MattB-msft** [comment]
Not at this time.  Its a fairly complicated change ( going backward on a dependency ) in the server platform. 
How we can do this is still being worked though. 

In the mean time.. the guidance we provided above for functions is what you should use for now.

**Comment by MattB-msft** [comment]
@drivardxrm FYI, I updated the title of this item to help other searchers find the issue.

**Comment by aditmer** [comment]
Hello, I can confirm that upgrading to .NET 6 and Microsoft.NET.Sdk.Functions Version 4.1.0 resolved this issue for me.  I hope it helps someone else.

**Comment by MattB-msft** [comment]
Moving this to Discussions / Q/A area at this point... 0.6 + is shipping with System.Text.Json 6.0 as a dependency.
