### ISSUE TITLE
Project Task update does not happen as expected.

### ISSUE THREAD

**Issue by GayaniSU** [microsoft/PowerPlatform-DataverseServiceClient#197]
I'm using Microsoft.PowerPlatform.Dataverse.Client 0.5.7 (updated to 0.5.10 recently)

I'm trying to update a task using msdyn_PssUpdateV1 operationset.
I'm setting up the task fields as below:
task["msdyn_progress"] = 0.50m;
task["msdyn_duration"] = 0.0;

When I try to update the msdyn_progress to 0.0m or 1.0m it works without any issue, but if the value is between 0 and 1, it doesn't get updated. The API doesn't throw any error as well.
Also when I'm creating a task, I can set the number of days to 0, but when I update the task, I cannot change the number of days to 0.

Could you please assist me resolving the above issues?

**Comment by MattB-msft** [comment]
This has to do with the way in which Project's Schedule API's work @GayaniSU, they push changes to the project services and then, in an async manner, update the data back into dataverse.

You would need to reach out to support, or contact the project team via the feedback link on the documentation page to get the answer for your question.

**Comment by GayaniSU** [comment]
Thank you @MattB-msft. Does it mean that those fields are not allowed to update via Project's Schedule API's?

**Comment by MattB-msft** [comment]
The API owner has control over how the API itself works,  that's why im directing you to the Project' teams' doc's site to ask the question there.
