### ISSUE TITLE
Microsoft.Cds.Sdk.dll changed to Microsoft.Xrm.Sdk.dll

### ISSUE THREAD

**Issue by miseeger** [microsoft/PowerPlatform-DataverseServiceClient#198]
Was this a planned change? 
![grafik](https://user-images.githubusercontent.com/1128963/139558775-5e42a44d-9688-42ec-96fe-70d85c2a9817.png)
I just wonder if this could cause some namespace problems with `Microsoft.Xrm.Sdk` when upgrading from 0.5.7 to 0.5.10?

**Comment by MattB-msft** [comment]
Intentional,  and no there will be no namespace issues

**Comment by miseeger** [comment]
Thank you very much for your quick reply and for clarifying this.
