### ISSUE TITLE
IFD

### ISSUE THREAD

**Issue by ONYXDave** [microsoft/PowerPlatform-DataverseServiceClient#208]
Need to use for on premise with either AD or IFD using username and password without oAuth.

**Comment by BetimBeja** [comment]
please take a look here -> https://github.com/Data8/DataverseClient

**Comment by ONYXDave** [comment]
Thanks but this doesn't support .Net 6 from what I can tell.  Do you know if there is something similar for .Net 5 or 6?

**Comment by MarkMpn** [comment]
Thanks both, there's now an issue for this at https://github.com/Data8/DataverseClient/issues/1. The package does work in both .NET 5 and 6.

**Comment by MattB-msft** [comment]
Im going to go ahead and close this issue on our side..  We understand the ask for support of AD and we are seeking to provide support for it in the future as part of this lib. 

We do not yet have an ETA on it.
