### ISSUE TITLE
Certain locales causes exceptions when updating datetimes

### ISSUE THREAD

**Issue by Donsig** [microsoft/PowerPlatform-DataverseServiceClient#216]
Hi,

It seems there's an error when updating datetimes, if the client is run on a windows machine using a locale that uses dots instead of colons to separate time components.

Specifically I got this error, while I used "English (Denmark)", which is a locale that writes time in the "HH.mm.ss" format, instead of the classic "hh:mm:ss", when updating any dynamics DateTimes.

`Exception thrown: 'Microsoft.PowerPlatform.Dataverse.Client.Utils.DataverseOperationException' in System.Private.CoreLib.dll ("An error occurred while validating input parameters: Microsoft.OData.ODataException: Cannot convert the literal '2021-12-14T15.04.16.134Z' to the expected type 'Edm.DateTimeOffset'. ---> System.FormatException: The string '2021-12-14T15.04:00.16.134Z' is not a valid AllXsd value.")`

(Notice the extra ":00" in the final datetime string)

Switching to English (Europe) fixed all issues in this regard.

**Windows settings before:**
![image](https://user-images.githubusercontent.com/2880730/146032054-b0b4ad42-f6b4-4a2f-8b84-fddd4ae88cea.png)

**Windows settings after:**
![image](https://user-images.githubusercontent.com/2880730/146032086-af164a29-ccf0-4f31-8a41-6caaf13700e3.png)

**Comment by MattB-msft** [comment]
Thanks for your feedback here, there are several issues we are chasing with the translation and formatting of date times currently. 

To bypass the issue while we work on this, you can set the property "UseWebAPI=false" on the ServieClient and that will avoid this issue.

**Comment by maskati** [comment]
I have found another workaround is to use `DateTimeOffset` instead of `DateTime`. Technically this is failing because the client is sending time as a local culture string and Dataverse [AddSecondsPaddingIfMissing](https://github.com/OData/odata.net/blob/145252226e60b4c9735f1c643fe3e01af039eab0/src/PlatformHelper.cs#L361) is expecting an ISO 8601 date string by checking for a colon, which results in actually corrupting the date string.

**Comment by FarmerenHE** [comment]
It looks like a possible cause for this exception is that the English(Danish) version of the time uses "." instead of ":" to seperate hours, minutes and seconds.

This should be : as that is the correct Danish format for time.

**Comment by MattB-msft** [comment]
We believe we have found this and fixed it.
