### ISSUE TITLE
Download Image Field

### ISSUE THREAD

**Issue by andreatosato** [microsoft/PowerPlatform-DataverseServiceClient#217]
Hi there, 
I am trying to download the "full size" image from Dataverse.
To date I can only download the low resolution image.

I use "OrganizationServiceContext" to do a Field Select with linq.
Is there a way to download the high resolution image as well?

The documentation is clear, only on the rest API.
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/image-attributes#retrieve-image-data

How can I, via the SDK, make this call? 
GET /api/data/v9.1/<entity-type(id)>/<image-attribute-name>/$value?size=full

Thanks

**Comment by MattB-msft** [comment]
The docs you linked have the SDK Call references as well. Image files are treated as "Files"
to download the files you would use the InitializeFileBlocksDownloadRequest and then batch though DownloadBlockRequest for the full file.  What is missing is the sample pattern for how to do it ( which exists :) ) as many of our internal apps use that. 
I would suggest you hit the feedback link at the bottom of the doc's page and ask for the SDK Client sample there, it will get done more quickly by your direct feedback on the page that needs to reference it. 

That said, 
You can, from the dataverse client, make the webAPI call if you want to allow the http client to manage the streaming ( using executewebrequest), however if your working directly with the SDK, you can also manage the process fully on your own.

Here is the actual sample that was written to demonstrate this, note that this sample encompasses the various types of file download that can occur for activities, notes and general-purpose files.  Thus, the initiation leg could be simplified substantially for your use case.  Also, this sample writes to a file on disk, you could easily modify it to return the byte array you need or form the Image type in the response. 

**Note:** 
in this sample, its assumed the dataverse service client was previously constructed and the variable containing it is called "**cli**"

samples:

```csharp
public static void Download(Entity e, string downloadLocation, string fileAttributeName = null)
{
    // Initialize download
    InitializeFileDownload(e, fileAttributeName, out string downloadToken, out long fileSizeDownload, out string downloadFileName);

    // Download
    DownloadFile(e, downloadToken, fileSizeDownload, downloadLocation, downloadFileName);
}

private static void InitializeFileDownload(Entity e, string fileAttributeName, out string token, out long fileSize, out string downloadFileName)
{
	string requestName = null;
	OrganizationRequest initializeDownloadRequest = null;

	if (e.Attributes.Contains("activitymimeattachmentid"))
	{
		requestName = "InitializeAttachmentBlocksDownload";
		initializeDownloadRequest = new InitializeAttachmentBlocksDownloadRequest
		{
			Target = e.ToEntityReference()
		};
	}
	else if (e.Attributes.Contains("annotationid"))
	{
		requestName = "InitializeAnnotationBlocksDownload";
		initializeDownloadRequest = new InitializeAnnotationBlocksDownloadRequest
		{
			Target = e.ToEntityReference()
		};
	}
	else
	{
		requestName = "InitializeFileBlocksDownload";
		initializeDownloadRequest = new InitializeFileBlocksDownloadRequest
		{
			Target = e.ToEntityReference(),
			FileAttributeName = fileAttributeName
		};
	}

	Console.WriteLine("Calling {0} ", requestName);

	var resp3 = cli.Execute(initializeDownloadRequest);

	token = (string)resp3.Results["FileContinuationToken"];

	Console.WriteLine("Download token: " + token);

	if (string.Equals(requestName, "InitializeFileBlocksDownload"))
	{
		fileSize = (long)resp3.Results["FileSizeInBytes"];
	}
	else
	{
		fileSize = (int)resp3.Results["FileSizeInBytes"];
	}
	downloadFileName = (string)resp3.Results["FileName"];
}

private static void DownloadFile(Entity e, string downloadToken, long fileSizeDownload, string downloadLocation, string downloadFileName)
{
	var requestName = "DownloadBlock";

	long offset = 0;
	long chunkSizeDownload = 4 * 1024 * 1024; // 4 MB
    Console.WriteLine($"File download size: {fileSizeDownload} Bytes. Chunk size: {chunkSizeDownload} MB", ConsoleColor.Cyan);
	int chunksCountDownload = (int)(fileSizeDownload / (float)chunkSizeDownload) + 1;
	int chunkNumberDownload = 0;

	using (FileStream outputFile = new FileStream(downloadLocation + "//" + downloadFileName, FileMode.OpenOrCreate, FileAccess.Write))
	{
		Console.WriteLine("Calling {0} with chunks for: {1}", requestName, downloadFileName);
		List<Task> downloadTasks = new List<Task>();
		int counter = 0;
		byte[] emptyBytes = new byte[fileSizeDownload];
		while (fileSizeDownload > 0)
		{
			chunkNumberDownload++;
			Console.WriteLine("Downloading chunk {0}/{1} from file {2}", chunkNumberDownload, chunksCountDownload, downloadFileName);
			if (fileSizeDownload < chunkSizeDownload)
			{
				chunkSizeDownload = (int)fileSizeDownload;
			}

			var downloadRequest = new DownloadBlockRequest
			{
				FileContinuationToken = downloadToken,
				Offset = offset,
				BlockLength = chunkSizeDownload
			};


			downloadTasks.Add(Task.Factory.StartNew((object data) =>
			{
				var data1 = (dynamic)data;
				var c = Convert.ToInt32(data1.Item2);
				var fileDataOffset = Convert.ToInt32(data1.Item1);

				var response3 = cli.Execute(downloadRequest);

				var result = (byte[])response3.Results["Data"];

                Console.WriteLine($"Counter:{c}; Offset: {fileDataOffset}; Length: {result.Length}", ConsoleColor.Cyan);
				Buffer.BlockCopy(result, 0, emptyBytes, fileDataOffset, result.Length);
			}, new Tuple<long, int>(offset, counter)));

			offset += chunkSizeDownload;
			fileSizeDownload -= chunkSizeDownload;
			counter++;
		}

		Task.Run(async () =>
		{
			await Task.WhenAll(downloadTasks.ToArray()).ConfigureAwait(false);
		}).GetAwaiter().GetResult();

		outputFile.Write(emptyBytes, 0, emptyBytes.Length);
		outputFile.Flush();

		Console.WriteLine("Download complete");
	}
}
```

To invoke it for an image file, you would do this:
```csharp
Entity ent = new Entity("new_somerecordwithimage");
ent.Id = Guid.Parse("RecordGUID");
Download(ent, fileAttributeName: "ImageAttributeName", downloadLocation: "FileNameAndLocation");
```

Let me know if what it is doing does not make sense.

**Comment by andreatosato** [comment]
I have this field definitions, (image field, not File Field)
```cs
        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ant_planimetryimage")]
        public byte[] ant_PlanimetryImage
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<byte[]>("ant_planimetryimage");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.OnPropertyChanging("ant_PlanimetryImage");
                this.SetAttributeValue("ant_planimetryimage", value);
                this.OnPropertyChanged("ant_PlanimetryImage");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ant_planimetryimage_timestamp")]
        public System.Nullable<long> ant_PlanimetryImage_Timestamp
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("ant_planimetryimage_timestamp");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ant_planimetryimage_url")]
        public string ant_PlanimetryImage_URL
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<string>("ant_planimetryimage_url");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ant_planimetryimageid")]
        public System.Nullable<System.Guid> ant_PlanimetryImageId
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("ant_planimetryimageid");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ant_startvaliditydate")]
        public System.Nullable<System.DateTime> ant_StartValidityDate
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("ant_startvaliditydate");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.OnPropertyChanging("ant_StartValidityDate");
                this.SetAttributeValue("ant_startvaliditydate", value);
                this.OnPropertyChanged("ant_StartValidityDate");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr129_imagebase64")]
        public string cr129_ImageBase64
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<string>("cr129_imagebase64");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.OnPropertyChanging("cr129_ImageBase64");
                this.SetAttributeValue("cr129_imagebase64", value);
                this.OnPropertyChanged("cr129_ImageBase64");
            }
        }
```


Exception details: 
ErrorCode: 0x80090007
Message: **Invalid File Attribute Name**: [cr129_imagebase64].
TimeStamp: 2021-12-15T16:41:38.0761107Z

**Comment by andreatosato** [comment]
This is my attributes
![image](https://user-images.githubusercontent.com/24985956/146230045-5a40bf38-edc6-4aaf-bee8-dd384faee0db.png)

**Comment by MattB-msft** [comment]
The code should be falling though to this case:
```csharp
else
	{
		requestName = "InitializeFileBlocksDownload";
		initializeDownloadRequest = new InitializeFileBlocksDownloadRequest
		{
			Target = e.ToEntityReference(),
			FileAttributeName = fileAttributeName
		};
	}
```
where the FileAttributeName is the name of the Image Attribute. ( ant_planimetryimage ) based on my read... though a few of them will be virtual attributes.   You want the one that is tagged as "Image" in the meteadata.

**Comment by andreatosato** [comment]
Yes, it's right.
I want to download full size image



Microsoft.PowerPlatform.Dataverse.Client.ServiceClient: Error: ************ FaultException`1 - InitializeFileBlocksDownload : Execute (InitializeFileBlocksDownload) request to Dataverse from IOrganizationService |=> No imagedescriptor records found for image attribute :ant_planimetryimage of ant_planimetria record with id 035b264a-b510-ec11-b6e6-000d3a2b7e5a
Source: System.Private.ServiceModel
Method: HandleReply
DateUTC: 12/15/2021
TimeUTC: 5:34:36 PM
Error: Message: No imagedescriptor records found for image attribute :ant_planimetryimage of ant_planimetria record with id 035b264a-b510-ec11-b6e6-000d3a2b7e5a
ErrorCode: -2147220969
ActivityId: d20a4732-ce9c-493c-863f-9f8c8e3d6a48
Trace: 
Error Details	:
ApiExceptionSourceKey	: Plugin/Microsoft.Crm.ObjectModel.FileStoreService
ApiSourceActivityKey	: 
ApiExceptionOwnerKey	: OwnershipNotFoundInExceptionOwnerSettings
ApiOriginalExceptionKey	: Microsoft.Crm.BusinessEntities.CrmObjectNotFoundException: No imagedescriptor records found for image attribute :ant_planimetryimage of ant_planimetria record with id 035b264a-b510-ec11-b6e6-000d3a2b7e5a ---> Microsoft.Crm.BusinessEntities.CrmObjectNotFoundException: No imagedescriptor records found for image attribute :ant_planimetryimage of ant_planimetria record with id 035b264a-b510-ec11-b6e6-000d3a2b7e5a
   at Microsoft.Crm.BusinessEntities.ImageDataTypeHelper.RetrieveFileAttachmentForImageAttribute(String entityName, Guid entityKeyValue, String imageAttributeLogicalName, ColumnSet columnSet, ExecutionContext context, IImageDataTypeHelperWrapper imageWrapper, IBusinessProcessObject bpo)
   at Microsoft.Crm.ObjectModel.ImageAttachmentServiceProvider.RetrieveFileAttachment(EntityMetadata targetEntityMetadata, Guid entityKeyValue, String fileAttributeName, ExecutionContext context)
   at Microsoft.Crm.ObjectModel.FileAttachmentServiceProvider.<>c__DisplayClass13_0.<InitializeFileBlocksDownload>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)
   at Microsoft.Crm.ObjectModel.FileStoreService.InitializeFileBlocksDownload(EntityReference target, String fileAttributeName, Int64& fileSizeInBytes, String& fileName, ExecutionContext context)
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Extensibility.VersionedPluginProxyStepBase.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.PipelineInstrumentationHelper.Execute(Boolean instrumentationEnabled, String stopwatchName, ExecuteWithInstrumentation action, PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.Pipeline.<>c__DisplayClass3_0.<RunStep>b__0()
ApiStepKey	: 8ab9402f-e5c9-4ad8-8728-9f5f54c8eae6
ApiDepthKey	: 1
ApiActivityIdKey	: d20a4732-ce9c-493c-863f-9f8c8e3d6a48
ApiPluginSolutionNameKey	: System
ApiStepSolutionNameKey	: System
ApiExceptionCategory	: ClientError
ApiExceptionMessageName	: ObjectDoesNotExist
ApiExceptionHttpStatusCode	: 404

HelpLink Url: Not Provided
Stack Trace: at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
   at generatedProxy_1.Execute(OrganizationRequest )
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClientAsync.<>c__DisplayClass52_0.<ExecuteCore>b__0()
   at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.ExecuteAction[TResult](Func`1 action)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClientAsync.ExecuteCore(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClientAsync.Execute(OrganizationRequest request)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.Command_Execute(OrganizationRequest req, String errorStringCheck, Boolean bypassPluginExecution)
======================================================================================================================
Inner Exception Level 1	: 
==OrganizationServiceFault Info=======================================================================================
Error: Message: No imagedescriptor records found for image attribute :ant_planimetryimage of ant_planimetria record with id 035b264a-b510-ec11-b6e6-000d3a2b7e5a
ErrorCode: -2147220969
ActivityId: d20a4732-ce9c-493c-863f-9f8c8e3d6a48
Trace: 
Time: 12/15/2021 5:34:37 PM
ErrorCode: -2147220969
DateUTC: 12/15/2021
TimeUTC: 5:34:36 PM
HelpLink Url: Not Provided
Trace: Not Provided
======================================================================================================================


System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: No imagedescriptor records found for image attribute :ant_planimetryimage of ant_planimetria record with id 035b264a-b510-ec11-b6e6-000d3a2b7e5a (Fault Detail is equal to Exception details: 
ErrorCode: 0x80040217
Message: No imagedescriptor records found for image attribute :ant_planimetryimage of ant_planimetria record with id 035b264a-b510-ec11-b6e6-000d3a2b7e5a
TimeStamp: 2021-12-15T17:34:37.9997757Z
--
Exception details: 
ErrorCode: 0x80040217
Message: No imagedescriptor records found for image attribute :ant_planimetryimage of ant_planimetria record with id 035b264a-b510-ec11-b6e6-000d3a2b7e5a
TimeStamp: 2021-12-15T17:34:37.9997757Z
--
).
Microsoft.PowerPlatform.Dataverse.Client.ServiceClient: Error: [TerminalFailure] Failed to Execute Command - InitializeFileBlocksDownload : RequestID=56150ae3-a3fa-4f4d-a8d9-3ff8068afa47 : Execute (InitializeFileBlocksDownload) request to Dataverse from IOrganizationService duration=00:00:00.2399024 ExceptionMessage = No imagedescriptor records found for image attribute :ant_planimetryimage of ant_planimetria record with id 035b264a-b510-ec11-b6e6-000d3a2b7e5a


System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: No imagedescriptor records found for image attribute :ant_planimetryimage of ant_planimetria record with id 035b264a-b510-ec11-b6e6-000d3a2b7e5a (Fault Detail is equal to Exception details: 
ErrorCode: 0x80040217
Message: No imagedescriptor records found for image attribute :ant_planimetryimage of ant_planimetria record with id 035b264a-b510-ec11-b6e6-000d3a2b7e5a
TimeStamp: 2021-12-15T17:34:37.9997757Z
--
Exception details: 
ErrorCode: 0x80040217
Message: No imagedescriptor records found for image attribute :ant_planimetryimage of ant_planimetria record with id 035b264a-b510-ec11-b6e6-000d3a2b7e5a
TimeStamp: 2021-12-15T17:34:37.9997757Z
--
).
Exception thrown: 'System.ServiceModel.FaultException`1' in Microsoft.Xrm.Sdk.dll
Exception thrown: 'System.ServiceModel.FaultException`1' in System.Private.CoreLib.dll
Exception thrown: 'System.ServiceModel.FaultException`1' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: No imagedescriptor records found for image attribute :ant_planimetryimage of ant_planimetria record with id 035b264a-b510-ec11-b6e6-000d3a2b7e5a (Fault Detail is equal to Exception details: 
ErrorCode: 0x80040217
Message: No imagedescriptor records found for image attribute :ant_planimetryimage of ant_planimetria record with id 035b264a-b510-ec11-b6e6-000d3a2b7e5a
TimeStamp: 2021-12-15T17:34:37.9997757Z
--
Exception details: 
ErrorCode: 0x80040217
Message: No imagedescriptor records found for image attribute :ant_planimetryimage of ant_planimetria record with id 035b264a-b510-ec11-b6e6-000d3a2b7e5a
TimeStamp: 2021-12-15T17:34:37.9997757Z
--

**Comment by MattB-msft** [comment]
OnPrem or OnLine?

**Comment by andreatosato** [comment]
Online.
I use ClientCredential with Azure App Registration

**Comment by MattB-msft** [comment]
Are you using CMK? ( Customer Managed Keys? )

**Comment by andreatosato** [comment]
No

**Comment by andreatosato** [comment]
Sorry, I connect to wrong environment.
I change a little code and refactor.

```cs
 public class DownloadImages
    {
        private static CrmContext cli;

        public DownloadImages(CrmContext db)
        {
            cli = db;
        }

        public async Task<byte[]> DownloadAsync(Entity e, string fileAttributeName = null)
        {
            // Initialize download
            InitializeFileDownload(e, fileAttributeName, out string downloadToken, out long fileSizeDownload, out string downloadFileName);

            // Download
            return await DownloadFileAsync(downloadToken, fileSizeDownload, downloadFileName);
        }

        private void InitializeFileDownload(Entity e, string fileAttributeName, out string token, out long fileSize, out string downloadFileName)
        {
            string requestName;
            OrganizationRequest initializeDownloadRequest;

            if (e.Attributes.Contains("activitymimeattachmentid"))
            {
                requestName = "InitializeAttachmentBlocksDownload";
                initializeDownloadRequest = new InitializeAttachmentBlocksDownloadRequest
                {
                    Target = e.ToEntityReference()
                };
            }
            else if (e.Attributes.Contains("annotationid"))
            {
                requestName = "InitializeAnnotationBlocksDownload";
                initializeDownloadRequest = new InitializeAnnotationBlocksDownloadRequest
                {
                    Target = e.ToEntityReference()
                };
            }
            else
            {
                requestName = "InitializeFileBlocksDownload";
                initializeDownloadRequest = new InitializeFileBlocksDownloadRequest
                {
                    Target = e.ToEntityReference(),
                    FileAttributeName = fileAttributeName
                };
            }
            var resp3 = cli.Execute(initializeDownloadRequest);
            token = (string)resp3.Results["FileContinuationToken"];
            fileSize = string.Equals(requestName, "InitializeFileBlocksDownload") ? (long)resp3.Results["FileSizeInBytes"] : (int)resp3.Results["FileSizeInBytes"];
            downloadFileName = (string)resp3.Results["FileName"];
        }

        private async Task<byte[]> DownloadFileAsync(string downloadToken, long fileSizeDownload, string downloadFileName)
        {
            long offset = 0;
            long chunkSizeDownload = 4 * 1024 * 1024; // 4 MB
            int chunksCountDownload = (int)(fileSizeDownload / (float)chunkSizeDownload) + 1;
            int chunkNumberDownload = 0;

            using (MemoryStream outputFile = new MemoryStream())
            {
                List<Task> downloadTasks = new List<Task>();
                int counter = 0;
                byte[] emptyBytes = new byte[fileSizeDownload];
                while (fileSizeDownload > 0)
                {
                    chunkNumberDownload++;
                    if (fileSizeDownload < chunkSizeDownload)
                    {
                        chunkSizeDownload = (int)fileSizeDownload;
                    }

                    var downloadRequest = new DownloadBlockRequest
                    {
                        FileContinuationToken = downloadToken,
                        Offset = offset,
                        BlockLength = chunkSizeDownload
                    };

                    downloadTasks.Add(DownloadChunk(Convert.ToInt32(offset), downloadRequest));
                    offset += chunkSizeDownload;
                    fileSizeDownload -= chunkSizeDownload;
                    counter++;
                }

                await Task.WhenAll(downloadTasks.ToArray());
                await outputFile.WriteAsync(emptyBytes, 0, emptyBytes.Length);
                outputFile.Flush();

                return outputFile.ToArray();

                async Task DownloadChunk(int fileDataOffset, DownloadBlockRequest downloadRequest)
                {
                    var response3 = cli.Execute(downloadRequest);
                    var result = (byte[])response3.Results["Data"];
                    Buffer.BlockCopy(result, 0, emptyBytes, fileDataOffset, result.Length);
                    await Task.CompletedTask;
                }
            }
        }
    }
```
