### ISSUE TITLE
Unable to cast object of type 'generatedProxy_3' to type 'Microsoft.PowerPlatform.Dataverse.Client.IOrganizationServiceAsync'

### ISSUE THREAD

**Issue by Dashulol** [microsoft/PowerPlatform-DataverseServiceClient#219]
Using Microsoft.PowerPlatform.Dataverse.Client 0.5.10

I got an Azure function with a Blob trigger that parses the blobs and writes to Dynamics 365 CE. Was working fine until the frequency of Blobs uploaded increased drastically. First I was seeing the error 
> Unable to cast object of type 'generatedProxy_**2**' to type 'Microsoft.PowerPlatform.Dataverse.Client.IOrganizationServiceAsync'

I read through #48 and added 
> RequireNewInstance=true

to the connectionString.

Now it looks like more Blobs get processed but the majority now produces the very similar exception
> Unable to cast object of type 'generatedProxy_**3**' to type 'Microsoft.PowerPlatform.Dataverse.Client.IOrganizationServiceAsync'

**Comment by Dashulol** [comment]
Setting UseWebApi = false seemingly solved the issue,

**Comment by MattB-msft** [comment]
@Dashulol can you link a repro of your use case?  that would help us understand what is happening as it sounds like a threading issue.

**Comment by MattB-msft** [comment]
We have refactored some of the client code in this upcoming release to see if we can lock this down. or at least give us a better understanding of where the type is getting lost. 

should be in the next update.

**Comment by sdhz236** [comment]
I still occasionally got the error "Unable to cast object of type 'generatedProxy_2' to type 'Microsoft.PowerPlatform.Dataverse.Client.IOrganizationServiceAsync'", The version of Microsoft.powerplatform.dataverse.client is 0.6.1
