### ISSUE TITLE
Microsoft.Xrm.Sdk.Client.RealmInfo class missing

### ISSUE THREAD

**Issue by andrew-sumner** [microsoft/PowerPlatform-DataverseServiceClient#221]
I'm porting code to dotnet 6.0 from the older .net framework libraries and can't find the RealmInfo class. Can you recommend an alternative to using this class?

**Comment by MattB-msft** [comment]
Only types we have made available in Microsoft.Xrm.Sdk namespace are included as part of the dataverse serviceclient.

Realminfo is part of our core sdk. It should not be accessed directly. 

Can I ask why your trying to access it? And what your trying to do?

**Comment by andrew-sumner** [comment]
I've attached the code where it's used. Unfortunately the developer who wrote this has just gone on leave so I can't give any background to why this is required. I do know it was written 4 years ago.

It's probably well overdue for a rewrite, so we'll look at alternatives in the new year.


```
private const string RealmServicePage = "https://login.microsoftonline.com/GetUserRealm.srf";

internal static RealmInfo GetRealmServiceResponse(string userName)
{
    var request = (HttpWebRequest)HttpWebRequest.Create(new Uri($"{RealmServicePage}"));
    request.ContentType = "application/x-www-form-urlencoded";
    request.Method = "POST";

    var body = $"handler=1&login={HtmlEncodeString(userName)}&xml=1";
    byte[] byteArray = Encoding.UTF8.GetBytes(body);

    using (Stream stream = request.GetRequestStream())
    {
        stream.Write(byteArray, 0, byteArray.Length);
    }

    using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
    {
        if (response != null && response.StatusCode == HttpStatusCode.OK)
        {
            using (Stream responseStream = response.GetResponseStream())
            {
                using (XmlReader reader = XmlReader.Create(responseStream))
                {
                    var serialiser = new XmlSerializer(typeof(RealmInfo));
                    return (RealmInfo)serialiser.Deserialize(reader);
                }
            }
        }
    }

    return null;
}
```

**Comment by MattB-msft** [comment]
Ah.  That code is based on a sample from v5.   It will no longer work post April of next year for online. 

Good time to rewrite for using either the dataverse serviceclient or the crm serviceclient
