### ISSUE TITLE
Microsoft.Dynamics.Sdk.Messages 0.5.10 contains an outdated version of the "Client" dependency

### ISSUE THREAD

**Issue by numsantos** [microsoft/PowerPlatform-DataverseServiceClient#224]
I was using the 0.4.21 version of the "Microsoft.Dynamics.Sdk.Messages" nugget package. Since this nugget contained the ServiceClient library I had no issue in using IOrganizationServiceAsync (Which is currently injected into all my Repository Classes). Everything went smooth until I decided to Update the nugget packages.

On Updating to the current version (0.5.10), the ServiceClient class lost its Inheritance from IOrganizationServiceAsync to be replaced with  IOrganizationServiceAsync2. 
This is not a problem if you also update Microsoft.PowerPlatform.Dataverse.Client nugget too, because in the current version of the package: IOrganizationServiceAsync2 inherits from IOrganizationServiceAsync. 

But of course, I didn't and had to run in a long tangent to know why my ServiceClient was not inheriting from IOrganizationServiceAsync (and any type cast would fail). and comparing with the documentation made no sense. until I saw this:

![image](https://user-images.githubusercontent.com/40486762/148222360-1f1d2117-de38-4fc4-97fc-7cf32893716f.png)

Since Microsoft.Dynamics.Sdk.Messages depend on Microsoft.PowerPlatform.Dataverse.Client, is it also possible to update nugget dependency to avoid this type of confusion?

Solution:
Ultimately, to fix the issue I had to install Microsoft.PowerPlatform.Dataverse.Client nugget 0.5.10 which was no big deal, just confusing

Have all a good year!

**Comment by MattB-msft** [comment]
Thanks for your feedback,, we will see if we can sort that out for you in the next drop. 
thanks again.
