### ISSUE TITLE
ResetLastError method does not work

### ISSUE THREAD

**Issue by 1-Accelerator-1** [microsoft/PowerPlatform-DataverseServiceClient#229]
https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/07b3400f94af784f12e488038222a2ef538321ab/src/GeneralTools/DataverseClient/Client/DataverseTraceLogger.cs#L96-L102

String is immutable. When you delete the LastError field, it is not deleted, but a new line is created in which there are no characters, that is, an empty string. To fix this, you must return the result of the Remove method in the LastError field.

base.LastError = base.LastError.Remove(0, LastError.Length - 1);

**Comment by MattB-msft** [comment]
This has been fixed by the team and will be in the next drop/.
