### ISSUE TITLE
Single quote is not property handled in DataverseClient?

### ISSUE THREAD

**Issue by keqli** [microsoft/PowerPlatform-DataverseServiceClient#231]
Let's say we have an entity like below. The key attribute value "Men's Shoes" contains a single quote. Using `ServiceClient.Update` or `UpdateRequest` to update this entity will result in an error like this:
"There is an unterminated literal at position 30 in '(name='Men's Shoes')'.".

```
    Entity entity = new ("a", "some entity id guid");
    EntityReference entityReference = new ("b", new KeyAttributeCollection());
    entityReference.KeyAttributes.Add("name", "Men's Shoes");
    entity["refb"] = entityReference;
```

It seems a bug that single quote is not property handled/escaped. Would you please take a look?

**Comment by JimDaly** [comment]
@MattB-msft 
Seems like this is using OData.
Per this part of OData spec: [OData Version 4.0. Part 2: URL Conventions Plus Errata 03 2  URL Components](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752335) 

_One of these rules is that single quotes within string literals are represented as two consecutive single quotes._

I think the single quote character needs to be escaped like so:

    (name='Men''s Shoes')

**Comment by MattB-msft** [comment]
Thanks for looking into it @JimDaly ,  The team will take that up for fix.

**Comment by keqli** [comment]
Is there an ETA of when it will be fixed?

**Comment by MattB-msft** [comment]
This looks like a server side bug right now,  we have been working with the API team on it but progress has been slow due to a number of other priorities . 
Will follow up on it in the next meeting with the team.

thanks for poking it.

**Comment by MattB-msft** [comment]
Looked over this in the case of CRUD Operations that are not using Alt Key's and it seems to now be working. 
can you verify that you're only seeing when you try to use it as a alt key?  ( we are still looking at that code path. )

**Comment by MattB-msft** [comment]
NM, we found the issue in the client,  
Fixed in the next drop.

**Comment by keqli** [comment]
Thanks team! I've verified it in latest version 0.6.6.
