### ISSUE TITLE
Refactoring Primary operations to Extensions

### ISSUE THREAD

**Issue by noakesey** [microsoft/PowerPlatform-DataverseServiceClient#241]
>>0.6.x refactors much of the primary ServiceClient interface, narrowing its focus to primary operations against Dataverse. the balance of the feature set has been moved to Microsoft.PowerPlatform.Dataverse.Client.Extensions. - We are seeking feedback on this refactor.

I welcome this refactor as I noticed before that GetGlobalOptionSetMetadata wasn't on an interface!  It's now still an extension of ServiceClient though - should it be defined as an extension of an interface so I can inject it?

I am currently injecting IOrganizationServiceAsync2 and casting back to ServiceClient when I need the extension... is that the correct approach?

var metadata = ((ServiceClient)serviceClient).GetEntityAttributeMetadataForAttribute(entity, name);

**Comment by MattB-msft** [comment]
Yes that is the correct approach for now,  The extensions were never setup with their own interfaces, which is something we plan to address in the future.  We are currently discussing splitting them further into their own Namespaces to allow you to filter down what you need .
