### ISSUE TITLE
System.ServiceModel namespaces in Microsoft.Xrm.Sdk.dll

### ISSUE THREAD

**Issue by MarkMpn** [microsoft/PowerPlatform-DataverseServiceClient#242]
In 0.6.1, various classes in System.ServiceModel.* and System.IdentityModel.* namespaces have been included in the Microsoft.Xrm.Sdk assembly. This causes compiler errors when a project references both this package and one of the standard System.ServiceModel assemblies.

I've been able to work around it by adding an [alias to the package reference](https://github.com/Data8/DataverseClient/blob/17fa8909fe85ce5281f557524f93b39012a7316b/Data8.PowerPlatform.Dataverse.Client/Data8.PowerPlatform.Dataverse.Client.csproj#L85) but I wonder if it would be possible to avoid having to do this by including the classes via a reference to the standard assemblies, or if the classes have to be copied then changing the namespaces?

**Comment by MattB-msft** [comment]
This is a byproduct of work on the dataverse server @MarkMpn ,  for the moment I would stick with aliasing the versions your using outside of the Xrm.sdk.dll.   The team is working to make those internally visible only as we work though things with the .net core team and WCF folks.
