### ISSUE TITLE
[Question] What is the difference of UseWebApi

### ISSUE THREAD

**Issue by zsybupt** [microsoft/PowerPlatform-DataverseServiceClient#243]
Hi team,
  I see that if UseWebApi is enabled, the request will be sent by HttpClient, but if it is false, it will use WebProxyClient. What is the main difference of two clients, because we see there are several 'sync over async' calls in WebProxyClient, we have some concerns about this, what is the best practice to use ServiceClient.

Thanks!

**Comment by MattB-msft** [comment]
This flag,  as marked in the intelisense and in the code [here](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/254952f3a781f1ab363c56f1a43c4d9b49652fed/src/GeneralTools/DataverseClient/Client/ServiceClient.cs#L618) is a temporary flag we use to support force switching some operations between using WebAPI and our older Protocol,  specifically for things that we are working on fixing, or optimizing . 

In general you should ignore its existence as it will be removed from the interface in the future.

**Comment by zsybupt** [comment]
so in the future, all the operations will use WebAPI, right ? I see when using WebAPI, the underlying is a HttpClient, and there is no sync over aysnc code path

**Comment by MattB-msft** [comment]
We support both Sync and Async calling patterns currently,  if you use a sync call pattern, and we choose to use http, we will manage the blocking behavior inside the call, 

Insofar as the future, we will not necessarily use the WebAPI for things, One of the benefits of the dataverse ServiceClient is that we can adjust particular protocol we use based on the needs of the specific call.  It is also why we do not expose the wire protocol to the end developer as it allows us to change it to sute the needs of both the client and server behaviors to optimize the performance and capabilities of the Client without dealing with particular protocol call pattern challenges.
