### ISSUE TITLE
Setting EntityReference using key not working if key is numerical

### ISSUE THREAD

**Issue by petersk80** [microsoft/PowerPlatform-DataverseServiceClient#244]
Let's say I want to create and invoice referencing a salesorder using key instead of salesorderid.

` var invoice = new Entity("invoice");`
`invoice["salesorderid"] = new EntityReference("salesorder", "new_key", 123);`
`service.Create(invoice);`

This will fail with **Bad Request - Error in query syntax**
By inspecting the request I see that the content is generated with ' around the int value making it a string: 
`{ "salesorderid@odata.bind":"/salesorders(new_key=\u0027123\u0027)"}`

**Comment by petersk80** [comment]
It works if you chose service.UseWebApi = false, but I just wanted to let you know.

**Comment by MattB-msft** [comment]
Thanks for Reporting this @petersk80,  We have been chasing a number of these inconsistencies in the way the WebAPI handles alternate keys.  Will take a look.

**Comment by MattB-msft** [comment]
This has been identified and fixed in the next drop.

**Comment by petersk80** [comment]
Excellent, thank you. Keep up the great work
