### ISSUE TITLE
Best practices for DI in Azure Functions

### ISSUE THREAD

**Issue by noakesey** [microsoft/PowerPlatform-DataverseServiceClient#245]
I'm trying to figure out the best practice for injecting ServiceClient into an Azure function and I'm concerned about either exhausting my connection pool by creating a ServiceClient for each request, or trying to use a static ServiceClient that is no longer authenticated..

With the client Id / secret authentication flow, is it best to 

[a] inject ServiceClient (IOrganizationServiceAsync2) as a scoped service, specifiying useUniqueInstance=false
[b] create singleton/static ServiceClient for use by all functions.  Wil this handle timeouts / re-authentication etc..?

I can't decide whether HttpClient is already pooling connections.

**Comment by noakesey** [comment]
Update - I'm using builder.Services.AddScoped<IOrganizationServiceAsync2> with useUniqueInstance = false.

This seems to be having the desired behaviour - the service client reauthenticates and pools connections internally.

**Comment by veljko** [comment]
Can you please post exact code you are using? Are you also injecting HttpClient or/and using Polly?
Thanks!

**Comment by noakesey** [comment]
Hi veljok,

I don't think the current API allows us to inject our own HttpClient.  I am not using Polly as I am leaving the retry handling to logic apps / functions.

I ended up with something like this:  

```
public class Startup : FunctionsStartup
{
    private readonly string appD365ClientId = Environment.GetEnvironmentVariable(...);
    private readonly string appD365ClientSecret = Environment.GetEnvironmentVariable(...);
    private readonly string appD365Environment = Environment.GetEnvironmentVariable(...);

    public override void Configure(IFunctionsHostBuilder builder)
    {
        Uri appUri = new Uri(appD365Environment);

        //Scoped lifetime (new for each request)
        builder.Services.AddScoped<IOrganizationServiceAsync2>((s) =>
        {
            //Get detailed logs from ServiceClient in the function console to see how/when connections are created etc..
            ILogger logger = s.GetService<ILogger<Startup>>();

            return new ServiceClient(appUri, appD365ClientId, appD365ClientSecret, false, logger);
        });
    }
}
```

**Comment by rajyraman** [comment]
Hi @MattB-msft,

Is [this post](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/issues/191#issuecomment-950398003) still valid - for Functions specifically?

**Comment by reneduesmann** [comment]
Hey,

i have a problem too, to use DI in azure functions. It is a durable function.
Created a startup class
```
[assembly: FunctionsStartup(typeof(CSVImport.Startup))]

namespace CSVImport
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            string crmUrl = Environment.GetEnvironmentVariable(CrmUrl);
            string clientId = Environment.GetEnvironmentVariable(CrmClientId);
            string clientSecret = Environment.GetEnvironmentVariable(CrmClientSecret);
            Uri crmUri = new(crmUrl);

            builder.Services.AddScoped<IOrganizationServiceAsync>((x) =>
            {
                ILogger logger = x.GetService<ILogger<Startup>>();

                return new ServiceClient(crmUri, clientId, clientSecret, false, logger);
            });
        }
    }
}
```

And have this activity function

```
public static async Task ProcessCsvLandlineRecord([ActivityTrigger] Landline landline, ILogger logger, IOrganizationServiceAsync organizationServiceAsync)
{}
```

But when i start the app in VS, i get this exception
```
 Microsoft.Azure.WebJobs.Host: Error indexing method 'SPToCrmCsvImport_ProcessCsvLandlineRecord'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'organizationServiceAsync' to type IOrganizationServiceAsync. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
```
