### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0

### ISSUE THREAD

**Issue by Red1408192** [microsoft/PowerPlatform-DataverseServiceClient#250]
Currently using Microsoft.PowerPlatform.Dataverse.Client.Dynamics 0.6.1 in Net5.0

'Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
<img width="649" alt="image" src="https://user-images.githubusercontent.com/48690547/159717044-fa3960c1-d040-4514-a0e4-e339e09abc6a.png">

I'm currently developing a webApp that have to interact with the dynamics365 dataverse, while i'm updating an entity i get this error, but i can retrieve the records with no exception encountered. I tried a bit of everything: switch to netstandard2.1 or core3.1, install newtonsoft directly, ilRepack (didn't compile, required a different version of newtonsoft), switched between dataverse.client versions, nothing is working. Is this a bug?

**Comment by Red1408192** [comment]
There is actually an inner exception 'HttpOperationException: Operation returned an invalid status code 'BadRequest'', from the file [ConnectionService](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/master/src/GeneralTools/DataverseClient/Client/ConnectionService.cs) line: 2460
So the problem might be a bad formatting Update request, using fidler i can say the request was composed like so (i'm using a barebone test project for debugging)(some data have been obscured for security reason)
```
PATCH https://----------------------.api.crm4.dynamics.com/api/data/v9.2/ivg_accountmasters(b32d680b-6c5e-ec11-8f8f-000d3aad6a6c) HTTP/1.1
Host: ------------------.api.crm4.dynamics.com
Prefer: odata.include-annotations=*
If-Match: *
Accept: application/json
OData-MaxVersion: 4.0
OData-Version: 4.0
x-ms-client-request-id: df1ce1d0-c40c-48f3-978a-21c6736e4477
Cookie: ARRAffinity=ddbd35ea22bba90848b9819b03c6a584a038a6863e79a1fd37b488457a456fee; ReqClientId=9718c67c-6413-48c4-b570-5d375bee74ec; orgId=290e6e1a-f2ca----------------------------------; 
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImpTMVhvMU9XRGpfNTJ2YndHTmd2UU8yVnpNYyIsImtpZCI6ImpTMVhvMU9XRGpfNTJ2YndHTmd2UU8yVnpNYyJ9.eyJhdWQiOiJodHRwczovL2l2ZWNvLWl2ZWNvY3JtLWRldi5jcm00LmR5bmFtaWNzLmNvbSIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0Lzc5MzEwZmIwLWQzOWItNDg2Yi1iNzdiLTI1ZjNlMGM4MmEwZS8iLCJpYXQiOjE2NDgwNDI3MzUsIm5iZiI6MTY0ODA0MjczNSwiZXhwIjoxNjQ4MDQ2NjM1LCJhaW8iOiJFMlpnWU9pNXVNblh1TmIzNUhuZCt1MFA0MnpMQUE9PSIsImFwcGlkIjoiNDU4NmNiNWEtOTc2ZC00MGNjLWIxODEtNWNkYzZiZDI4MTUwIiwiYXBwaWRhY3IiOiIxIiwiaWRwIjoiaHR0cHM6----------------------------------------------------------------ZiLWI3N2ItMjVmM2UwYzgyYTBlLyIsIm9pZCI6IjQyMTFkZTRjLTU0MzQtNDM3ZS1hZmY3LTQxODdhZDE2YjcyYiIsInJoIjoiMC5BU0FBc0E4eGVadlRhMGkzZXlYejRNZ3FEZ2NBQUFBQUFBQUF3QUFBQUFBQUFBQWdBQUEuIiwic3ViIjoiNDIxMWRlNGMtNTQzNC00MzdlLWFmZjctNDE4N2FkMTZiNzJiIiwidGlkIjoiNzkzMTBmYjAtZDM5Yi00ODZiLWI3N2ItMjVmM2UwYzgyYTBlIiwidXRpIjoicnlJUUNxTTFTVXFCNDNNY0JUSmxBQSIsInZlciI6IjEuMCJ9.FCks6vakxNE4xZNxRJMCkRUxuqCkrnuMoTnSSOYncwiGGqx2XauueVNjGOZ01mq_HLl9kzYyQ1aikttWH9dSBBxLbNQFWuj1A0H90PNXqhNl8HkEoPfvNI7tz6CBjUi5lx4Ft-FgOlQT25BfPaNvY64bO9fTMRDsPYnT7LlHFDjNVEmIGI2EvVg04ZQxrPw2qgpbCIeTWMuY-zdTdDZEz8SDFj_VXo96utvQ_Uzm7Mg2TM12elGg1jDtJ5DuhQfuwy1EWlISfjfR-bCXEs----------------------------------------------------------------------------
User-Agent: teeest (DataverseSvcClient:0.0.5.10)
Connection: Keep-Alive
Content-Type: application/json
Content-Length: 80

{"ivg_duns":"1111","ivg_accountmasterid":"b32d680b-6c5e-ec11-8f8f-000d3aad6a6c"}
```

**Comment by Red1408192** [comment]
By making the call with postman i can say that the problem is actually from the dataverse itself:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/48690547/159715436-2e79b98e-3384-4b43-875f-1c151997328e.png">

**Comment by Red1408192** [comment]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/48690547/159715588-39eb09e7-f293-43f3-93e8-53d4fa8dea53.png">
By reproducing the call in postman i can say that the exception is from the dataverse itself

**Comment by Red1408192** [comment]
Solved, was a plugin installed in powerapp that was raising the exception, i close the issue

**Comment by hcyang** [comment]
@Red1408192,  was the plugin developed/installed by you or from somewhere else? Try downgrading your Newtonsfot.JSON to version 11 and see how it goes.
