### ISSUE TITLE
ClientSecret connection failing with "Need a non-empty authority"

### ISSUE THREAD

**Issue by andrew-sumner** [microsoft/PowerPlatform-DataverseServiceClient#252]
Running on my development machine works, however when I run on a production server I get the error "Need a non-empty authority"

```
string connectionString ="AuthType=ClientSecret; Url=https://xxx.crm6.dynamics.com; ClientId=xxx; ClientSecret=xxx;"

var serviceClient = new ServiceClient(connectionString);
```

Can you explain what might be going on here so I can work around this issue?

**Comment by MattB-msft** [comment]
Sounds like your URL is incorrect to talk to the server, 
if you attach a logger or enabled the in memory logger to see in detail what is going on.

**Comment by andrew-sumner** [comment]
Turned out I had an HTTP_PROXY environment set which broke it.

Worked when removed that, and when added an HTTPS_PROXY variable alongside it, just not having HTTP_PROXY on its own.

**Comment by sujinbalajee** [comment]
Hi @andrew-sumner, I have similar issue. can you please explain it bit more ? what is HTTP_PROXY ?
Thanks in advance.

Regards
Sujin

**Comment by andrew-sumner** [comment]
Http_proxy is an environment variable

**Comment by sujinbalajee** [comment]
Hi @andrew-sumner , Thanks for the quick response. I Checked in the Prod server and don't see any Environment variable as HTTP_PROXY. 
There is something else that's blocking.
