### ISSUE TITLE
ServiceClient does not support TransactionScope?

### ISSUE THREAD

**Issue by MoranShusheng** [microsoft/PowerPlatform-DataverseServiceClient#256]
Hi,
   I wanted to execute the creation method and other  business logic in a transaction, but my test results showed that the data of Dataverse was not rolled back. Is this operation not supported?
This is a function app of Azure Service Bus trigger， code example:
public static class TestQueueManualAck
   `{`
        `[FunctionName("TestQueueManualAck")]`
        `public` static void Run([ServiceBusTrigger("%TargetQueueName%", Connection = "ServiceBusConnection", IsSessionsEnabled = `true)]Message` message, MessageReceiver messageReceiver,  ILogger log)
        `{`
            `var messageBody = System.Text.Encoding.UTF8.GetString(message.Body);`
           ` log.LogInformation($"C# ServiceBus queue trigger function processed message: {messageBody}");`
           `var dataverseConnection = Environment.GetEnvironmentVariable("DataverseConnection");`
            `using var scope = new TransactionScope(TransactionScopeOption.RequiresNew, TransactionScopeAsyncFlowOption.Enabled);`
            `try`
            `{`
                `IOrganizationService _organizationservie = new ServiceClient(dataverseConnection);`
                `Entity entity1 = new Entity("new_xm_productpack");`
                `entity1["new_name"] = "testImportfromExcel123";`
                `entity1["new_country_id"] = new EntityReference("new_country", new Guid("7a0e46fd-bb03-eb11-a813-000d3aa3ee47"));`
                `_organizationservie.Create(entity1);`
               `throw new Exception("Manual exception");`
                `messageReceiver.CompleteAsync(message.SystemProperties.LockToken);`
                `scope.Complete();`
            `}`
            `catch (Exception ex)`
            `{`
                `scope.Dispose();`
                `throw new Exception($"Function App execution failed,Exception :{ex.Message}-----trace is {ex.StackTrace}");`
            `}`
        `}`
    `}`

**Comment by MattB-msft** [comment]
The Dataverse SDK does not support client to server transaction scopes.  Once a command is executed, that command either completes or fails within its own scope.  

If you have several Dataverse SDK Operations that you want to execute and run as a transaction from a Client you CAN do that using the ExecuteTransactionRequest message.  See: [ExecuteTransactionRequest](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.messages.executetransactionrequest?view=dynamics-general-ce-9).   This method will execute all operations in the request as a unit, if any one message fails, all of them are rolled back. 

However, when operating in the context of a plugin hosted on Dataverse, this is slightly different.  In that situation, depending on the plugin staged used, the execution of the plugin happens within a transaction and any fault/exception generated causes the entire transaction to be cancelled, effectively causing all operations inside the plugin to be rolled back.

**Comment by MattB-msft** [comment]
There are no plans to offer this capability for the public API at this time given the potential negative impacts it has on the users of the system.

There may be an opportunity to explore supporting this in the future as our API infrastructure evolves. but no promises right now.
