### ISSUE TITLE
Enable server caching

### ISSUE THREAD

**Issue by sferhah** [microsoft/PowerPlatform-DataverseServiceClient#260]
Contrary to the full .net client, the current implementation disables server caching by systematically sending the http header "Cache-Control: no-cache, max-age=0".

Is it possible to inject a custom HttpClient with NoCache to false?

**Comment by MattB-msft** [comment]
The Dataverse Platform does not support that header behavior at all,  Dataverse uses an its own caching system.
That is why we are setting the headers to default (none) at the moment for the Http connections (where we use them)
