### ISSUE TITLE
SuppressDuplicationDectection in request parameter is not taken when it is false bool value

### ISSUE THREAD

**Issue by wszdwp** [microsoft/PowerPlatform-DataverseServiceClient#266]
Here https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/254952f3a781f1ab363c56f1a43c4d9b49652fed/src/GeneralTools/DataverseClient/Client/ConnectionService.cs#L1822-L1830

if req.Parameters[Utilities.RequestHeaders.SUPPRESSDUPLICATEDETECTION] is false, suppressDuplicateDetection  will be null and not set to false, then in 
https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/254952f3a781f1ab363c56f1a43c4d9b49652fed/src/GeneralTools/DataverseClient/Client/ConnectionService.cs#L1912-L1915 will not add this request header with value to "false"

**Comment by MattB-msft** [comment]
Flagged as a bug.. will get that fixed.
