### ISSUE TITLE
Reason behind IOrganizationServiceAsync2

### ISSUE THREAD

**Issue by vmcbaptista** [microsoft/PowerPlatform-DataverseServiceClient#271]
Is there any reason for not having a single async interface?
Will IOrganizationServiceAsync2 and IOrganizationServiceAsync be merged into single one in the future?

**Comment by MattB-msft** [comment]
It will not be merged in the short term.   We _may_ merge them in the future based on underlying communications and protocol changes we make. 

IOrganziationAsync2 is very specific to the implementation in the Dataverse client.  Whereas IOrganziationAsync allows us to, while still being client specific, code gen asynchronous com's with the Dataverse Server over the protocol's we are using currently.
