### ISSUE TITLE
125 Errors and 70 Warnings following a fresh download

### ISSUE THREAD

**Issue by stephencqub1** [microsoft/PowerPlatform-DataverseServiceClient#276]
Hello, after downloading a zip and building a solution (DataverseClientWithConnector.sln for example), I'm presented with 125 errors and 70 warnings.

This is 'out of the box' behaviour simply by downloading, unzipping and opening a solution into visual studio.

I must be missing a prerequisite. Any idea what that is? Anyone else seeing this issue?

The errors mainly fall into the category of the referenced XRM package but there are other errors.

Here's an example of an error message:
"_Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1603	Microsoft.PowerPlatform.Dataverse.Client depends on Microsoft.Crm.Sdk.Proxy (>= 4.7.7698-v9.0-master.release) but Microsoft.Crm.Sdk.Proxy 4.7.7698-v9.0-master.release was not found. An approximate best match of Microsoft.Crm.Sdk.Proxy 5.0.12 was resolved.	Microsoft.PowerPlatform.Dataverse.WebResourceUtility	D:\Dynamics\1\src\GeneralTools\DataverseClient\WebResourceUtility\Microsoft.PowerPlatform.Dataverse.WebResourceUtility.csproj	1_
"

Here's an example of a warning message:
"_Severity	Code	Description	Project	File	Line	Suppression State
Warning		Unable to locate the .NET SDK as specified by global.json, please check that the specified version is installed.	Microsoft.PowerPlatform.Dataverse.WebResourceUtility		14_	
"

Thanks for any guidance.

**Comment by MattB-msft** [comment]
We do not support building this project external to Microsoft, we call this out on the readme on the home page. 

MattB

**Comment by stephencqub1** [comment]
Thank you for the reply & correction. That does seem rather obvious now :-) I think my confusion partially arose from these guys having a built version of it. https://www.nuget.org/packages/NY.Dataverse.LINQPadDriver/

Am I right in thinking that this project allows (or will allow when released) early loading intellisense dynamically? i.e. without needing to have an export from the live system in the project. And would also be particularly suitable for plugins due to the file size restrictions?

**Comment by MattB-msft** [comment]
The nuget packages include intellisense support currently. if you mean model code generation, that is a function of a host program vs this client itself.  We currently provide that as a base tool called crmserviceutil which manny members of the community have written extensions for.

This will not support plug-in development at this time due to limitations in our plug-in system host.  We may off support in a future version as we update that system.
________________________________

**Comment by stephencqub1** [comment]
https://www.nuget.org/packages/NY.Dataverse.LINQPadDriver/
This link has the following paragraph:

_This new driver is a dynamic driver that uses [Microsoft.PowerPlatform.Dataverse.Client](https://github.com/microsoft/PowerPlatform-DataverseServiceClient) assemblies which targets .NET 5. The Tables (Entities) and associated metadata are regenerated everytime LINQPad is opened, so that you don't need to worry about keeping Dataverse Metadata and LINQPad context in sync._

This is what I meant to say earlier about late bound vs early bound.
My understanding is that people who use the early bound approach must currently include a copy of their system's extracted entity and optionset definitions so that intellisense can be populated.

So, I'm wondering if the this new driver is dynamic and allows early bound without having to include a copy of the defintions.

Also, how did the people at the link above get the driver to work if they are outside microsoft?

**Comment by veljko** [comment]
> This is what I meant to say earlier about late bound vs early bound. My understanding is that people who use the early bound approach must currently include a copy of their system's extracted entity and optionset definitions so that intellisense can be populated.
> So, I'm wondering if this new driver is dynamic and allows early bound without having to include a copy of the defintions.
> Also, how did the people at the link above get the driver to work if they are outside microsoft?

I do not think early binding and Client should be looked at as one thing. Getting early bindings happens in design time and Client is used in runtime. I've been using this (https://github.com/delegateas/XrmContext/wiki/Using-XrmContext-in-a-.net-core-project) successfully, might help you too.

**Comment by stephencqub1** [comment]
Thank you veljko. I'll have a look at that.

What I picked up from reading this https://www.nuget.org/packages/NY.Dataverse.LINQPadDriver/ is that linqpad allows dynamic design time work so that all happens in the background. That's quite neat as it removes the need to consider regenerating the xrmcontext definitions. *I think*. Perhaps I have the wrong impression of it as I haven't used the linqpad version.

They are stating that as:
_"This new driver is a dynamic driver that uses Microsoft.PowerPlatform.Dataverse.Client assemblies which targets .NET 5. The Tables (Entities) and associated metadata are regenerated everytime LINQPad is opened, so that you don't need to worry about keeping Dataverse Metadata and LINQPad context in sync."_

So I wondered if it was possible to get the same functionality outside of linqpad using this dynamic driver. Something like that would probably have wide appeal?

**Comment by MattB-msft** [comment]
While I have not seen the code for this tool, from the behavior I would expect that it’s pulling the complete metadata from the server 15-20 megs of data) and creating (code gen) a temp assembly in memory with the types it brought down,  then loading that into the local runtime.

That would allow linq to work in linqpad.  But it’s not portable outside / to your own program. To get it into your program you would use the crmsvcutil to code gen the classes and add them to your client.

________________________________
