### ISSUE TITLE
After upgrade to 0.6.6 Unit tests fail with : OneTimeSetUp: System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.Cds.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by HectorMeneses333** [microsoft/PowerPlatform-DataverseServiceClient#277]
We want to upgrade to version 0.6.6 

However, some of our unit tests are failing now

 Message: 
    OneTimeSetUp: System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.Cds.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

Is there something else we need to do to upgrade besides upgrading the nuget packages?

**Comment by jordimontana82** [comment]
Not sure what you're using for unit testing but I had a similar (possibly same issue) because the extensions package had also to be updated:
https://github.com/DynamicsValue/fake-xrm-easy/issues/20

**Comment by jordimontana82** [comment]
Could you try removing <PackageReference Include="Microsoft.Dynamics.Sdk.Messages" Version="0.5.17" /> ?

That was replaced by <PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client.Dynamics" Version="0.6.6" />

**Comment by HectorMeneses333** [comment]
Looks like your message is incomplete. Could you elaborate? 
Thank you!

**Comment by HectorMeneses333** [comment]
Removed Microsoft.Dynamics.Sdk.Messages 
Reinstalled Microsoft.PowerPlatform.Dataverse.Client and Microsoft.PowerPlatform.Dataverse.Client.Dynamics  both 0.6.6

but issue is still there. :(

**Comment by jordimontana82** [comment]
If you try downgrading now to netcoreapp3.1 just to rule out net6 with these package references?

**Comment by HectorMeneses333** [comment]
downgraded to netcoreapp3.1 but issue is still there.

**Comment by MattB-msft** [comment]
Removed Microsoft.Dynamics.Sdk.Messages was removed.. Please remove that from all of your tests.

**Comment by HectorMeneses333** [comment]
Hi Matt,
I removed [Microsoft.Dynamics.Sdk.Messages](https://www.nuget.org/packages/Microsoft.Dynamics.Sdk.Messages)
but issue still happens

We are **targeting .net 6.0** ( however I also tried downgrading to netcoreapp3.1 as suggested by jordi above)... still the issue persists.
Here's what we have in our project:

<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
		<PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" Version="0.6.6" />
		<PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client.Dynamics" Version="0.6.6" />
		<PackageReference Include="NetCore.AutoRegisterDi" Version="2.1.0" />
		<PackageReference Include="System.Linq.Async" Version="6.0.1" />
		<PackageReference Include="System.Linq.Async.Queryable" Version="6.0.1" />
		<PackageReference Include="System.ServiceModel.Primitives" Version="4.9.0" />
    </ItemGroup>

**Comment by HectorMeneses333** [comment]
ahh... sorry... Original version is 0.5.5 for the 3 nugets: Client, Client.Dynamics and Dynamics.Sdk.Messages.

**Comment by HectorMeneses333** [comment]
Removed bin and obj folders from both feature and test projects. 
Closed VS 2022
Rebuilt solution

Tests are still failing with this error:
Message: 
OneTimeSetUp: System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.Cds.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified. 

I also cleared nuget caches from Toos/Options/Nuget Package Manager/General/Clear All Nuget cache(s)

**Comment by HectorMeneses333** [comment]
dotnet test reports same failures.
No dlls in GAC
No binding redirects

packages from feature project:
Microsoft.Extensions.Logging Version=6.0.0
Microsoft.PowerPlatform.Dataverse.Client Version=0.6.6
Microsoft.PowerPlatform.Dataverse.Client.Dynamics Version=0.6.6
NetCore.AutoRegisterDi Version=2.1.0
System.Linq.Async Version=6.0.1
System.Linq.Async.Queryable Version=6.0.1
System.ServiceModel.Primitives Version=4.9.0

packages from test project:
Microsoft.NET.Test.Sdk Version= 17.2.0
Moq Version= 4.17.2
NUnit Version= 3.13.3
NUnit3TestAdapter Version= 4.2.1
coverlet.collector Version= 3.1.2
+ our internal feature project

**Comment by jordimontana82** [comment]
Few things, you downgraded the project but I still see logging package using net6 right?

Also, Try removing the NetCore.AutoRegisterDi package, it targets .netstandard 2.0 only and the dataverse client package doesn't support that.


@MattB-msft  might be able to assist better here....

**Comment by MattB-msft** [comment]
@HectorMeneses333 ,  
There are few things left to check before I would have to say "I need to see the solution".
1) Check all projects (csproj files and such) for Nuget package references to Microsoft.cds.sdk.  If you find any, remove them. 
2) Check all includes ( usings ) for Microsoft.cds.sdk,  if you find any, remove them.

In short, there should be no mention of Microsoft.cds.sdk anywhere in your solution.

**Comment by HectorMeneses333** [comment]
Ran
grep -r "Microsoft.Cds.Sdk.dll" in our project directory
got this match:
./.vs/{OUR PROJECT FOLDER}/DesignTimeBuild/.dtbcache.v2

I removed it... Ran the test again... still had the issue...

doing a grep for "Microsoft.Cds.Sdk" 
got this match:
Binary file ./{OUR TEST PROJECT FOLDER}/bin/Debug/net6.0/Microsoft.Xrm.Sdk.dll matches

So it looks like Microsoft.Xrm.Sdk.dll still holds a reference to Microsoft.Cds.Sdk?

**Comment by MattB-msft** [comment]
So we are at the point where I now need to see what your doing :) 
There is no intra dependency between any shipping lib and Microsoft.Cds.Sdk. 

Is this something you can share with me on Git?  If not could you goto the Nuget Package for the Dataverse ServiceClient and click the contact the owners link.   That will send an email to us and I can reach out to you directly to setup a call to review waht you have going on.

**Comment by jordimontana82** [comment]
@HectorMeneses333  I might be a bit biased, but given the time spent by you, Matt and myself just trying to build the solution and we haven't even mocked anything yet, maybe you could give [FakeXrmEasy a go](https://github.com/DynamicsValue/power-apps-bootcamp-2022-05)... supports both DataverseClient and CrmSdk.CoreAssemblies, it comes with an In-Memory database + its own query engine, and even pipeline simulation features, plus you don't have to mock anything....

**Comment by HectorMeneses333** [comment]
Matt, I will reach out to you shortly.

Jordi, I'm not familiar with FakeXrmEasy... but will review that in the future.

**Comment by HectorMeneses333** [comment]
Thank you for your help identifying the circular reference we had in our projects. A referenced project had a stale dll with the reference to Microsoft.Cds.Sdk.
