### ISSUE TITLE
'Service Client is not connected' with ExternalTokenManagement and new ServiceClient(ConnectionOptions) ctor

### ISSUE THREAD

**Issue by fowl2** [microsoft/PowerPlatform-DataverseServiceClient#288]
I'm updating my code to take advantage of the new `SerivceClient(ConnectionOptions)` constructor.

The working code:

``` c#
  new ServiceClient(
      instanceUrl: uri,
      tokenProviderFunction: GetToken,
      useUniqueInstance: true,
      logger: logger);
```

Switching to the new constructor:
``` c#
  new ServiceClient(connectionOptions: new()
  {
    AccessTokenProviderFunctionAsync = GetToken,
    AuthenticationType = Microsoft.PowerPlatform.Dataverse.Client.AuthenticationType.ExternalTokenManagement,
    ServiceUri = uri,
    Logger = logger,
    RequireNewInstance = true, // seems to be true by the default anyway (undocumented/change?)
    // SkipDiscovery also seems to true by default anyway (undocumented/change?)
  });
```

I receive this exception calling `Execute()`:

> Microsoft.PowerPlatform.Dataverse.Client.Utils.DataverseConnectionException:
> 'Service Client is not connected to Dataverse. Please recreate this Service Client.'
>    at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.ValidateConnectionLive()
>    at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.ExecuteOrganizationRequestImpl(OrganizationRequest req, String logMessageTag, Boolean useWebAPI, Boolean bypassPluginExecution)
>    at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.Execute(OrganizationRequest request)

The exception occurs for:
* all combinations of `RequireNewInstance` and `SkipDiscovery`
* regardless of whether `deferConnection` is true or false
* regardless of whether `Connect()` is called or not

`GetToken` is never called.

The only message logged is this warning, which seem spurious:
> Client ID not supplied, using SDK Sample Client ID for this connection

Environment: I'm using .NET 6.0 in an Azure Function running locally in the Visual Studio 2022 Version 17.2.4 debugger.

As far as I can tell both constructors calls are equivalent - what am I missing?

**Comment by MattB-msft** [comment]
We have found the issue there and corrected it, expect an update later today / tomorrow for it. 
Also the behavior of both skipdiscovery and requirenewinstance is defaulted to the same behavior as connection strings, which have behaved that way since 2017ish. 

I have asked the team to make sure the doc's and intensens reflect the default behavior. 

thanks for your report.
