### ISSUE TITLE
Timeout of ServiceClient

### ISSUE THREAD

**Issue by zsybupt** [microsoft/PowerPlatform-DataverseServiceClient#289]
Hi Team, we have seen some time out of init ServiceClient:

Failed to Executed Command - RetrieveCurrentOrganizationRequest : RequestId=42e3c5f5-780b-4266-95e4-ab2ecfc8df9f : total duration: 00:04:00.0968062
Source: Not Provided
Method: Not Provided
DateUTC: 6/21/2022
TimeUTC: 10:04:24 PM
Error: Failed to Executed Command - RetrieveCurrentOrganizationRequest : RequestId=42e3c5f5-780b-4266-95e4-ab2ecfc8df9f : total duration: 00:04:00.0968062
HelpLink Url: Not Provided
Stack Trace: Not Provided

Seems it takes about 4 minutes to get the organization data, but failed

**Comment by MattB-msft** [comment]
This sort of issue would infer that there is a server side problem.  If your still experiencing this issue, please open a support request with the information you collected here so the issue sever side can be looked at .

**Comment by zsybupt** [comment]
@MattB-msft  Is there a way to set the max execution time out of a request

**Comment by MattB-msft** [comment]
Yes, it can be set during Connection Setup.  there is a static property for it, also you have the ability to set it using the configuration options-based constructor.
