### ISSUE TITLE
Problem with empty option set collection results in index out of range when saving entity

### ISSUE THREAD

**Issue by nicro950** [microsoft/PowerPlatform-DataverseServiceClient#292]
If we tried to save an entity which contained an attribute with and empty OptionSetValueCollection, then we would get an error saying index out of range. We think it has to do with this line of code: 

https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/master/src/GeneralTools/DataverseClient/Client/Utils/Utils.cs#L561 which tries to remove the last comma from the string, but then if there is no values in the collection then it fails since the string is empty. 

Maybe `string.Join(',', optionSetValues.Select(x => x.Value))` would be better to use?

**Comment by MattB-msft** [comment]
Can you provide a sample of what your doing?  are you using Linq? or just an update request?
Once you do that, if you can set UseWebAPI = false, it should get you around this issue for the moment while we look into this. 

Thanks !

**Comment by nicro950** [comment]
We have added an extra property which is an `OptionsSetValueCollection` to the OpportunityType from Dynamics 365 online. The opportunity type is generated by the early bound generator tool. This should be the same for all entities containing an `OptionSetValueCollection`. 

```csharp
var client = scope.ServiceProvider.GetRequiredService<ServiceClient>();
var opty = new Models.Opportunity();
opty.ci_meetinggoal = new OptionSetValueCollection();
client.Create(opty);
```

System.AggregateException: 'One or more errors occurred. (StartIndex cannot be less than zero. (Parameter 'startIndex'))'

This exception was originally thrown at this call stack:
    string.Remove(int)
    Microsoft.PowerPlatform.Dataverse.Client.Utilities.ToExpandoObject(Microsoft.Xrm.Sdk.Entity, Microsoft.PowerPlatform.Dataverse.Client.MetadataUtility, System.Net.Http.HttpMethod, Microsoft.PowerPlatform.Dataverse.Client.DataverseTraceLogger)
    Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.Command_WebAPIProcess_ExecuteAsync(Microsoft.Xrm.Sdk.OrganizationRequest, string, bool, Microsoft.PowerPlatform.Dataverse.Client.MetadataUtility, System.Guid, bool, int, System.TimeSpan, System.Threading.CancellationToken, System.Uri, bool)

We found another workaround by just making sure that all fields which contains an `OptionSetValueCollection` is set to null instead of an empty collection. It was the result of a mapper which mapped an empty collection to an empty `OptionSetValueCollection`.

And from what we could dig up in the code we found this code part which tries to remove the last comma, but if it is an empty collection then it will try and remove the comma from an empty string which result in an exception. 

https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/dfba939dbbfe967c5ef339dfffa70ba41b7196ab/src/GeneralTools/DataverseClient/Client/Utils/Utils.cs#L560-L565

**Comment by MattB-msft** [comment]
Thanks for your report,  

We have affected a change and it will be updated in the next drop. 
Thanks for your report and help tracking down the issue.
