### ISSUE TITLE
Command_WebAPIProcess_ExecuteAsync wipes RowVersion

### ISSUE THREAD

**Issue by dr-consit** [microsoft/PowerPlatform-DataverseServiceClient#296]
In : https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/dfba939dbbfe967c5ef339dfffa70ba41b7196ab/src/GeneralTools/DataverseClient/Client/ConnectionService.cs#L1757

RowVersion is not cloned, this leads to https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/dfba939dbbfe967c5ef339dfffa70ba41b7196ab/src/GeneralTools/DataverseClient/Client/ConnectionService.cs#L1846 always returning false thus https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/dfba939dbbfe967c5ef339dfffa70ba41b7196ab/src/GeneralTools/DataverseClient/Client/ConnectionService.cs#L1864 always throws.

Which also contains a spelling error (then/than).

Which AFAICT makes deletion with optimistic concurrency impossible.

**Comment by MattB-msft** [comment]
Thanks for your report,  Team is having a look at it as part of the current pass.
