### ISSUE TITLE
Use of ExecuteMultipleRequest /UpdateRequest fails but Update does not?

### ISSUE THREAD

**Issue by Steve-Dawkins** [microsoft/PowerPlatform-DataverseServiceClient#299]
We are getting an issue in 1.0.9.

We can call organizationService.Update() just fine but when we use ExecuteMultipleRequest  with UpdateRequest via organizationService.Execute()  we see the following fault:

{Exception details: 
ErrorCode: 0x80041103
Message: 'msnfp_transaction' entity doesn't contain attribute with Name = 'msnfp_DesignationId' and NameMapping = 'Logical'.

Both requests are being performed with the same Entity and the attribute msnfp_DesignationId definetlty exists.

![image](https://user-images.githubusercontent.com/73112535/180231450-ce482ef1-fe35-44b1-a895-ea20e8e1804f.png)

Please advise if this is a know issue

**Comment by MattB-msft** [comment]
use Logical name vs Schema name for the attribute, Logical name is generally ( there are some exceptions ) all lowercase, so msnfp_designationid

**Comment by MattB-msft** [comment]
Please Reopen if that didnt work for you
