### ISSUE TITLE
Linkenties with a one to many relation problem

### ISSUE THREAD

**Issue by danielpastoor** [microsoft/PowerPlatform-DataverseServiceClient#300]
When I use linkentity with a one to many  relation. Then the parent model of the relation is repeated for every relation item. With the only difrence the relation object in attributes.

Example:
{
      "LogicalName": "account",
      "Id": "ed3dd17b-c851-ec11-8c62-000d3abfc415",
      "Attributes": [
        { "Key": "accountid", "Value": "ed3dd17b-c851-ec11-8c62-000d3abfc415" },
        { "Key": "name", "Value": "Puur Chocolade" },
        {
          "Key": "Contacts.parentcustomerid",
          "Value": {
            "AttributeLogicalName": "parentcustomerid",
            "EntityLogicalName": "contact",
            "Value": {
              "Id": "ed3dd17b-c851-ec11-8c62-000d3abfc415",
              "LogicalName": "account",
              "Name": "Puur Chocolade",
              "KeyAttributes": [],
              "RowVersion": null,
              "ExtensionData": {}
            },
            "ExtensionData": {}
          }
        },
        {
          "Key": "Contacts.fullname",
          "Value": {
            "AttributeLogicalName": "fullname",
            "EntityLogicalName": "contact",
            "Value": "Klaas-Anne de Jong",
            "ExtensionData": {}
          }
        }
      ],
    },
    {
      "LogicalName": "account",
      "Id": "ed3dd17b-c851-ec11-8c62-000d3abfc415",
      "Attributes": [
        { "Key": "accountid", "Value": "ed3dd17b-c851-ec11-8c62-000d3abfc415" },
        { "Key": "name", "Value": "Puur Chocolade" },
        {
          "Key": "Contacts.parentcustomerid",
          "Value": {
            "AttributeLogicalName": "parentcustomerid",
            "EntityLogicalName": "contact",
            "Value": {
              "Id": "ed3dd17b-c851-ec11-8c62-000d3abfc415",
              "LogicalName": "account",
              "Name": "Puur Chocolade",
              "KeyAttributes": [],
              "RowVersion": null,
              "ExtensionData": {}
            },
            "ExtensionData": {}
          }
        },
        {
          "Key": "Contacts.fullname",
          "Value": {
            "AttributeLogicalName": "fullname",
            "EntityLogicalName": "contact",
            "Value": "Daniel Pastoor",
            "ExtensionData": {}
          }
        }
      ],
    }

Is it posible to have it like this:
{
      "LogicalName": "account",
      "Id": "ed3dd17b-c851-ec11-8c62-000d3abfc415",
      "Attributes": [
        { "Key": "accountid", "Value": "ed3dd17b-c851-ec11-8c62-000d3abfc415" },
        { "Key": "name", "Value": "Puur Chocolade" },
        {
          "Key": "Contacts.0.parentcustomerid",
          "Value": {
            "AttributeLogicalName": "parentcustomerid",
            "EntityLogicalName": "contact",
            "Value": {
              "Id": "ed3dd17b-c851-ec11-8c62-000d3abfc415",
              "LogicalName": "account",
              "Name": "Puur Chocolade",
              "KeyAttributes": [],
              "RowVersion": null,
              "ExtensionData": {}
            },
            "ExtensionData": {}
          }
        },
        {
          "Key": "Contacts.0.fullname",
          "Value": {
            "AttributeLogicalName": "fullname",
            "EntityLogicalName": "contact",
            "Value": "Daniel Pastoor",
            "ExtensionData": {}
          },
        {
          "Key": "Contacts.1.parentcustomerid",
          "Value": {
            "AttributeLogicalName": "parentcustomerid",
            "EntityLogicalName": "contact",
            "Value": {
              "Id": "ed3dd17b-c851-ec11-8c62-000d3abfc415",
              "LogicalName": "account",
              "Name": "Puur Chocolade",
              "KeyAttributes": [],
              "RowVersion": null,
              "ExtensionData": {}
            },
            "ExtensionData": {}
          }
        },
        {
          "Key": "Contacts.1.fullname",
          "Value": {
            "AttributeLogicalName": "fullname",
            "EntityLogicalName": "contact",
            "Value": "Daniel Pastoor",
            "ExtensionData": {}
          }

        }
      ],
    }

OR:
{
      "LogicalName": "account",
      "Id": "ed3dd17b-c851-ec11-8c62-000d3abfc415",
      "Attributes": [
        { "Key": "accountid", "Value": "ed3dd17b-c851-ec11-8c62-000d3abfc415" },
        { "Key": "name", "Value": "Puur Chocolade" },
        {
          "Key": "Contacts",
          "Value":         [ [{
                  "Key": "parentcustomerid",
                  "Value": {
                    "AttributeLogicalName": "parentcustomerid",
                    "EntityLogicalName": "contact",
                    "Value": {
                      "Id": "ed3dd17b-c851-ec11-8c62-000d3abfc415",
                      "LogicalName": "account",
                      "Name": "Puur Chocolade",
                      "KeyAttributes": [],
                      "RowVersion": null,
                      "ExtensionData": {}
                    },
                    "ExtensionData": {}
                  }
                },
                {
                  "Key": "fullname",
                  "Value": {
                    "AttributeLogicalName": "fullname",
                    "EntityLogicalName": "contact",
                    "Value": "Daniel Pastoor",
                    "ExtensionData": {}
                  }],
                  [
                          {
                      "Key": "parentcustomerid",
                      "Value": {
                        "AttributeLogicalName": "parentcustomerid",
                        "EntityLogicalName": "contact",
                        "Value": {
                          "Id": "ed3dd17b-c851-ec11-8c62-000d3abfc415",
                          "LogicalName": "account",
                          "Name": "Puur Chocolade",
                          "KeyAttributes": [],
                          "RowVersion": null,
                          "ExtensionData": {}
                        },
                        "ExtensionData": {}
                      }
                    },
                    {
                      "Key": "fullname",
                      "Value": {
                        "AttributeLogicalName": "fullname",
                        "EntityLogicalName": "contact",
                        "Value": "Daniel Pastoor",
                        "ExtensionData": {}
                      }
            ]],
          }
        },
        }
      ],
    }

**Comment by MattB-msft** [comment]
Are you asking a general question about the Dataverse WebAPI? or are you asking a question about how the Dataverse ServiceClient is forming the request?

In either case, the format used is what is required by the Dataverse WebAPI.

**Comment by MattB-msft** [comment]
Going to close this up... Please reopen if have a follow up here.
