### ISSUE TITLE
Registering plugins targeting .NET Framework version 4.8

### ISSUE THREAD

**Issue by prasath2k4** [microsoft/PowerPlatform-DataverseServiceClient#301]
Im trying to register D365 Online plugin with latest version of Dataverse SDK and rec'd the error - "This plugin assembly targets version 4.8 of .NET Framework that is not supported. Rebuild this assembly using .NET Framework version 4.7.1 and try again."

![image](https://user-images.githubusercontent.com/7643239/181663776-ae4a6f61-13cb-40b4-b7d1-51f333d87808.png)

Understand that for online, the Dataverse sdk is compatible with .net framework 4.8

online: https://www.nuget.org/packages/Microsoft.PowerPlatform.Dataverse.Client/#supportedframeworks-body-tab

Let me know if the Plugin registration tool will be updated to support reigstration of plugin with net .framework 4.8

**Comment by MattB-msft** [comment]
The plugin framework (server side ) officially only supports 4.6.2 currently,  the dataverse service client is not for use with Plugins at this time.

We are exploring options in the future to move plugin container hosts up from their current .net framework.  
We will make announcements via the PowerPlatform blog as this feature evolves.
