### ISSUE TITLE
New ServiceClient 'hanging' in WPF Application

### ISSUE THREAD

**Issue by JurgenPostelmans** [microsoft/PowerPlatform-DataverseServiceClient#302]
Hi,

I'm trying to create a new ServiceClient object in a WPF app but this just causes the app to hang. I'm using the following code:

string conStr = "...";
ServiceClient service = new ServiceClient(conStr);

The WPF application appears but in stead of popping up a login screen, it just hangs....

It's basically the same problem as in this closed issue:
https://github.com/microsoft/PowerPlatform-DataverseServiceClient/issues/213

If I change my code to something like below it works fine...

 Task t = Task.Run(() => { service = new ServiceClient(conStr); });
 t.ContinueWith(_ => {
                Entity c = new Entity("contact");
                c["firstname"] = "aaa";
                service.Create(c);
            });

Is this the 'expected' behavior or is this a bug?

Thanks,

**Comment by MattB-msft** [comment]
WPF's has a number of specialized rules around UX thread processing. 
By default it backgrounds code execution, so in this case, your Create command is being executed on the 'runtime' thread vs the UX thread, which it would need to be to pop a dialog. 

your Task.Run() bypasses thease rules. 

You can also get a copy of the local dispatcher in wpf and "Invoke" it there. 
for example: 
Application.Current.Dispatcher.Invoke(() =>{ <work here> } which will run this on the UX thread. 

We do have an updated Login Control we plan to provide with this tool set, you can actually find it in this repro, we just have not published the containing nuget package yet.  its here: https://github.com/microsoft/PowerPlatform-DataverseServiceClient/tree/master/src/GeneralTools/DataverseClient/ConnectControl

**Comment by JurgenPostelmans** [comment]
Thanks for the info!
