### ISSUE TITLE
Secured Feilds Not Retrieved when using ExecuteFetchXML or Retrieve

### ISSUE THREAD

**Issue by deepsmehta** [microsoft/PowerPlatform-DataverseServiceClient#303]
When we try to retrieve fields where field level security is enabled, those fields are not returned at all.

**Comment by MattB-msft** [comment]
Depending on the user running the request that is correct behavior for field level security.  FLS is evaluated sever side. 

If it's expected that the calling user should be able to read, I would suggest that you verify the role and group assignments for that user to make sure the users security profile is configured correctly. 

Note FLS rules apply to system admins too.
