### ISSUE TITLE
Getting "Exception - Fault While initializing client - RefreshInstanceDetails" while making connection

### ISSUE THREAD

**Issue by kwu022** [microsoft/PowerPlatform-DataverseServiceClient#307]
I have a set of client Ids and secrets used to connect to D365 from a Function App.

When I try to connect using connection string like: $"AuthType=ClientSecret;url={orgUrl};ClientId={user.clientId};ClientSecret={user.clientSecret};**RequireNewInstance=true**", I got the "Exception - Fault While initializing client - RefreshInstanceDetails" exception, only for **_some client ids_** and rest of them are fine.

If I set RequireNewInstance=**false** in the connection string, all client ids I used can connect without any issues. I've checked AAD, there isn't any difference in the app registrations. Their secrets are all active, all have proper security roles in D365. Just some of the client Ids don't like RequireNewInstance set to true for some strange reasons.

I drilled down to the inner exceptions, and found this exception as well: "The HTTP request was forbidden with client authentication scheme 'Anonymous'."

And the stack trace: 
"   at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateAuthentication()\r\n   at System.ServiceModel.Channels.HttpResponseMessageHelper.<ParseIncomingResponse>d__7.MoveNext()\r\n   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<ReceiveReplyAsync>d__17.MoveNext()\r\n   at System.ServiceModel.Channels.RequestChannel.<RequestAsync>d__33.MoveNext()\r\n   at System.ServiceModel.Channels.RequestChannel.<RequestAsyncInternal>d__32.MoveNext()\r\n   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)\r\n   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)\r\n   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)\r\n   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operati
on)\r\n   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)\r\n   at generatedProxy_1.Execute(OrganizationRequest )\r\n   at Microsoft.PowerPlatform.Dataverse.Client.Connector.WebProxyClientAsync`1.ExecuteAction[TResult](Func`1 action)\r\n   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.<RefreshInstanceDetails>d__189.MoveNext()"
    TargetSite: {Void ValidateAuthentication()}
ex.InnerException.InnerException.InnerException.InnerException.StackTrace
"   at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateAuthentication()\r\n   at System.ServiceModel.Channels.HttpResponseMessageHelper.ParseIncomingResponse(TimeoutHelper timeoutHelper)\r\n   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.ReceiveReplyAsync(TimeoutHelper timeoutHelper)\r\n   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)\r\n   at System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout)\r\n   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)\r\n   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)\r\n   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)\r\n   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall 
methodCall, ProxyOperationRuntime operation)\r\n   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)\r\n   at generatedProxy_1.Execute(OrganizationRequest )\r\n   at Microsoft.PowerPlatform.Dataverse.Client.Connector.WebProxyClientAsync`1.ExecuteAction[TResult](Func`1 action)\r\n   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.RefreshInstanceDetails(IOrganizationService dvService, Uri uriOfInstance)"

**Comment by MattB-msft** [comment]
Connection strings, by default, Set RequireNewInstance = false.  
RequireNewInstance tells the client to reuse the in memory version of the connection, in this case it would be the first instance of the connection ever created.  

If you create the initial connection with AppID 123,  then create a new connection passing RequiredNewInstance = False and AppID 465,  it will fail to connect.   This is because the connection its trying to use was created with AppID 123.

if your going to be switching between AppID's and or Endpoints, you should not set RequireNewInstance at all.  If you need to cache the connections, you should use a URL centric client caching mechanic, where you are keeping a connection per instance.
