### ISSUE TITLE
Question on the DataverseService Client Sdk

### ISSUE THREAD

**Issue by thye1997** [microsoft/PowerPlatform-DataverseServiceClient#310]
My team has started a new project using .net 6.0 to connect to our online dynamics 365. we have come across the recommended sdk to use is Microsoft.PowerPlatform.Dataverse.Client. However, when i try to use it i hit the error 
![image](https://user-images.githubusercontent.com/53056194/188262184-95cd91f6-b2b8-4f83-aa1c-fd34fce7a5a1.png)
Does the library is not usable in the .net 6.0 framework?

**Comment by MattB-msft** [comment]
The client is fully supported and working on .net 6. It is also actively tested on .net 6.   

The error you reported is cut off and an aggregate error,  what is the full error and other errors?   

Also you should not include anything from the Microsoft.crmsdk.* nuget packages in a .net 6 project.

**Comment by thye1997** [comment]
Oh ok, i actually included the crmsdk in my project and now after i removed it, it actually does not trigger the error. Thanks. Just one quick question, i see the news https://community.dynamics.com/365/f/dynamics-365-general-forum/459368/how-to-use-solution-checker-to-identify-usage-of-the-organizationdata-svc-endpoint-which-is-planned-for-retirement-in-november-2022
about the deprecation of the organizationdata.svc. May i know would it impact this dataverse client sdk or it is safe to continue use it?

**Comment by MattB-msft** [comment]
This client is safe to use.

**Comment by thye1997** [comment]
Between IOrganizationService/OrganizationServiceContext, and ServiceClient, which one is more recommended to use?
