### ISSUE TITLE
Memory leak caused by exception thrown when constructing ServiceClient

### ISSUE THREAD

**Issue by zhaohangChen** [microsoft/PowerPlatform-DataverseServiceClient#322]
Hi team, 
We observe there is memory leak when our sevice is using Microsoft.PowerPlatform.Dataverse.Client.ServiceClient. 
When we call the constructor of Microsoft.PowerPlatform.Dataverse.Client.ServiceClient, if it throws exception, its member `DataverseTraceLogger` which is Disposable won't be disposed. That cause a sever memory leak in our service when it runs for some time.

Can we enhance the logic or provide some guaidance to avoid this? It's hard for our service to prevent the exception before invoking the ctor(). Also when the exception is thrown, even if we catch it, we can't dispose the object since no reference would be returned.

**Comment by zhaohangChen** [comment]
As discussed internally with @Matthew, there is a workaround for this problem:
Use the Connection Settings Constructor with deferred activation instead of the Constructor which do the activation inside and lead to the memory leak issue.
An example of changed code:
![image](https://user-images.githubusercontent.com/109334500/195739566-9c5386c1-9fbd-4060-9e4c-331a6b694b8d.png)

**Comment by MattB-msft** [comment]
We have a fix queued for this which will be in the next drop.
