### ISSUE TITLE
Org

### ISSUE THREAD

**Issue by naushers** [microsoft/PowerPlatform-DataverseServiceClient#337]
Dear Team,

When we are consuming DataverseService Client with D365 instance for CRUD operation, we found internally it is using 2011 WCF services of Dynamics 365 which was depreciated by Microsoft for a long time. I am attaching the screenshot of Application insights which clearly shows the WCF service URL.

Would you please clarify the same?

Thanks,
Nausher

URL: https://xxx.crm.dynamics.com:443/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.47.11043
 
![WCF Service](https://user-images.githubusercontent.com/118335192/202106642-75dc9c69-ea8d-420a-b1be-22cd1a595670.PNG)

**Comment by MattB-msft** [comment]
@naushers Thanks for your question. 

We have deprecated and will continue to phase out **external use** of the WCF endpoint.  
This specifically means developers that are trying to integrate with the SOAP contract without using the CrmServiceClient or the Dataverse ServiceClient.   

We will at some point block access to it by clients other then CrmServiceClient and Dataverse ServiceClient, but have yet to announce a date on this. 

If you'r using the CrmServiceClient or Dataverse ServiceClient you are 'safe' as we will continue to manage the wire protocol to meet the needs of the SDK clients.  As it changes, the clients will be updated to support it. 

If you are using the SOAP Endpoint directly, not using our clients, you should transition off direct use of the SOAP Protocol to the WebAPI (OData 4.0 Standard).

**Comment by naushers** [comment]
Thank you for your update.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
