### ISSUE TITLE
Invocation of ServiceClient ---> System.IO.FileNotFoundException: 'Could not load file or assembly 'System.ServiceModel, Version=4.0.0.0

### ISSUE THREAD

**Issue by thyme51** [microsoft/PowerPlatform-DataverseServiceClient#338]
My client is running on-prem CRM 9.0. They are moving to dynamics.com during 12-18 months.
Meanwhile, we are modernizing their application portfolio and moving from MSMQ to Azure Service Bus by using Azure functions triggered by subscriptions to topics.

Due to CRM 9.0 restrictions, we must stick to AD-auth and .NETFx 4.8. Therefore the function code is built using NetFx48.

When we execute
`
ServiceClient onPremAD = new ServiceClient(connectionString);
`
we get a run time error. 

`System.IO.FileNotFoundException: 'Could not load file or assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.'
`
Running the same code in a plain console application NetFx4.8 works perfect 
('app.dataverse.connection.test.exe' (CLR v4.0.30319: dk.gi.app.dataverse.connection.test.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Channels\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Channels.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.)

Our code looks like
```
[FunctionName("EkkoUserIDTilIncomingQueue")]
        [return: ServiceBus("incoming", Connection = "ServiceBusConnection")]
        public static string RunEkkoUserID([ServiceBusTrigger(crmtopicName, crmsubscriptionName, Connection = "ServiceBusConnection")]
            string mySbMsg, ILogger log)
        {
            log.LogInformation($"Entry for opslagafCRMUserIDB");

            string userId = MakeCallToCRM();
            return $"Userid for {mySbMsg} er {userId}";

        }

        public static string MakeCallToCRM()
        {
            // Settings must be moved to Azure somewhere
            string CrmConnectionTemplate = "Url=https://{0}/;AuthType=AD;Username={1};Password={2};Domain=gisb";
            string CrmServerName = "xxxx.xx.dk";
            string CrmUserName = "xxxx@xxx.dk";
            string CrmUserPassword = "password";

            // CRM Need NuGet package: Microsoft.PowerPlatform.Dataverse.Client.Dynamics (Must use .Net Framework)
            Console.WriteLine("Creating OnPremiseClient");
            // Create a Dataverse service client using the default connection string.
            string connectionString = string.Format(CrmConnectionTemplate, CrmServerName, CrmUserName, CrmUserPassword);
            try
            {
                ServiceClient onPremAD = new ServiceClient(connectionString);
                onPremAD.UseWebApi = false;

                Console.WriteLine(onPremAD.ConnectedOrgVersion.ToString());
                // Send a WhoAmI message request to the Organization service to obtain information about the logged on user.
                WhoAmIResponse resp = (WhoAmIResponse)onPremAD.Execute(new WhoAmIRequest());
                return resp.UserId.ToString();
            }
            catch (Exception e)
            {
                return e.Message;
            }
        }```

I hope this make sense to you

Thanks Jørgen

**Comment by MattB-msft** [comment]
Which function host version are you using? 
The inference there is that the function host is trying to run it as a .net 6.0 app ( which partly supports some of the features of .net 4.x ) 

It could also be a binding redirection issue on the functions host. 
Can you run it in your local functions test harness?

**Comment by thyme51** [comment]
Thanks - we moved the code to an isolated host ( "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",) and a 4.8 project.
It works perfect locally and on my Function App in Azure.

PS: I had to update Azure Functions SDK (Tools->Options.....) although the UI did not advise but that button had a "repair" behavior :-) - now we can debug locally

**Comment by thyme51** [comment]
I'll close the issue
