### ISSUE TITLE
Avoid error logging during throttling / transient error handling

### ISSUE THREAD

**Issue by cluise1** [microsoft/PowerPlatform-DataverseServiceClient#342]
Hello,

The issue with current implementation throttling / transient error handling is, that it logs exception at with ERROR severity during retry attempt:

https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/b483aee3feb4cd79095764e7c59131393b62c6d2/src/GeneralTools/DataverseClient/Client/Utils/Utils.cs#L430

This leads to misinterpretation, when human log reader is under impression that some operation has failed, but in reality it has succeeded (later). E.g.: 

```
2022-11-29 10:53:14,272 ERROR Service - - 5 - Failed to Execute Command - RetrieveMultiple : RequestID=e90cca4d-1ded-46ea-9127-53151a960eeb : RetrieveMultiple to Dataverse via IOrganizationService duration=00:00:00.8582878 ExceptionMessage = Combined execution time of incoming requests exceeded limit of 1200000 milliseconds over time window of 300 seconds. Decrease number of concurrent requests or reduce the duration of requests and try again later.
Source: System.Private.ServiceModel
Method: HandleReply
DateUTC: 11/29/2022
TimeUTC: 9:53:14 AM
Error: Message: Combined execution time of incoming requests exceeded limit of 1200000 milliseconds over time window of 300 seconds. Decrease number of concurrent requests or reduce the duration of requests and try again later.
ErrorCode: -2147015903
ActivityId: af728d7c-06f1-4572-a4ed-0700b08ad658
Trace: 
Error Details	:
Retry-After	: 00:00:15.3650000
HelpLink Url: Not Provided
Stack Trace: .. (trimmed)
2022-11-29 10:53:14,274 WARN Service - - 5 - Retry No=1 Retry=Started IsThrottle=True Delay=00:00:06 for Command RetrieveMultiple
```

At the moment we have to rely on parsing and filtering out the error message.

Proposals:

1. Lower log severity (INFO, DEBUG?) for errors that are to be retried
2. Swap order of WARN and ERROR message -> at `ILogger` implementation, it will be possible change log level for following error message. 
3. Or introduce more complex control over this ..

Thank you

**Comment by cluise1** [comment]
Hello,

I'm closing this issue, I have find a way how to change severity at via `ILogger` wrapper.

```
public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
{
	if (exception is FaultException<Microsoft.Xrm.Sdk.OrganizationServiceFault> { Detail.ErrorCode: -2147015903 })
	{
		// do whatever needed with throttling log entry
	}
}
```

**Comment by fowl2** [comment]
@cluise1 I feel this would be a worthwhile improvement so we don't all have to implement that workaround, would you mind reopening it?

**Comment by MattB-msft** [comment]
To clarify the concern here, Is that the reported error from DV is an Error and not a warning., as if you look at the top of the stack, the client is reporting it as a warning, with the child exceptions being raised as errors.

**Comment by MattB-msft** [comment]
Going to close up this. The DVSC reports throttling as Warnings.. if your seeing them reported as errors, please reopen with an error stack where we can see what your seeing. 

Note: the HTTP Stack ( if your monitoring the network flow ) will show it as a failure, (429 error ).
