### ISSUE TITLE
PowerShell Wrapper

### ISSUE THREAD

**Issue by iangwilliams** [microsoft/PowerPlatform-DataverseServiceClient#344]
When there will be a PowerShell wrapper for the PowePlatform-DataverseServiceClient?
Currently using Microsoft.Xrm.Tooling.CrmConnector.PowerShell which uses ADAL hence the need for the above.
The Xrm.Tooling.CrmConnector has no project here on GitHub for me to ask there.

Thanks

**Comment by MattB-msft** [comment]
It's on the 'to-do list'.   

Which is to say once we can free a dev to take care of porting and splitting it from our main build tree for Git, we will do the port for PowerShell Core. 
No solid ETA right now, 
Im sorry.
