### ISSUE TITLE
CreateAndReturnAsync is not implemented

### ISSUE THREAD

**Issue by Wesslan92** [microsoft/PowerPlatform-DataverseServiceClient#347]
The method CreateAndReturnAsync exists, but is not implemented and throws a NotImplementedException.

This is confusing as there is no indication for this in the official [documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.powerplatform.dataverse.client.serviceclient.createandreturnasync?view=dataverse-sdk-latest). This results in an assumption that it is implemented.

When I got the exception I assumed the issue was on my side, in the end I decided to check the source code, but this was one of the later things I did. This resulted in a lot of wasted time as I trust that the NuGet is correctly implemented.

**Comment by Misiu** [comment]
This is possible with WebAPI: https://learn.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/gg328090(v=crm.8)#create-with-data-returned
But I also would like to have it here.
I've fixed the interface and added another not implemented method, but I'm not sure how to proceed with this.

According to the docs I can't even build this project, so not sure how can I contribute, ref: https://github.com/microsoft/PowerPlatform-DataverseServiceClient#overview

**Comment by Wesslan92** [comment]
> This is possible with WebAPI: https://learn.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/gg328090(v=crm.8)#create-with-data-returned 

Okay, I have simply implemented a second call and use the regular CreateAsync method which returns the GUID which I then use to query the RetrieveAsync method. So, there is nothing blocking me, although it would be nice to have that method natively, but there is no critical need for it.

For me the biggest problem is that it is shown in documentation and all and does not work. Would be good to at least have it removed from the documentation while it is being implemented to not cause unnecessary confusion until it is implemented.

**Comment by Misiu** [comment]
@Wesslan92 https://github.com/microsoft/PowerPlatform-DataverseServiceClient/issues/348#issuecomment-1384301862
