### ISSUE TITLE
COE dashboard is showing dataverse error

### ISSUE THREAD

**Issue by kishvel77** [microsoft/PowerPlatform-DataverseServiceClient#351]
Data source error: Expression.Error: A join operation cannot result in a table with duplicate column names ("<ccon>owningbusinessunitname").. </ccon>. The exception was raised by the IDbCommand interface. Table: App Connection Reference.
Cluster URI: WABI-US-NORTH-CENTRAL-G-PRIMARY-redirect.analysis.windows.net
Activity ID: 824806ab-0ea0-473b-822f-208e22ea266f
Request ID: 5d4d0d65-24d0-fa76-6a84-305c7fa5d1c9
Time: 2023-02-01 15:41:48Z

**Comment by MattB-msft** [comment]
COE toolkit issues should be posted to their git hub... you can find that here: https://github.com/microsoft/coe-starter-kit
