### ISSUE TITLE
GetOrgnameAndOnlineRegionFromServiceUri or alternative?

### ISSUE THREAD

**Issue by bo-stig-christensen** [microsoft/PowerPlatform-DataverseServiceClient#352]
I am working on an upgrade for a D365 deployment framework in order to ditch the now not supported ADAL that is utilized by the older Microsoft.Xrm.Tooling.Connector library. - This means a complete upgrade to the latest Dataverse SDK (Microsoft.PowerPlatform.DataVerse.Client).

All good and it seems as if it will be relatively easy.... if not for this bastard: _Microsoft.Xrm.Tooling.Connector.Utilities.**GetOrgnameAndOnlineRegionFromServiceUri**(serviceUri, out onlineRegion, organizationName, isOnPrem)_

I reverse-engineered it and the logic is also relatively easy to re-implement, but I'd rather not ;-)

Is there anything like this in the new SDK? or somewhere else? or has it just been forgotten? ;-)
I'd hate to keep using it from the old SDK as it will put dependencies on the old ADAL libraries.

**Comment by MattB-msft** [comment]
The code is still present but was taken internal as there are future updates that will likely alter how this is done. 
it can be found here: https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/b483aee3feb4cd79095764e7c59131393b62c6d2/src/GeneralTools/DataverseClient/Client/Utils/Utils.cs#L57

It was built to support our login controls only, 
What are you trying to use it for, as that information may be available elsewhere.

**Comment by MattB-msft** [comment]
Closing this thread as there has been no feedback,
