### ISSUE TITLE
Method not found: ConfigurePrimaryHttpMessageHandler

### ISSUE THREAD

**Issue by brianhearn** [microsoft/PowerPlatform-DataverseServiceClient#353]
Using the default 3.1.8 and latest 7.0.0 dependencies, managed entirely using NuGet, for V1.0.26, I cannot instantiate a new ServiceClient without throwing:

Method not found: 'Microsoft.Extensions.DependencyInjection.IHttpClientBuilder Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.ConfigurePrimaryHttpMessageHandler(Microsoft.Extensions.DependencyInjection.IHttpClientBuilder, System.Func`1<System.Net.Http.HttpMessageHandler>)'.

**Comment by MattB-msft** [comment]
Not following your question, 
are you saying you bumped up Microsoft.Extensions.DependencyInjection to from 3.1.8 to 7.0.0 and are seeing this failure?

**Comment by brianhearn** [comment]
I am seeing the issue on a fresh load with the dependencies at 3.1.8 and when I upgrade Microsoft.Extensions.DependencyInjection to from 3.1.8 to 7.0.0.

**Comment by brianhearn** [comment]
You can see my NuGet versioning here: 
<dependentAssembly>
    
            <assemblyIdentity name="Microsoft.IdentityModel.Protocols.OpenIdConnect" publicKeyToken="31bf3856ad364e35" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-6.26.1.0" newVersion="6.26.1.0" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-4.1.1.3" newVersion="4.1.1.3" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="Microsoft.IdentityModel.Tokens" publicKeyToken="31bf3856ad364e35" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-6.26.1.0" newVersion="6.26.1.0" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="System.IdentityModel.Tokens.Jwt" publicKeyToken="31bf3856ad364e35" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-6.26.1.0" newVersion="6.26.1.0" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="Microsoft.IdentityModel.Protocols" publicKeyToken="31bf3856ad364e35" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-6.26.1.0" newVersion="6.26.1.0" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="Microsoft.IdentityModel.Abstractions" publicKeyToken="31bf3856ad364e35" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-6.26.1.0" newVersion="6.26.1.0" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-4.0.1.2" newVersion="4.0.1.2" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="System.Text.Json" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.2" newVersion="7.0.0.2" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-13.0.0.0" newVersion="13.0.0.0" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="Microsoft.Identity.Client" publicKeyToken="0a613f4dd989e8ae" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-4.50.0.0" newVersion="4.50.0.0" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="Microsoft.Extensions.Caching.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="Microsoft.Extensions.Options" publicKeyToken="adb9793829ddae60" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.1" newVersion="7.0.0.1" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="Microsoft.Extensions.Logging.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="Microsoft.Extensions.DependencyInjection.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="Microsoft.Extensions.Http" publicKeyToken="adb9793829ddae60" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="Microsoft.Identity.Client.Extensions.Msal" publicKeyToken="0a613f4dd989e8ae" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-2.26.0.0" newVersion="2.26.0.0" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="Microsoft.Extensions.Caching.Memory" publicKeyToken="adb9793829ddae60" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="Microsoft.Extensions.DependencyInjection" publicKeyToken="adb9793829ddae60" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
    
        </dependentAssembly>
    
        <dependentAssembly>
    
            <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
    
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.1" newVersion="7.0.0.1" />
    
        </dependentAssembly>

**Comment by MattB-msft** [comment]
We are looking into this,  
thanks for the report.

**Comment by brianhearn** [comment]
Just pinging...any news?

**Comment by MattB-msft** [comment]
@brianhearn 
Sorry for the delay in responding... 
We tried to replicate this issue using a console app + upgrading the DI system to 7.x on a .net 6 and 7 target w/out issues. 
As the base tests do not seem to be complaining it could be another dependency,  

Could you tell us more about your configuration / how you have setup your project? 

thanks
MattB.

**Comment by brianhearn** [comment]
It may have something to do with my solution also has dependencies to the OWIN framework?

Here's a stack trace on the error:
   at Microsoft.PowerPlatform.Dataverse.Client.Utils.ClientServiceProviders.BindServiceProviders()
   at Microsoft.PowerPlatform.Dataverse.Client.Utils.ClientServiceProviders.get_Instance()
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient..ctor(Uri instanceUrl, Func`2 tokenProviderFunction, Boolean useUniqueInstance, ILogger logger)
   at CrmRest.Service.GetOrgServiceInstance(String userId, String pwd, String idToken) in E:\Projects\EasyTerritory\OpenIntel\REST\Service.cs:line 218
   at CrmRest.Service.QueryUsingFetchXml(FetchXmlRequest request) in E:\Projects\EasyTerritory\OpenIntel\REST\Service.cs:line 295

**Comment by brianhearn** [comment]
Okay, I got the issue resolved. I had another version of System.Net.Http added from nuget to support OWIN. Once I removed that dependency, the exception in Microsoft.PowerPlatform.Dataverse stopped.

**Comment by MattB-msft** [comment]
Thanks @brianhearn Can you give us a bit more detail on that?  Which version of the System.Net.Http package was causing this?

We would like to see if we can detect it in the future and provide a more meaningful error.

**Comment by MattB-msft** [comment]
Going to resolve this at this point as this was a dependency issue in the host code.
