### ISSUE TITLE
Throttling Issue Encountered while accessing Dataverse

### ISSUE THREAD

**Issue by otep-kunnn** [microsoft/PowerPlatform-DataverseServiceClient#358]
We would like to ask your assistance with a throttling issue that we are having while doing some calls to our Dataverse using the Microsoft.PowerPlatform.Dataverse.Client NuGet. Can you assist/guide us here?

**Comment by otep-kunnn** [comment]
Hi, 

Thank you for your response! We tried some of the suggestions from various links and articles (including the one that you've sent) but we still have the same error stack.

![MicrosoftTeams-image (30)](https://user-images.githubusercontent.com/127529355/225070441-463e03bd-5ee7-48fa-84fc-25545ec12d0f.png)

Maybe a bit of context on our current implementation: we actually upgraded our solution (Azure WebJob) from .NETFramework 4.8 to .NET 6.0. Initially, we are using NuGet package which uses the CrmClient (Microsoft.CrmSdk.CoreAssemblies). But since this doesn't seem to be compatible with .NET 6.0, we used the Microsoft.PowerPlatform.Dataverse.Client NuGet instead. We have implemented the ServiceClient as follows:

![MicrosoftTeams-image (31)](https://user-images.githubusercontent.com/127529355/225077714-80a46565-9af4-44ce-85c6-d8085d86bc03.png)

The CRM connection string defines the user that we are using to access the environment with AuthType set to OAuth. Anyway, this solution is triggered whenever an event is pushed to a service bus, is initiated daily and by batch and can finish processing from 1 second to 2 hours, depending on how many records are fetched in the CRM environment.

We tried setting `ServicePointManager.DefaultConnectionLimit = 65000` and `sbOptions.MaxConcurrentCalls = 4` to slow down the amount of incoming events (with the hope to alleviate the throttling). However, neither worked.

Based on the stack trace, we see that the error occurs on this line and not during retrieving of data.
`_crmClient = new ServiceClient(_connectionString)`

Can you advise us what further actions can we take to resolve the issue that we are encountering. If needed, you can also direct us with the support that you are referring to.

Looking forward to your response! Thank you.

**Comment by MattB-msft** [comment]
@otep-kunnn 

You are being throttled by AAD, not by dataverse. 
Are you creating and deleteing the ServiceClient per Request?  or are you keeping it alive to process all of your requests? 
also you said your using a User Auth flow vs a S2S app.  if your using a connection string for userAuth Flow, did you set TokenCachePath ?

**Comment by MattB-msft** [comment]
The format for the token cache should be this: C:\\home\\data\\jobs\\continuous\\{{WebJobName}}\\MyTokenCache**\\token.dat**
And unless your using different logins per webJob, you do not need to have a webJob specific folder. 

In general, though, your performance for this type of operation will be better using an S2S authentication flow vs a User/interactive authentication flow. 

User Interacitve tokens are not cached unless you have provided a proper token cache path + file name, and MSAL does not have good internal caching logic, unlike ADAL which did that pretty well. 

Thus, what is happening is for each request is that it is trying to go to AAD to get a new token for the user.
This is causing AAD to throttle you.

**Comment by otep-kunnn** [comment]
Hello @MattB-msft ,

Thank you again for your feedback!

Just an update from our end, we tried to adjust the token cache according to your suggestion and deployed our change.

`AuthType=OAuth; Url={{xxx.crm4.dynamics.com}}; Username={{username}}; Password={{password}}; RedirectUri=http://localhost; LoginPrompt=Never;TokenCacheStorePath=C:\\home\\data\\jobs\\continuous\\{{WebJobName}}\\MyTokenCache\\token.dat";`

From the Kudu Debug Console, we can see that the folder "MyTokenCache" was created. However, there are no files inside and we still encounter the same error. 

Additionally, we noticed that we did not encounter the error when we locally run the solution and added the TokenCacheStorePath in the connection string. The "token.dat" file was added and gets updated after starting the WebJob. Do you know what might have been the reason why it works locally but not when deployed?

Moreover, since we didn't do much of a change on the way we are connecting on the CRM environments (only migrating from CrmClient to ServiceClient and updated the old CRM methods to their counterparts in the ServiceClient), can you tell us what's the difference between the CrmClient and the ServiceClient (especially in terms on how they are authenticating in the AAD)?

Again, we will be looking forward to your response. Thank you!

**Comment by otep-kunnn** [comment]
Hi @MattB-msft 

Thank you for your continuous help.
We tried the client secret authentication but we are getting the following error:

`System.ServiceModel.Security.MessageSecurityException: The HTTP request was forbidden with client authentication scheme 'Anonymous'.`

We are using the below connection string for authentication:
`"AuthType=ClientSecret; Url={opCoSecretName}; ClientId={appId}; ClientSecret={secret}"`

Can you kindly point us in the correct way to use this?
Thank you and looking forward again to your response.

**Comment by MattB-msft** [comment]
@otep-kunnn  were you able to get though this? or do you still need help?

**Comment by otep-kunnn** [comment]
Hi @MattB-msft and @BetimBeja ,

Apologies on the late response on this issue.
Our application is now working as expected after using the S2S Authentication Flow and adding App Registrations & Application Users on our CRM Environments. 

Many thanks to all of your support and for your patience in answering my inquiries!
Until next time!
