### ISSUE TITLE
ResetLastError methods does not work

### ISSUE THREAD

**Issue by 1-Accelerator-1** [microsoft/PowerPlatform-DataverseServiceClient#359]
https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/b483aee3feb4cd79095764e7c59131393b62c6d2/src/GeneralTools/DataverseClient/ConnectControl/Utility/LoginTracer.cs#L58-L62

https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/b483aee3feb4cd79095764e7c59131393b62c6d2/src/GeneralTools/DataverseClient/WebResourceUtility/TraceLogger.cs#L49-L53

String is immutable. When you delete the LastError field, it is not deleted, but a new line is created in which there are no characters, that is, an empty string. To fix this, you must return the result of the Remove method in the LastError field.

LastError = LastError.Remove(0, LastError.Length - 1);

**Comment by MattB-msft** [comment]
This will be fixed in the next drop for Dataverse Service Client.
