### ISSUE TITLE
Failed to clone connection with latest package 1.0.39

### ISSUE THREAD

**Issue by chironh** [microsoft/PowerPlatform-DataverseServiceClient#362]
Works with previous packages (reverting back to 1.0.26 resolves the problem). Works locally, but not in an Azure Function.

Nothing too fancy:

`            
Parallel.ForEach(
                batches,
                new ParallelOptions()
                {
                    MaxDegreeOfParallelism = service.RecommendedDegreesOfParallelism
                },
                () =>
                {
                    return service.Clone();
                },
                (batch, loopstate, index, threadLocalSvc) =>
                {
`

Seems this exception is being thrown:
https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/44a1af6fca8e9b3ec806d2322fbceab332b3164e/src/GeneralTools/DataverseClient/Client/ServiceClient.cs#L1403

**Comment by MattB-msft** [comment]
Can you provide the actual exception being thrown? 

Discovery is not used during clone, 

Also, if your running on .net 6+ , we have altered our guidance on how to use parallel for each, please see here: https://learn.microsoft.com/en-us/power-apps/developer/data-platform/send-parallel-requests?tabs=sdk#using-serviceclient-with-net-6-or-higher

That said it should still work the way you trying to use it.

**Comment by dmognaschi** [comment]
The root cause of the issue is that with 1.0.39, if you Clone() the instance before having used the service, the method fails with an invalid object reference exception.

As a workaround, to prevent the issue, make sure to use the service (i.e. you can execute a WhoAmIRequest()) before Clone() it.

**Comment by MattB-msft** [comment]
We were able to locate this issue,  
We have fix coming for it in the next update. 

As a workaround, you can call "GetMyUserId" ( in .extensions ) before you start cloning.  
That will resolve the issue in the .39 client.

**Comment by chironh** [comment]
Thanks! I totally forgot to check this thread again, my bad :)
