### ISSUE TITLE
Connection to Dataverse - thread is just stuck

### ISSUE THREAD

**Issue by maxpaj** [microsoft/PowerPlatform-DataverseServiceClient#366]
Hello,

Thank you for developing this!

I'm trying to connect to Dataverse using AuthType ClientSecret, and this is what I'm seeing in my log:

```17:15:31:302	2023-03-23 17:15:31.1764|DEBUG|Initialize Dataverse connection Started - AuthType: ClientSecret
17:15:31:302	2023-03-23 17:15:31.1764|DEBUG|Direct Login Process Started
17:15:31:302	2023-03-23 17:15:31.1764|INFO|Attempting to Connect to Uri https://<organization>.crm4.dynamics.com/XRMServices/2011/Organization.svc
17:15:31:302	2023-03-23 17:15:31.1764|DEBUG|DiscoveryServer indicated organization service location = https://<organization>.crm4.dynamics.com/XRMServices/2011/Organization.svc
17:15:31:302	2023-03-23 17:15:31.1764|INFO|Organization Service URI is 'https://<organization>.crm4.dynamics.com/XRMServices/2011/Organization.svc'
17:15:31:302	2023-03-23 17:15:31.1764|DEBUG|ConnectAndInitService - Initializing Organization Service Object
17:15:31:302	2023-03-23 17:15:31.1764|INFO|ConnectAndInitService - Requesting connection to Organization with Dataverse Version: No organization data available
17:15:31:564	2023-03-23 17:15:31.5084|INFO|AuthenticateService - found authority with name https://login.microsoftonline.com/<tenant ID>/
17:15:31:564	2023-03-23 17:15:31.5084|INFO|AuthenticateService - found resource with name https://my-dynamics.crm4.dynamics.com/
17:15:46:553	The thread 0x4890 has exited with code 0 (0x0).
```

Seems like the thread just freezes. I see nothing else logged. 

What am I doing wrong? How can I debug this?

According to this article (https://learn.microsoft.com/en-us/power-apps/developer/data-platform/sdk-client-transition) if I continue using `Microsoft.CrmSdk.XrmTooling`, eventually ADAL authentication will be deprecated, and my app will stop working. Is this correct?

**Comment by MattB-msft** [comment]
Could you provide a bit more context, 
from the Log, it looks like your using Azure functions.  ( though that could be an asp.net site too. ) 
Which version of the Client are you using?
What OS/.net version are you using, 
How are you initializing that? ( IE if its a function, where are you creating the connection ) 

The symptom your seeing is a deferred startup problem that is known in some services where an async operation is blocked during service startup.  There are several ways to deal with it,  but would need to know more about the context to offer guidance.

**Comment by maxpaj** [comment]
**The issue was, I had switched from using a connection string to using a more explicit constructor, and had not supplied the client secret. There was no validation error for this, though.**


This is an old MVC project, with some API controllers, using .NET Framework 4.7.2. 

I run it in IISExpress on my local machine. 

OS is Windows 11. 

I initialize the connection in the constructor of my wrapper service.

```
public DynamicsService(IConfigurationProvider configurationProvider, ILogger<DynamicsService> logger)
{
    var connString = configurationProvider.GetConfigurationName("DynamicsConnectionString");

    logger.LogInformation("Start connection to dataverse!");

    try
    {
        _dataverseServiceClient = new ServiceClient(
            new ConnectionOptions { 
                ServiceUri = new Uri(connString["Url"]), 
                ClientSecret = connString["ClientSecret"], 
                ClientId = connString["ClientId"],
                Logger = logger, 
                AuthenticationType = connString["AuthType"]
            },
            false,
            new ConfigurationOptions { 
                MaxRetryCount = 1, 
                RetryPauseTime = TimeSpan.FromSeconds(1), 
                MSALRequestTimeout = TimeSpan.FromSeconds(1),
                MSALEnabledLogPII = true, 
                MSALRetryCount = 0 
        });
        logger.LogInformation("Finished connection to dataverse!");
    }
    catch (Exception e)
    {
        logger.LogError(e.Message);
    }
}
```
