### ISSUE TITLE
Intermittent connection error when using Microsoft.PowerPlatform.Dataverse.Client.ServiceClient

### ISSUE THREAD

**Issue by rsaclee** [microsoft/PowerPlatform-DataverseServiceClient#368]
We are experience the following issue. 
We used SDK to connect to CRM on cloud. Per Microsoft recommendation, we replace ADAL auth with Microsoft.PowerPlatform.Dataverse.Client. .NET application is running on framework 4.7.2. We did not get any error when doing unit testing in our test environment. However, after we deployed the application to our production with higher volume of transactions (we load more than 1/2 million of records daily), then we got the following error

Exception Message:
Failed to connect to Dataverse
StackTrace:
at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.CreateServiceConnection(Object externalOrgServiceProxy, AuthenticationType requestedAuthType, String hostName, String port, String orgName, NetworkCredential credential, String userId, SecureString password, String domain, String Geo, String claimsHomeRealm, Boolean useSsl, Boolean useUniqueInstance, OrganizationDetail orgDetail, String clientId, Uri redirectUri, PromptBehavior promptBehavior, OrganizationWebProxyClientAsync externalOrgWebProxyClient, String certificateThumbPrint, StoreName certificateStoreName, X509Certificate2 certificate, Uri instanceUrl, Boolean isCloned, Boolean useDefaultCreds, Version incomingOrgVersion, ILogger externalLogger, String tokenCacheStorePath)
at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient..ctor(Uri instanceUrl, String clientId, String clientSecret, Boolean useUniqueInstance, ILogger logger)

Inner Message:
One or more errors occurred.
Inner StackTrace:
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task1.get_Result()
at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.GetCachedService(ConnectionService& ConnectionObject)
at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.IntilizeService(ConnectionService& ConnectionObject)
at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.DoLogin(ConnectionService& ConnectionObject)
at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.CreateServiceConnection(Object externalOrgServiceProxy, AuthenticationType requestedAuthType, String hostName, String port, String orgName, NetworkCredential credential, String userId, SecureString password, String domain, String Geo, String claimsHomeRealm, Boolean useSsl, Boolean useUniqueInstance, OrganizationDetail orgDetail, String clientId, Uri redirectUri, PromptBehavior promptBehavior, OrganizationWebProxyClientAsync externalOrgWebProxyClient, String certificateThumbPrint, StoreName certificateStoreName, X509Certificate2 certificate, Uri instanceUrl, Boolean isCloned, Boolean useDefaultCreds, Version incomingOrgVersion, ILogger externalLogger, String tokenCacheStorePath)

After rolling back the changes to use Microsoft.Xrm.Tooling.Connector with ADAL, the error is gone.

Any help or comment for trouble shooting is appreciated.

**Comment by MattB-msft** [comment]
There is not a lot to go on there,  
When you say you migrated from SDK to Service Client, what were you using before? CrmServiceClient ? or lower level Xrm OrganizationWebProxy? 

What sort of authentication flow are you using here?  
Are you using the ServiceClient connection string / or constructor flow?
or are you using your own auth stack?

thanks

**Comment by rsaclee** [comment]
This is the connection method, and we registered the Application on Azure and got the client id and client secret and use it to connect, the organizationUrl is [https://OrgNamedev1.crm.dynamics.com]
The library we used are
using Microsoft.Xrm.Tooling.Connector;
using Microsoft.IdentityModel.Clients.ActiveDirectory;

public static IOrganizationService GetOrganizationService(string clientId, string appKey, string tenantId, string organizationUrl)
        {

            //Create the Client credentials to pass for authentication
            ClientCredential clientcred = new ClientCredential(clientId, appKey);
        
            System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

            //Generate the authentication context - this is the azure login url specific to the tenant
            //string authority = authParam.Authority;
            string authority = "https://login.microsoftonline.com/" + tenantId + "/";
            //request token

            if (authContext == null)
            {
                authContext = new AuthenticationContext(authority);
            }
            
            AuthenticationResult authenticationResult = authContext.AcquireTokenAsync(organizationUrl, clientcred).Result;
            //get the token              
            string token = authenticationResult.AccessToken;

            Uri serviceUrl = new Uri(organizationUrl + @"/xrmservices/2011/organization.svc/web?SdkClientVersion=9.1");

            //using (OrganizationWebProxyClient sdkService = new OrganizationWebProxyClient(serviceUrl, false))

            OrganizationWebProxyClient sdkService = new OrganizationWebProxyClient(serviceUrl, false);
            //{
                sdkService.HeaderToken = token;

                //IOrganizationService _orgService = (IOrganizationService)sdkService != null ? (IOrganizationService)sdkService : null;
                //return _orgService;
               var _orgService = new CrmServiceClient(sdkService);
            //}
            return _orgService;
        }

After we got the orgService, we used that to update/delete/insert to CRM.
We didn't get any error when using this method. But after switching to MSAL using Microsoft.PowerPlatform.Dataverse.Client, we got the error - Failed to connect to Dataverse (in my previous post).
How can we manage the connection pool when using this new library?  How can this be configured so we don't exceed the API call limits?

**Comment by MattB-msft** [comment]
Ok this method is not supported in DVSC, 

When you converted to DVSC did you use a connection string ( passing ClientID/APIKey to the service Client? 
or did you retain the process of creating the access token on your own? 

also are you recreating the connection for each request or are you getting a pool of requests and processing them with one client?

**Comment by rsaclee** [comment]
I changed the method to this
public static ServiceClient ConnectToCRM(string crmOrg)
        {
            //d365
            string filePath = XmlFileManager.GetFilePath(Constants.CRMENTITIES_FILE);
            XDocument xDoc = XDocument.Load(filePath);
            System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;
            
              ////---- from microsoft link
            //// Bump up the min threads reserved for this app to ramp connections faster - minWorkerThreads defaults to 4, minIOCP defaults to 4 
            ThreadPool.SetMinThreads(minThreads, minThreads);
            // Change max connections from .NET to a remote service default: 2
            System.Net.ServicePointManager.DefaultConnectionLimit = conLimit;
            // Turn off the Expect 100 to continue message - 'true' will cause the caller to wait until it round-trip confirms a connection to the server 
            System.Net.ServicePointManager.Expect100Continue = false;
            // Can decrease overall transmission overhead but can cause delay in data packet arrival
            System.Net.ServicePointManager.UseNagleAlgorithm = false;
            ////---- from microsoft link

            ServiceClient svc = null;

            foreach (string connectionItem in listCrmConnectionString)
            {
               
                svc = new ServiceClient(connectionItem);
                if (svc != null)
                {
                   if (svc.IsReady)
                        break;
                }
           }
           
            return svc;
      }

so I am using connection string with appid and client id and it seems to be working.
However, even though I try to use a collection of app id and client secret, It will only use one connection with one client.
Do you have sample code to use a pool of requests?
Also, I got this following from a MS document, not sure if the setting is fixed or how to configure it

//// Bump up the min threads reserved for this app to ramp connections faster - minWorkerThreads defaults to 4, minIOCP defaults to 4 
            ThreadPool.SetMinThreads(minThreads, minThreads);
            // Change max connections from .NET to a remote service default: 2
            System.Net.ServicePointManager.DefaultConnectionLimit = conLimit;
            // Turn off the Expect 100 to continue message - 'true' will cause the caller to wait until it round-trip confirms a connection to the server 
            System.Net.ServicePointManager.Expect100Continue = false;
            // Can decrease overall transmission overhead but can cause delay in data packet arrival
            System.Net.ServicePointManager.UseNagleAlgorithm = false;

**Comment by MattB-msft** [comment]
Thanks, this helps.. 
Can you describe what your trying to do ?  Context would help me guide you here. 

So far, I gather your trying to do a mass data import / update to Dataverse, 
do you start with a single large file?  or do you get the records in smaller groups? 

t

**Comment by rsaclee** [comment]
This custom SDK C# project loads around 1/2 million of records from our EPR system to D365 CRM daily.  Because of the size, we load 200 records every 1 mins. (There are also some batch processing at night) The input files for now are XML files but will be json in new development.
The challenge now is how to configure and tune performance and manage the connection pooling (if there is any) so we can optimize the data load using Service Client.
Any help is this area is greatly appreciated.

**Comment by MattB-msft** [comment]
Got it. 
Take a look at this code here: https://learn.microsoft.com/en-us/power-apps/developer/data-platform/api-limits?tabs=sdk#how-to-maximize-throughput and here: https://learn.microsoft.com/en-us/power-apps/developer/data-platform/send-parallel-requests?tabs=sdk

For Batch and Rappid fire updates,  take a look at the second link, we changed the guidance here from CrmServiceClient. 

Insofar as connection pooling, that is only going to help you if each connection has its own appid /secret as the throttling limits are calculated based on connected user. 

The DV Service client will also handle throttling automatically, retrying for a set number of retires. 

In the fall of this year, ( or sooner ) we will also be shipping set of 'bulk' api's that are designed to support this type of scenario. 
You will see them described as "CreateMultiple, UpdateMultiple, DeleteMultiple".  We will start these with custom entities, and extended it to shipped entities over time.  see: https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/use-createmultiple-updatemultiple?tabs=sdk

**Comment by MattB-msft** [comment]
Given no response, im going to assume your good to go and will close up this issue.
