### ISSUE TITLE
Usage of .Result is problematic

### ISSUE THREAD

**Issue by soutchilin** [microsoft/PowerPlatform-DataverseServiceClient#372]
https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/44a1af6fca8e9b3ec806d2322fbceab332b3164e/src/GeneralTools/DataverseClient/Client/ServiceClient.cs#L1580

Hi,

according to https://learn.microsoft.com/en-us/aspnet/core/fundamentals/best-practices?view=aspnetcore-3.0#avoid-blocking-calls the usage of .Result is not okay and can lead to deadlocks. Please consider to use GetAwaiter().GetResult().

Kind regards,
Alexander

**Comment by MattB-msft** [comment]
Thanks for pointing this out,

We have gone back and forth on this and discussed this at somewhat great lengths with the folks in the .net team. The general guidance we are getting back is 'it depends on framework / core / version of core' as to the potential for the deadlocking behavior to occur. 

Public Doc's are generally targeted at the leading-edge vs the spectrum. 

In light of the pending drop of support for .net core 3.1, we can discuss it again.
