### ISSUE TITLE
Intermittent error "An error occurred while sending the request."

### ISSUE THREAD

**Issue by heroes3lover** [microsoft/PowerPlatform-DataverseServiceClient#374]
Hello, 

I am not sure what is the root cause of this issue, but I noticed that several times during testing in last few weeks.

framework is .Net 6 
PowerPlatform sdk 1.0.39
Interface IOrganizationServiceAsync2 registered as Singleton.

Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..

**Comment by heroes3lover** [comment]
[error.log](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/files/11416256/error.log)

**Comment by MattB-msft** [comment]
Network forcibly closed is nearly always a network gateway or proxy terminating the connection. 

This has cropped up more frequently as folks switch to .net 6 as the net team changed several aspects of the net6 network behavior that seem to trigger gateways to think something is wrong. (Or the gateway is misbehaving to being with) 

You isolate that in 2 ways. 

1) run your code outside of the network filters by the gateway. 

2) recompile for .net framework and re run. 

If the problem stops, it's the gateway and you will need to work with your network team to troubleshoot shoot the problem. 

If it does not stop, the it must be something in the route to the msft network and there is further troubleshooting you can do.

**Comment by MattB-msft** [comment]
Going to close this up at this time as there has not been a response.
