### ISSUE TITLE
Clone cloned connection inside Parallel.ForEach

### ISSUE THREAD

**Issue by frozzen10** [microsoft/PowerPlatform-DataverseServiceClient#375]
Hello there!
I'm working with your library on a new .NET 6 project and I've encountered a certain issue. Specifically, I wanted to take advantage of the DI (Dependency Injection) capabilities. I searched GitHub to find the proper way to do it, and here's the code that explains it:

```C#
public class DataverseServiceClientWrapper
{
    private readonly static string _connectionString = "AuthType=ClientSecret;url=url;ClientId=clientId;ClientSecret=clientSecret";
    public readonly ServiceClient ServiceClient;

    public DataverseServiceClientWrapper()
    {
        ServiceClient = new ServiceClient(_connectionString);
    }
}
```
there is a registration inside Progam.cs
```C# 
// some code

builder.RegisterAssemblyTypes(typeof(ISomeInterface).Assembly)
    .Where(t => typeof(ISomeInterface).IsAssignableFrom(t) && t.IsClass && !t.IsAbstract)
    .AsImplementedInterfaces()
    .AsSelf()
    .InstancePerLifetimeScope();
    
builder.RegisterType<Repository>()
    .AsSelf()
    .InstancePerLifetimeScope();
    
builder.Register(ctx => new DataverseServiceClientWrapper())
    .AsSelf()
    .SingleInstance();

builder!.Register(ctx =>
{
    var logger = ctx.Resolve<ILogger<Program>>();
    var client = ctx.Resolve<DataverseServiceClientWrapper>().ServiceClient.Clone();
    logger.LogInformation("Cloned client at {time}.", DateTimeOffset.UtcNow);
    return client;
})
.InstancePerDependency();
      
 // some code
 ```
 
There I have some class that has Repository class which has ServiceClient class:
 
 ```C#
 public class Repository
{
    private readonly ServiceClient _serviceClient;

    public Repository(ServiceClient serviceClient)
    {
        _serviceClient = serviceClient;
    }
}

public class SomeClass : ISomeInterface
{
    private readonly ILogger<SomeClass> _logger;
    private readonly Repository _repository;

    public SomeClass(ILogger<SomeClass> logger, Repository repository)
    {
        _logger = logger;
        _repository = repository;
    }
}
 ```
 
Additionally, I wanted to use Parallel.ForEach for executing requests concurrently. Here's implementation of my extension method:

```C#
public static ConcurrentBag<ExecuteMultipleResponse> ExecuteInParallel<T>(
   this ServiceClient @this,
   IEnumerable<T> requests,
   int batchSize = 500,
   Action<ExecuteMultipleResponse, int> batchCallback = null) where T : OrganizationRequest
{
   // some code
    ConcurrentBag<ExecuteMultipleResponse> responses = new();
    Parallel.ForEach(source,
        new ParallelOptions() { MaxDegreeOfParallelism = @this.RecommendedDegreesOfParallelism },
        () =>
        {
            // Clone the ServiceClient for each thread
            return @this.Clone(); // <= here is the problem
        },
        (batch, loopState, index, threadLocalSvc) =>
        {
           // some code

            return threadLocalSvc;
        },
        (threadLocalSvc) =>
        {
            // Dispose the cloned ServiceClient instance
            threadLocalSvc?.Dispose();
        });

    // Return the ConcurrentBag of ExecuteMultipleResponse
    return responses;
}
```
The problem is that when I use the Clone method inside localinit, I get an error:
>1 of 3 inner exceptions
>DataverseOperationException: Failed constructing cloned connection. debugstate=2
>2 of 3 inner exceptions
>DataverseConnectionException: Exception - Fault While initializing client - RefreshInstanceDetails
>3 of 3 inner exceptions
>NullReferenceException: Object reference not set to an instance of an object.

Could someone explain why this is happening and how I can fix it, or perhaps suggest a different approach altogether?
Thank you so much for your help!

**Comment by MattB-msft** [comment]
For .net6 + our guidance changed due to changes in how .net networking and threading work. 
Please see this : https://learn.microsoft.com/en-us/power-apps/developer/data-platform/send-parallel-requests?tabs=sdk#examples for guidance on threads. 

Also do make sure you on the most current version of the dataverse Service Client.

**Comment by frozzen10** [comment]
@MattB-msft thanks for fast response.
I've changed my implementation with guidance you provided and I think it's working.
But can you explain what happen under the hood? I am wondering how instance of ServiceClient is treated by threads in this async foreach.
Earlier client should be cloned manually inside init Func parameter and then at the and disposed. How it is done with this approach?

Thanks.

**Comment by MattB-msft** [comment]
Most of the changes in .net 6 are listed here: https://devblogs.microsoft.com/dotnet/dotnet-6-networking-improvements/ 
Structurally, there was a memory leak issue we resolved. 

The Object reference not set to an instance of an object should have been fixed in .39 of the client.

**Comment by frozzen10** [comment]
@MattB-msft thanks for explanation!
