### ISSUE TITLE
SessionTrackingId not persisted in ClientSessionId in DV SDK 1.1.9 Release

### ISSUE THREAD

**Issue by BegBedion** [microsoft/PowerPlatform-DataverseServiceClient#381]
From version 1.0.0.39 to 1.1.9 we are not seeing the ClientSessionId being persisted in CRM Logs

We are blocked on bumping SDK version.

**Comment by MattB-msft** [comment]
This has been identified and fixed, and will be included in the next update to the ServiceClient. 
in the meantime, if you encounter this issue, you will need to execute an operation that force the update the host organization version to get session ID to work. 

this can be done by asking for the tenant ID property, or any property related to the environment configuration.

**Comment by BegBedion** [comment]
When will the next version of the ServiceClient be released?
