### ISSUE TITLE
LINQ query – Unable to perform multiple LEFT OUTER JOINs

### ISSUE THREAD

**Issue by rc-GDC** [microsoft/PowerPlatform-DataverseServiceClient#386]
I’m not sure if this is a bug\flaw in the design of the QueryProvider (Microsoft.Xrm.Sdk.Linq.QueryProvider) found within the Microsoft.PowerPlatform.Dataverse.Client package (I’m using the currently latest version, v1.1.9) or this is intentional and there is something I’m missing here, but when I try and perform the LINQ equivalent of a LEFT OUTER JOIN on two (or more) entities, I get the exception below (I’ve amended Microsoft’s example, converting it from inner to outer join):

```csharp
var complexQuery = (from c in svcContext.ContactSet
                   join a in svcContext.AccountSet
                          on c.ContactId equals a.PrimaryContactId.Id into accGrp
                    from acc in accGrp.DefaultIfEmpty()
                   join l in svcContext.CreateQuery<Lead>()
                          on acc.OriginatingLeadId.Id equals l.LeadId into leadGrp
                   from lead in leadGrp.DefaultIfEmpty()
                   where c.LastName == "Wilcox" || c.LastName == "Andrews"
                   where acc.Address1_Telephone1.Contains("(206)")
                       || acc.Address1_Telephone1.Contains("(425)")
                   select new
                   {
                       c.ContactId,
                       lead.LeadId,
                       acc.AccountId
                   }).Take(10).ToList();

/*
  The method 'GroupJoin' cannot follow the method 'SelectMany' or is not supported. Try writing the query in terms of supported methods or call the 'AsEnumerable' or 'ToList' method before calling unsupported methods.
   at Microsoft.Xrm.Sdk.Linq.QueryProvider.ThrowException(Exception exception)
   at Microsoft.Xrm.Sdk.Linq.QueryProvider.GetQueryExpression(Expression expression, Boolean& throwIfSequenceIsEmpty, Boolean& throwIfSequenceNotSingle, Projection& projection, NavigationSource& source, List`1& linkLookups)
   at Microsoft.Xrm.Sdk.Linq.QueryProvider.Execute[TElement](Expression expression)
   at Microsoft.Xrm.Sdk.Linq.QueryProvider.GetEnumerator[TElement](Expression expression)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in C:\CrmTest\Program.cs:line 30
*/
```

I’ve decompiled the source using JetBrains Decompiler, and I can see that the QueryProvider uses a map to determine which Lambda method can proceed another, and I can see here that whilst a SelectMany can follow a GroupJoin, this does not apply vice-versa with SelectMany following a GroupJoin, this is what’s causing the error.

I’ve also noticed that it’s not possible to follow an INNER JOIN with a LEFT OUTER JOIN (or vice-versa) either, this also generates an exception like the above.

**Comment by chironh** [comment]
I think this is just a limitation of the QueryProvider.
In this situation I usually go for a FetchExpression in a latebound RetrieveMultiple, which supports multiple inner/left join combinations.

**Comment by MattB-msft** [comment]
Yes. these are limitations of the LinqQuery Provider 
https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/use-linq-construct-query#linq-limitations
