### ISSUE TITLE
Deprecated Dependencies. Microsoft.Rest.ClientRuntime

### ISSUE THREAD

**Issue by Elio-Alten** [microsoft/PowerPlatform-DataverseServiceClient#392]
I am updating my code and I am using dataverseServiceClient and I am seeing that the library Microsoft.Rest.ClientRuntime is deprecated. will we have these dependencies updated?

**Comment by MattB-msft** [comment]
sorry for the delay in responding here. 

We are aware of this and are discussing this with the Azure team, as their replacement lib extends the dependencies beyond the features of Rest.ClientRuntime.  Also not all of the library's that have requirements of Rest.ClientRuntime have been updated yet. 

Once we have worked though the ramifications of this we will pick up the changes and push and update. 

I will hold this open until we make a call on this.

**Comment by MattB-msft** [comment]
Providing a bit of an update here. 
We are going to keep using the Rest nuget for a time yet. 

While the team is recommending Azure.Core as replacement, it is missing parts of the Rest package that we use (specifically the exception parsers for http REST requests) 

To swap out support will require us to take breaking changes to the library for consumers (you) who handle exceptions we throw from the lib. 

We will relook at this again when we bump the major version of the lib.
