### ISSUE TITLE
FetchXML flaw for ordering and then doing distinct, not the other way around.

### ISSUE THREAD

**Issue by wrharper-AASP** [microsoft/PowerPlatform-DataverseServiceClient#398]
When calling the API to do distinct you use ?fetchXml=`<fetch distinct="true">` but before that, I'd like to order by createdon desc and then do the distinct to remove duplicates. Is this possible in some way?

**Comment by wrharper-AASP** [comment]
I'm assuming the problem is how they do the distinct algorithm. They probably do (if next is same -> remove) rather than (if list contains dups -> remove). So, if you sort first, the distinct algorithm fails?

**Comment by JimDaly** [comment]
@wrharper -
Thanks for your feedback. 
This forum is for feedback about the documentation, and it works best when the feedback is associated with a specific article. The way that these get linked is by opening the issue using the feedback button at the bottom of the article.

Which article is your feedback related to? I expect it must be this one [Use FetchXML to construct a query](https://learn.microsoft.com/power-apps/developer/data-platform/use-fetchxml-construct-query)

I recommend using [FetchXml builder](https://www.xrmtoolbox.com/plugins/Cinteros.Xrm.FetchXmlBuilder/) to test your FetchXml query and observe the result. When you send the request via Web API, you should get the same results.

**Comment by wrharper-AASP** [comment]
I wish Microsoft owned that; 3rd party stuff isn't something most people are allowed to use.
What I am trying to do doesn't appear to be possible at all. What do you do in that case?

**Comment by JimDaly** [comment]
@wrharper -

I'm working with the dev team on some improvements to the fetchXml documentation. But these are going to be pretty general in nature. I don't think they will address your specific question.

I can't offer technical support here, so I can't help troubleshoot this specific issue.
The purpose of these issues is to identify things we can do to improve the docs.
What do you think we can add to the docs that will help address this challenge and save you time?

Also, some context about your use case might be helpful. I know you are using Web API and you want to do aggregation & grouping. Is this to generate a report?
If so, have you looked at Power BI?

BTW - An alternative to using FetchXml builder is to use the [legacy Advanced Find](https://learn.microsoft.com/power-apps/user/advanced-find#create-edit-or-save-a-view-using-legacy-advanced-find) and download the fetchxml it generates.

**Comment by wrharper-AASP** [comment]
At this point, it looks like it's just not possible with fetchxml. What I would really like is to know if there is an active github about fetchxml features and what it "cannot" do and see if such a thing can be requested.

**Comment by JimDaly** [comment]
Thanks Wayne. 
Positively documenting capabilities is possible. We have much room for improvement here just to do this.

Trying to maintain documentation about all the things that _can't be done_ is not realistic since everyone has different expectations about what they should be able to do. We are going to focus on documenting known capabilities better.

I'll share this feedback with the dev team and update this if I get a response.

**Comment by wrharper-AASP** [comment]
ok, my current query is quite complex already. it looks like to go further I will just have to do more than 1 query. I was hoping to get everything I needed in 1 go instead of sending multiple calls to get the info I need while being distinct and sorted in a certain way. I'm pretty positive this isn't possible now because of how "distinct=true" works.
I'm just trying to optimize overall speed of output to users.

**Comment by JimDaly** [comment]
@wrharper-AASP 
I recommend that you contact tech support for help with this question. A dev reviewed this thread and it isn't clear what specific change to the documentation we could make that would help you. 
Closing this.
