### ISSUE TITLE
DiscoverOnlineOrganizationsAsync fails with tokenCacheStorePath when AppDomain.CurrentDomain.FriendlyName has invalid characters

### ISSUE THREAD

**Issue by cupacheeno** [microsoft/PowerPlatform-DataverseServiceClient#406]
Using the Service Client DiscoverOnlineOrganizationsAsync static method with the optional parameter tokenCacheStorePath will fail when the AppDomain.CurrentDomain.FriendlyName contains invalid characters.

For example.
Microsoft.PowerPlatform.Dataverse.Client = 1.1.14

Visual Studio Project = VSTO Add-In

The call will fail in the Microsoft.PowerPlatform.Dataverse.Client.Auth.TokenCache.FileBackedTokenCacheHints.FileBackedTokenCacheHints method as it attempts to use the AppDomain.CurrentDomain.FriendlyName

Unfortunately this property is not an editable property and as such in this particular instance would be
"Project.vsto|vstolocal" and throw an exception.

**Comment by cupacheeno** [comment]
@MattB-msft just checked this however the fix has not been successful.
Taking a look at PR #411 
In src/GeneralTools/DataverseClient/Client/Auth/TokenCache/FileBackedTokenCacheHints.cs Line 39
This is where it would fail as a result of the AppDomain.CurrentDomain.FriendlyName having special characters, as such it should be remedied before the call to
`text = Path.GetFileNameWithoutExtension(AppDomain.CurrentDomain.FriendlyName);`

**Comment by MattB-msft** [comment]
oh. you were saying the .net file handler is failing ... ah. sorry misunderstood you there. will reopen and track this down.

**Comment by MattB-msft** [comment]
More complete fix added in next drop.
