### ISSUE TITLE
Error message  - Could not load file or assembly 'PresentationFramework'

### ISSUE THREAD

**Issue by Mastok1979** [microsoft/PowerPlatform-DataverseServiceClient#414]
Wenn trying to RetrieveMultiple

Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

 
```
                using ServiceClient svc = new(_connectionString);
                if (svc.IsReady)
                {
                    QueryExpression query = new()
                    {
                        EntityName = "new_statproduction",
                        ColumnSet = new ColumnSet(true),
                        Criteria = new FilterExpression(),
                    };

                    EntityCollection retrieved;
                    try
                    {
                        retrieved = await svc.RetrieveMultipleAsync(query);
                    }
                    catch (Exception ex)
                    {
                        throw ex;
                    }
                }


```

![image](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/5084676/ff577a54-8b59-4981-b3c9-56e0882fdc33)

I cannot understand why this happens :( 
Loosing lot of time to solve this issue.

Can someone help me?

**Comment by MattB-msft** [comment]
@Mastok1979 

There would need to be something else going on here,  PresentationFramework is only used in the Login Controls and their supporting modules.

Its not used by the base connector. 
could you provide more context as to what is going on if your still seeing the issue?

**Comment by MattB-msft** [comment]
Closing this post at this time as there is not enough to work with.
