### ISSUE TITLE
Cannot use Parameters in CreateMultipleRequest

### ISSUE THREAD

**Issue by rajyraman** [microsoft/PowerPlatform-DataverseServiceClient#417]
Using latest version 1.1.16. CreateMultiple works without any Parameters specified.

![image](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/5035266/35d2943f-5ea5-4386-946d-59e079766853)

The moment I want to use Parameters, I get an error saying that Targets is missing. I wanted plugins and flows to be skipped with CreateMultiple but I cannot due to this issue.

![image](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/5035266/e400f765-5b32-41c8-944d-1211f4256ca7)

**Comment by rajyraman** [comment]
Interestingly, this works though.

![image](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/5035266/deb8fd8a-744b-48f6-a66d-8e023b9310dd)

**Comment by JimDaly** [comment]
`Targets` is one of the parameters. If you set the Parameters collection, you are removing the Targets.

I don't think you should ever use Parameters unless you are using `OrganizationRequest`.

We have sample code for this here: https://github.com/microsoft/PowerApps-Samples/tree/master/dataverse/orgsvc/C%23-NETCore/BulkOperations/CreateUpdateMultiple

**Comment by rajyraman** [comment]
@jimdaly - Interesting!! This wasn't obvious to me. Thank you Jim.
