### ISSUE TITLE
ServiceClient DisableCrossThreadSafeties is not working for Command_ExecuteAsyncImpl

### ISSUE THREAD

**Issue by BowenWang0626** [microsoft/PowerPlatform-DataverseServiceClient#420]
The lock object was initialized but never used:
![image](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/103979770/e62e3851-ddb6-4f50-8f01-3ce7f48f78cd)

While the Command_Execute, the lock object was initialized and locked:
![image](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/103979770/ec8d33ac-22ad-456a-b25e-c6bf6b87971f)

**Comment by MattB-msft** [comment]
@BowenWang0626 

This is intentional and by design.  Its initialized there as we use the same functions for handling error and retry behavior between sync and async behaviors. 

Cross thread Safeties are not required for Async Operations.  That behavior is detrimental to async ops.
