### ISSUE TITLE
EntryPointNotFoundException when trying to connect using OAuth

### ISSUE THREAD

**Issue by sesockchris** [microsoft/PowerPlatform-DataverseServiceClient#421]
When trying to connect to our Dynamics 365 CRM using an OAuth connection string, I am receiving an exception stating that the "EntryPointNotFoundException: Entry point was not found". This is the same connection string used in other repositories and works, the only difference being that the working repo is a .Net Framework 4.8 repo, while mine is a .Net Core 6.0 project. 

*connection string values were removed for security reasons*

![image](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/32208002/5c854639-3fc1-447a-b823-82a7a6dd27d6)

![image](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/32208002/5ef8f134-a213-4679-9c68-18bb8a1c1968)

**Comment by MattB-msft** [comment]
@sesockchris 
Not a lot to go on here... We actively use and deploy this on .net6 + 

I, personally, have seen recompile errors if you switch from Framework to Core in the same project.  But I do not get that you're doing that.  You can usually clear those by deleting all OBJ and Bin directories.

Could you provide a bit more environmental data?  Are you running the .net6 bits on Windows / Non-Windows?

**Comment by MattB-msft** [comment]
Going to close this post at this time as there is not enough info to work with,.
