### ISSUE TITLE
Cloned connections lacking option to have their own custom headers

### ISSUE THREAD

**Issue by svejdo1** [microsoft/PowerPlatform-DataverseServiceClient#438]
Ref: https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/master/src/GeneralTools/DataverseClient/Client/ServiceClient.cs (line 1420)

When we're cloning ServiceClient the CustomHeaders function is always set to match the parent.
This makes impossible to set custom headers per clonned connection.

**Comment by MattB-msft** [comment]
@svejdo1, thanks for your report, Yes, this is a known issue.  

On the bright side, we are about to ship a new feature to address this specific issue. 
This new feature is a request builder where you can set headers per request, as well as user ID, request ID and so on.

**Comment by MattB-msft** [comment]
Fixed with https://github.com/microsoft/PowerPlatform-DataverseServiceClient/pull/444
