### ISSUE TITLE
Server-side request timeout

### ISSUE THREAD

**Issue by svejdo1** [microsoft/PowerPlatform-DataverseServiceClient#439]
We have a scenario where (typically when processing burst of requests) when we're getting slower replies from dataverse - attacking 2 minutes per request. Our services are configured (on purpose) to stop processing web request in 30seconds (lower than dataverse limit for web request processing - which is I believe 2minutes).

Challenge here is reporting and telemetry - when we stop processing the web request in our service side it is impossible to tell if there isn't say some global outage on dataverse web api.

Would it be possible / or is there some possibility to pass some "max processing request time header" from client to server so those requests will be cancelled on server side instead if they're processed slowly ?

This would be at least confirmation that DV is healthy / just slow.

**Comment by MattB-msft** [comment]
@svejdo1 
This make sense but would need to be taken up with the internal DV API team.  Please Ping them ( as I know your internal :) ) and discuss with them. 

The current timeout feature set exposed in the client does not stop DV processing, it just manages the keep alive on the connection itself.

**Comment by jarvan-jiang** [comment]
Hi @svejdo1 , did you have any updates regarding this? We met exactly the scenario, when some backend servers of dataverse gone bad for some reasons, we got requests timeout and dropped the connection, but from the network trace I saw the response returned long after we dropped the connection, that means the request still processing slowly in server.
