### ISSUE TITLE
Retrying requests 

### ISSUE THREAD

**Issue by mathiasbl** [microsoft/PowerPlatform-DataverseServiceClient#442]
Retrying requests will use Thread.Sleep in between attempts.
In the async implementation 'Command_ExecuteAsyncImpl' you could switch to use Task.Delay to free up the thread.

https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/33b6089f0be589dddad774fe748a93813bab4a97/src/GeneralTools/DataverseClient/Client/Utils/Utils.cs#L434

https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/33b6089f0be589dddad774fe748a93813bab4a97/src/GeneralTools/DataverseClient/Client/ServiceClient.cs#L1870

**Comment by MattB-msft** [comment]
Thanks for your feedback, 
We will have a look.

**Comment by MattB-msft** [comment]
Fixed with https://github.com/microsoft/PowerPlatform-DataverseServiceClient/pull/444

**Comment by mathiasbl** [comment]
@MattB-msft 

Task.Delay is not awaited in the new version so it has a bug. Don't forget to await upstream aswel.

https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/3af97c1776070c155b416e4488993e49524eaeb2/src/GeneralTools/DataverseClient/Client/Utils/Utils.cs#L456

**Comment by MattB-msft** [comment]
Checking with the team on this... in the meantime we have unlisted 1.1.21
