### ISSUE TITLE
Vulnerable transitive packages

### ISSUE THREAD

**Issue by isorty** [microsoft/PowerPlatform-DataverseServiceClient#455]
Currently, when running `dotnet list package --vulnerable --include-transitive` it shows the following vulnerable packages:

|         Transitive Package        | Resolved | Severity |                    Advisory URL                   |
|:---------------------------------:|:--------:|:--------:|:-------------------------------------------------:|
| System.Security.Cryptography.Pkcs |   6.0.1  |   <span style="color:red">High</span>   | https://github.com/advisories/GHSA-555c-2p6r-68mm |
|   System.Text.RegularExpressions  |   4.3.0  |   <span style="color:red">High</span>   | https://github.com/advisories/GHSA-cmhx-cq75-c4mj |

**Comment by MattB-msft** [comment]
This is an ongoing chase for downstream systems.
we will update these as quickly as we can, however in the interim, your advised to add the specific versions of the transitive dependencies to your local projects. 

thanks for reporting this.
