### ISSUE TITLE
Missing dependencies while running Text template (.tt or .t4)

### ISSUE THREAD

**Issue by HubdriveTeam** [microsoft/PowerPlatform-DataverseServiceClient#465]
We are facing issues after upgrading our .NET Framework 4.7.1 class library from XrmTooling.CoreAssembly to PowerPlatform.Dataverse.Client. 
The library compiles correctly, but runtime errors occur when executing text template files that rely on the library. The errors indicate that deprecated libraries and incorrect dependency versions are being sought in nested dependencies.

This behaviour does not occur with XrmTooling.CoreAssembly and the Text Template files return the sought after objects.

Has anyone had an issue like this before? Is it because PowerPlatform.Dataverse.Client also supports .NET core? We have already tried to redirect dependencies via binding redirect, however without any luck. The only solution was registering Assembly event handlers that allow us to attempt to load incoming assemblies if they fail initially. 

AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;
 
// Subscribe to the AssemblyLoad event
AppDomain.CurrentDomain.AssemblyLoad += CurrentDomain_AssemblyLoad;
(Important: Needed to be registered before calling ServiceClient constructor)

**Comment by MattB-msft** [comment]
This generally indicates that your tool is pulling dependencies from different sources in your output directory. 
I would check the modules you added to your project that may be pulling the older dependencies.

**Comment by MattB-msft** [comment]
Going to close this as it does not seem to apply to the Service Client itself.
