### ISSUE TITLE
High memory consumption after exceptions being thrown

### ISSUE THREAD

**Issue by tovyhnal** [microsoft/PowerPlatform-DataverseServiceClient#474]
As suggested in [here](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/issues/447#issuecomment-2078576845), we started using ServiceClient as singleton in our application. Recently we noticed, that our web application started occasionally failing with OutOfMemoryException.

We believe, this is connected with our migration to singleton ServiceClient.

I was able to repro this (high memory usage) locally, by requesting non-existing entity from DV, which resulted in exception being thrown in ServiceClient. After 10k of such iterations, memory grew to 1,4GB.

![Image](https://github.com/user-attachments/assets/b0732336-fc8a-4a81-b6f4-a0f057dfab07)

I suspect, it is connected to [DataverseTraceLogger](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/master/src/GeneralTools/DataverseClient/Client/DataverseTraceLogger.cs) and [this code](            _ActiveExceptionsList.Add(exception);) which add any thrown exception into internal list of exceptions. This can accumulate over days to size, which causes service to crash with OutOfMemoryException. 

See below state of DataverseTraceLogger after ~400 exceptions thrown.
![Image](https://github.com/user-attachments/assets/6fb99700-947a-4168-b184-f09c4cd135c0)

**Comment by tovyhnal** [comment]
I ran memory profiler, which I believe confirms my assumption:

![Image](https://github.com/user-attachments/assets/0dfb6046-e060-4256-81a0-6a7cb8e38561)

**Comment by MattB-msft** [comment]
Fix was provided by reporter internally 
thanks @tovyhnal , 
Fix will be provided in the next update drop to the client.

**Comment by ChrisIsidora** [comment]
@MattB-msft Is there an estimate when this will be included in a new release?

**Comment by MattB-msft** [comment]
Fix was provided in the associated release
