### ISSUE TITLE
Availability of the PowerShell module?

### ISSUE THREAD

**Issue by rvdwegen** [microsoft/PowerPlatform-DataverseServiceClient#483]
Hello,

There is seemingly a new Core/PS7 compatible Dataverse PowerShell module [included in this repo](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/tree/master/src/GeneralTools/DataverseClient/PowerShell/Microsoft.PowerPlatform.Dataverse.Client.PowerShell/Microsoft.PowerPlatform.Dataverse.Client.PowerShell).
Will this be published on the gallery in the near future?

Thank you!

**Comment by MattB-msft** [comment]
We do not have a good answer on if we will publish this in the future.  

This code is working, and you are welcome to use it locally, however there are compatibility issues that have come up with regards to some changes in the .net/WCF project that have created a version incompatibly in PSCore between this code and other MSFT PS Modules that can co-exist,   This should get sorted out with the released the .net/WCF team is doing for .net 9 (WCF8). 

We will revisit this once that has started shipping and the main XRM core has updated to it.

**Comment by rvdwegen** [comment]
Thanks, but my understanding is that its dependent on DLLs that are currently not publicly available? Or at least I haven't been able to find them in the repo or elsewhere.

**Comment by MattB-msft** [comment]
Fork the repro and change this : 

https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/42bcd7ea76d18a6d1e5e8e612a260f75e746b144/src/GeneralTools/DataverseClient/PowerShell/Microsoft.PowerPlatform.Dataverse.Client.PowerShell/Microsoft.PowerPlatform.Dataverse.Client.PowerShell.csproj#L25C1-L28C15

to point at the current DVSC Nuget package. 

that should let you build it.
