### ISSUE TITLE
Connect Business Central to Dataverse and Dynamics 365 Sale - Problem with customers

### ISSUE THREAD

**Issue by viktorglemne** [microsoft/PowerPlatform-DataverseServiceClient#486]
Description:
We are attempting to synchronize Business central to Dynamics 365 Sales but ends up with problem regarding sync of Customers. The sync fails on every record on SystemUser not exist. See error below

We Tried:
We have gone through permissions and user and can't find anything that could be the stopper. The user ID guid shown on the error message cannot be found either in BC, Dataverse or Sales.

Error:
An error occurred when communicating with Dataverse.
Detailed description: Entity 'SystemUser' With Id = <<Guid>> Does Not Exist

Question:
Where to look and what to do?

**Comment by MattB-msft** [comment]
@viktorglemne for this type of issue you should open up a support ticket with us so that we can look at you're in context of the environments and data you're working with. 

I'm sorry I cannot provide more information here, however this is likely something specific to your environment / data.

**Comment by viktorglemne** [comment]
Thanks for the response! Can you please provide me with guidance where do i open a support ticket?
