### ISSUE TITLE
[Feature] Add support for CancellationToken to cancel requests downstream

### ISSUE THREAD

**Issue by BoutemineOualid** [microsoft/PowerPlatform-DataverseServiceClient#79]
Hi,

Is it possible to add overloads that support a CancellationToken for methods exposed on the IOrganizationService contract and the OrganizationServiceContext class so that we can cancel requests to CDS when a call is aborted upstream.

Thanks.

**Comment by MattB-msft** [comment]
This is a longstanding ask that we are more actively considering how to deal with. 

It is currently not possible to support this sort of feature on IOrganziationService as it is shared between server and clients.  This choice was made to provide a uniform coding and development model between clients and server. 

Also, in general IOrganizationService calls are not Async by nature, they are sync calls and not subject to cancelation from the client.  

I am curious what you mean by aborted Upstream?  if your referring to the server faulting the request, this is already handled immediately.  if by upstream you mean in the caller of the client needing to terminate the call that is a different matter which we can look into.

**Comment by BoutemineOualid** [comment]
Say I have an API endpoint exposed in a controller with a CancellationToken to support aborting. If the CancellationToken is set following an abort, I would like to abort all microservice calls downstream including those to CDS. That's already possible with a regular HttpClient instance. I just dont wanna use regular Rest calls to CDS.

**Comment by MattB-msft** [comment]
Ok so your talking about the Caller asking to do a cancel of an inflight communications. 
We do not support that today as we do not support the async all pattern for our general SDK, this means that all calls to the CDS API are sync calls today. 

we are considering if and how to add async call patterns to the client.
if we add them however we will likely end up breaking cross's code use with Plugins on the CDS Server. 

that is the root of our conflict at the moment. 

thanks

**Comment by MoranShusheng** [comment]
Is there any progress? I have the same needs

**Comment by MattB-msft** [comment]
After Rather extensive discussion with the API teams on this, we are going to close this issue as a wont fix.  
We did add support for the client to be able to do this to a degree, using the local [IOrganizationService2](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/master/src/GeneralTools/DataverseClient/Client/Interfaces/IOrganizationServiceAsync2.cs) Interface.  However this will only cancel it up to the point of send.  Once the request is inflight it cannot be canceled.
