### ISSUE TITLE
Creating related entities in one operation fails to create related entities

### ISSUE THREAD

**Issue by ryanspain** [microsoft/PowerPlatform-DataverseServiceClient#98]
As per [this](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/org-service/entity-operations-create#late-bound-example-1) sample code on creating related entites in one operation, we should be able to create an _Account_ and it's primary _Contact_ in one operation. i.e. `service.Create(...)`.

**Using CrmServiceClient:**
- The Account is created ✔
- The Contact is created ✔
- The Contact is linked to the Account as the Primary Contact ✔

**Usign CdsServiceClient (0.3.10-Alpha):**
- The Account is created ✔
- The Contact is not created ❌
- The Contact is not linked to the Account ❌

**Repro:**
Here is the [slimmed down] sample code from the docs. Simply alternating between `CrmServiceClient` and `CdsServiceClient` will reproduce the issue.
```csharp
// Use Entity class with entity logical name
var account = new Entity("account");

// Set attribute values
    // string primary name
    account["name"] = "Sample Account";

// Create Primary contact
var primaryContact = new Entity("contact");
primaryContact["firstname"] = "John";
primaryContact["lastname"] = "Smith";

// Add the contact to an EntityCollection
EntityCollection primaryContactCollection = new EntityCollection();
primaryContactCollection.Entities.Add(primaryContact);

// Set the value to the relationship
account.RelatedEntities[new Relationship("account_primary_contact")] = primaryContactCollection;

// Create the account
Guid accountid = svc.Create(account);
```

**Comment by MattB-msft** [comment]
@ryanspain 
This feature may be dropped from the ServiceClient going forward as this does not translate properly to the WebAPI.  We are determining if we can support it.

**Comment by ryanspain** [comment]
@MattB-msft, thanks.

Looks like this is already supported by the Web API through a deep insert, described [here](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/create-entity-web-api#create-related-entity-records-in-one-operation) in the docs.

It supports both single-valued and collection-valued navigation properties.
```http
POST [Organization URI]/api/data/v9.0/accounts HTTP/1.1
Content-Type: application/json; charset=utf-8
OData-MaxVersion: 4.0
OData-Version: 4.0
Accept: application/json

{
 "name": "Sample Account",
 "primarycontactid":
 {
     "firstname": "John",
     "lastname": "Smith"
 },
 "opportunity_customer_accounts":
 [
  {
      "name": "Opportunity associated to Sample Account",
      "Opportunity_Tasks":
      [
       { "subject": "Task associated to opportunity" }
      ]
  }
 ]
}
```
Here assuming the same can be achieved in the service client.

**Comment by MattB-msft** [comment]
Yes, there are limitations in that process that do not exist in the org service implementation. 
Thus my statement "does translate properly" vs "does not support" :) 

We are prototyping a few different ideas to see if we can get it to work properly and consistently with the organization service client implementation.   Right now, it seems we may have to add limitations over what your used to in the organization service, or not, and see if folks bump into the limitations.  really depends on how the prototypes work out. 

If it is included it will be after the next update,  the next update is focused only on rename and NS changes.
